### ISSUE TITLE
New volume label

### ISSUE THREAD

**Issue by 135792** [pbatard/rufus#1036]
When you choose FAT32 to format it, the new volume only supports English letters and numbers，and you can try to name it in Japanese.

**Comment by pbatard** [comment]
I don't see what the problem is. Here's what Windows File Explorer will show if you create a FAT32 file with a Japanese label in Rufus:
![image2](https://user-images.githubusercontent.com/1206968/31364809-3874f63e-ad5f-11e7-996a-dfbe9ed882d5.png)

FAT32 labels may not be compatible with non ASCII, but you can place a label with whatever glyphs you want (provided Windows has support for it) in `autorun.inf`. And that is why Rufus does let you use whatever label you want.
