### ISSUE TITLE
Which BootManager is used for ISO-to-USB copies?

### ISSUE THREAD

**Issue by bsto** [pbatard/rufus#1076]
Assume I use Rufus v2.18 under 64bit Win 7 and drag an ISO file onto it.
The (automatically) selected Partition scheme is:

"MBR partition scheme for BIOS or UEFI-CSM"

Sorry for this question: But which boot manager does Rufus use to store the ISO image on the USB flash drive?

grub?

Or is the used boot manager pre-determined by the ISO image?

How can I find it out the used BootManager?

Can I change it?

Ben

**Comment by pbatard** [comment]
> which boot manager does Rufus use to store the ISO image on the USB flash drive?

For a Windows 7 ISO in BIOS or UEFI-CSM mode, Microsoft's proprietary boot manager called `bootmgr` will be used.

> is the used boot manager pre-determined by the ISO image?

Yes. There are plenty of boot managers to go around, and each ISO will use the most appropriate one. For Windows ISOs, it will never be GRUB or Syslinux, which are mostly designed to be used to boot Linux.

> How can I find it out the used BootManager?

The log may give some indication, but otherwise, you're supposed to know that if there's a `bootmgr` file residing on the root directory of the ISO, then Rufus will try to use that.

> Can I change it?

Not using Rufus. We use the most appropriate boot manager for each ISO to ensure boot __reliability__ and avoid bad surprises. You may try to use a different boot manager, but you're entirely on your own then.

Since I believe I answered your query, I will close this issue.
