### ISSUE TITLE
对rufus的建议

### ISSUE THREAD

**Issue by IFRFSX** [pbatard/rufus#1092]
我发现新版本的rufus没有对移动硬盘的支持，请加回来。
而且我想还建议添加一个对单独分区的写入功能，谢谢。
建议添加对HaikuOS的ISO的支持。
如果再有bug，我会尽量报告。

**Comment by pbatard** [comment]
1. Sorry, but I cannot provide support in Chinese.
2. There is a checklist, which references the FAQ. By looking at the FAQ you would have found the answer to 2 questions you are asking: One with regards to the [detection of USB HDDs](https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected) and the other with regards to [partition support](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiple_partition_support).
3. Due to lack of time and lack of usage, I currently have no plans to look into adding Haiku support.
