### ISSUE TITLE
Can't boot windows 10 from usb hdd

### ISSUE THREAD

**Issue by jebusss** [pbatard/rufus#1093]
So i have a msi gl62mvr laptop and i'm trying to boot windows 10 from a usb hdd, the hdd works on other computers pls don't tell me to get a new one or try other usb ports i've tried all that and those are not the issue, it gets recognized if i set the bios to legacy but then i can't install it, it i have in on uefi it's not recognized, the usb hdd is formated as gpt fat32 but i've tried all possibilites in the format and bios settings and it doesn't work

**Comment by pbatard** [comment]
Well, first of all, you didn't follow the checklist. It exists for a reason.
Second, since you say the same USB HDD boots fine on other computers but not this one, then clearly the issue has to do with this specific system and you should try to get support either from its manufacturer or other users with the same computer. If your computer is UEFI based, and you formatted your drive in "GPT partition mode for UEFI" with FAT32, then it should boot in UEFI mode. If that is not the case, you need to contact the manufacturer for support, as this is hardly the place to obtain support for MSI hardware, or what options should be set in your UEFI firmware for it to boot your HDD. Sorry.
