### ISSUE TITLE
Nice translation system?

### ISSUE THREAD

**Issue by marsjaninzmarsa** [pbatard/rufus#1109]
Encouraged by the request on project page, I was ready to give some polish to Polish translation, but when I've came across [Translators howto](https://github.com/pbatard/rufus/wiki/Localization), I doubted - to much  effort for only few strings. Why not use Transifex, Weblate or one of other such online tools? Make collaboration easy. ;)

**Comment by pbatard** [comment]
>  Why not use Transifex, Weblate or one of other such online tools? Make collaboration easy. ;)

Because they don't support the `.loc` format that we use due to being very size conscious, and also because, considering that the translation framework had no trouble to get established without these tools, and it definitely saved us __weeks__ which we could use for other features, it's hard to see the point of dropping everything right now to make life easier for a __very limited__ number of people. Also, we did try to use online collaboration tools when we started adding translations, but found that they wern't much help with the custom format that we used.

That's not to say that we are not going to improve on the translation framework __eventually__ (for instance, we just removed the whole manual positioning aspect for the upcoming 3.0, which was a major endeavour), but due to __time constraints__, helping you save a few minutes it takes to edit and test the `rufus.loc` file in situ is not a very high priority.

Every feature, such as using Transifex or Weblate, comes with a very real __cost__ for the developer, that is often difficult to properly appreciate for people who just want to collaborate. Please be mindful of assuming that switching to using such or such framework is a 5 minute operation... 

Eventually, I am planning to enable the use of PoEdit for all translation updates (and then we can see about online facilities that allow collaboration on `.po`/`.mo` files). But, realistically, due to feature prioritization according to overall usefulness and time, this isn't going to happen for 2 or 3 years at best.

Now, if editing a simple text file is too much of a barrier or entry for collaboration, so be it.
