### ISSUE TITLE
Data Collection and GDPR

### ISSUE THREAD

**Issue by tpavesi** [pbatard/rufus#1116]
Just want to give a heads up that Europe has now a GDPR framework for data collection.

Thanks.

**Comment by pbatard** [comment]
Yes I know. However that doesn't apply to us since we don't use it, even internally, to individually identify users, and the "data" we collect is the bare minimum we need for the update check. You may want to read [this](https://github.com/pbatard/rufus/wiki/Security#Data_Collection_and_User_Consent).

**Comment by tpavesi** [comment]
Thank you.
