### ISSUE TITLE
Recommend users try NTFS if FAT32 fails

### ISSUE THREAD

**Issue by cowwoc** [pbatard/rufus#1122]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [ ] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [ ] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I ran into a similar problem as https://github.com/pbatard/rufus/issues/992 where Rufus would run fine but my Dell XPS 13 laptop wouldn't see the USB key in UEFI GPT mode when formatted as FAT32. Eventually I tried NTFS and it just worked.

Given the number of people running into this problem on Google (USB key not showing up in boot menu) I recommend you enhance the documentation (somewhere prominent, not the FAQ) that says "If your system does not see FAT32-formatted USB keys, tried NTFS as well."

I understand that Rufus is not at fault here, but you'd save yourself and your users a lot of headache if you make this troubleshooting step more obvious ;) Thank you in advance.

**Comment by pbatard** [comment]
> somewhere prominent, not the FAQ

There's no other place to document what you ask but the FAQ. The home page is certainly not a place to start listing a bunch of very hardware-specific advice (_"If you have model XYW-8974, then you should ..."_) coz if I were to list all the quirks that one may run into it would become just that, a list of quirks that also happens to provide a download link, and nobody would bother reading through a list of 30 or 50 quirks to find out if their platform/hardware/environment is concerned. There's also the matter of needing to translate each quirk into all the languages that the homepage is translated into, which is not gonna happen.

And I don't think I even want to do it on the FAQ. First of all, since you didn't provide a log of how you created the FAT32 flash drive and then the NTFS one, I can't corroborate that your assertion that NTFS vs FAT32 is the actual difference that made it work (I'm very inclined to think that it could be something else, that the log would highlight, as having an UEFI firmware that boots NTFS and not FAT32 is __unheard of__ and would be such a breakage of basics UEFI specs, which Dell should definitely know about and have been able to test, that it requires extraordinary evidence to prove). Also, Rufus tends to prefer NTFS over FAT32 for Windows installations (but was made to pick FAT32 in some circumstances __precisely because some users wanted just that__), and IMO, it is squarely the job of the user to try again, by tweaking parameters, if they can't seem to boot the flash drive they created.

This is because, no matter what an application like Rufus does, unless the user has a minimum knowledge of what they are doing as well as what some options from their hardware do, there is no _one-ring-to-rule-them-all_ set of options that Rufus can apply to guarantee that the flash drive will boot. There are simply too many firmware options that can __prevent__ boot, no matter what Rufus does. Therefore, it is the responsibility of the user to tweak and retry if the flash drive doesn't boot. And it is not the responsibility of Rufus to tell users that they should do just that, because, as far as I'm concerned and even if it sounds harsh, this is just common sense that I am expecting Rufus users to have in the first place.

&rarr; Rejected.
