### ISSUE TITLE
Option to save USB-Stick as ISO (besides VHD)

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [pbatard/rufus#1158]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.

Issue description
-----------------
Hi!

First: I really like your tool! Good work! :-)
Also: I really like that you already support ReactOS! :-)
And that is also more or less the reason for suggesting this feature... ;-)

I work since some days on a new OSS-Project called 'Ultimate Windows Boot CD with ReactOS'...
https://github.com/UWBCD/UWBCD-ReactOS
...and there the challenge was, to create a ReactOS-LiveCD with additional software... (with keeping the FreeLoader!)
I run into multiple issues by 'creating' this LiveCD with different tools...
...and one issue was, to create a ISO out of my modified version again! :D
To don't waste your time and shorten the story, I found out, that there are some tools around that can create a image out of a USB-Stick, but no one seems to be able to create an ISO! (I needed ISO for the UBCD...)
And to make the problem more difficult, I found out, that there are some tools around to convert an(y) image to an ISO, but they seem to don't support the ReactOS-FreeLoader and therefor they run into errors...

So I want to suggest you, to support the creation of an ISO-Image out of an USB-Stick, too.
Think the implementation and support shouldn't waste to much time...
...and when ReactOS gets more stable & famous, maybe more people want to create (with your tool) an (bootable) ISO out of an USB-Stick (to make a own LiveCD)!
I also wondering what all the people that use WinPE do to get there CDs created... ^^
...for those people would be this feature interesting, too!

So maybe I have luck, you don't close this issue immediately... ;-)
...and maybe you implement it at any point... :-)

Greets, Tobias.

**Comment by pbatard** [comment]
> but no one seems to be able to create an ISO!

There's a very good reason for that. As with ISO &rarr; USB there are __tons__ of incompatible methods that need to be __converted programmatically__ (which means every single one needs to get code, that can be quite complex, specifically written for it) and usually required the provision of additional files. You can find more details about this [here](https://superuser.com/a/1171956/286681).

Obviously, this would require a lot of work from me, for exceedingly little benefit, since I'm afraid, if you look at it objectively, you'll see that your request falls squarely in the "selfish" kind of what I describe [here](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want): The vast majority of Rufus users will never need a USB &rarr; ISO feature, since they'll have access to the original ISO they use to create the USB, and there are hardly any people that are going to be interested with a very specific USB &rarr; ReactOS based ISO (for which, again, I would need to add __dedicated__ code - there's really nothing generic that can be done about USB &rarr; ISO, which is why the conversion tool you found didn't work)... besides yourself.

So, sorry, but no. USB &rarr; VHD is the only means of saving a bootable USB to another format you will see and, if anything, I'd rather spend time on adding VHD compression, which will benefit a lot more people, since uncompressed VHD images are obviously very large, than add another format besides VHD.

As to ReactOS getting stable and famous, my take on that is that it'd be a lot more useful to people if they sorted the ability to install and boot ReactOS directly from USB, as it is currently completely broken and has been so for years. This is actually the reason why I added ReactOS bootloader support in Rufus (which again, even as ISO &rarr; USB __is__ dedicated code that I had to spend extra time on), in the hope that the project would provide a Windows-To-Go like functionality for people who may need it. Sadly however, they don't seem to be interested in fixing USB boot support... which is yet something else that I'd rather spend time on if I had it, to help the project, rather than adding USB &rarr; ISO conversion support in Rufus, as this too would be beneficial to an awful lot more people.

I hope I don't come across as too negative here (if I do, so be it), but I have to reject your request.

Oh, and please, refrain from saying something like _"I think the implementation and support shouldn't waste too much time"_ when requesting a new feature, unless you are a developer yourself and have actually implemented a similar feature in your own software. For the record, I spend a lot of time ensuing that USB Syslinux support would work as expected, and I'd really have to spend as much time to have to do the reverse for ISO Syslinux (i.e. ISOlinux), by maintaining a new bunch of files on the server, that need to be updated regularly, and implement a whole fallback download mechanism, and then some more (such as dealing with the surprisingly angry users who want me to provide all these files as a single zipped download for offline usage).
