### ISSUE TITLE
Queue Multiple Drives to Reformat with the same 'Format Options'

### ISSUE THREAD

**Issue by flisz** [pbatard/rufus#1166]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I would like to mass re-format usb drives or queue multiple usb drives for re-formatting with the same settings. Is this possible with rufus? I could write a little script to do it pretty easily if rufus had command-line support. 

Log
---
```
Rufus version: 3.1.1320 (Portable)
Windows version: Windows 10 64-bit (Build 17134)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0409
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
Using autorun.inf label for drive J: 'FAT32'
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
Found USB 2.0 device 'USB Disk USB Device' (1221:3234)
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
10 devices found
```

**Comment by pbatard** [comment]
I'm afraid that Rufus is not a utility you want to use for mass duplication. It certainly wasn't designed for it an I'm not really planning on adding features to help doing this, as my time is limited and I will always prioritize features that will benefit a much larger number of people (such as adding persistence support for Linux image, which I've been planning to do for years now, and still haven't had a chance to find enough time for). All this to say that, you're probably better off using a different method for duplicating drives, especially as the current automation level in Rufus through command line support (#111) is likely to remain at a very basic level for a long time (read __a few more years__), since it's a super-low priority feature.

Now, the one advice I would give you, if you want to duplicate between device is to simply create a VHD/DD image of an original device that is set exactly as you want it, and then use that VHD/DD for duplication. For the record, Rufus can save an uncompressed VHD image of the currently selected device if you click _Show advanced drive properties_ (then you will see a "Save" icon next to the device).

But really, I wouldn't even use Windows to do that. Just use Linux and `dd` from a master device, and you'll have all the scripting and automation capability you need.

Considering that I have no plans of improving command line support in Rufus any time soon, since it's not a feature that many people require, I'm going to close this request.
