### ISSUE TITLE
can we get a "verify written data" option?

### ISSUE THREAD

**Issue by divinity76** [pbatard/rufus#1168]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

i would like an option for rufus to read back and verify all the written data, after completion, to make sure that all data is intact on the target device after writing. i realize that will take (much?) more time, and i'm not saying this option should be enabled by default, but it would be nice to have such an option nonetheless.

(and finally, may i remove the checklist stuff? it really isn't applicable to this feature request)

**Comment by pbatard** [comment]
I'd like to do that, but there exists a major problem with doing so in Windows which is illustrated [here](https://github.com/QubesOS/qubes-issues/issues/2051).

If you don't want to read the whole issue, the problem is that whenever Windows detects a partition it can mount, which it will tend to do for whatever is UEFI based as there should be a FAT32 ESP, it will create files there that are going to break validation. So I'm going to have either of these issues:

1. A validation that Rufus says fails because Windows will have created a 'System Volume Information\' directory with a bunch of random files.

2. A validation that Rufus says succeeds (provided we manage to keep Windows off the ESP partition for long enough) but that, when verified independently after people have left their flash drive plugged for more than a few seconds on Windows, will report failure because the 'System Volume Information\' directory, with people therefore raising doubts as to whether the Rufus validation check is actually reliable.

That's not to say I'm not planning to add a validation check for DD Images at some stage (I think that, with requesting exclusive access, I may be able to keep Windows off modifying the drive for the verification pass), but it is more tricky than it looks. And one also needs to ensure that it's the actual data from the USB that is being read and not something that Windows had kept in a memory buffer (since it will have just used such a buffer for writing), which can also be tricky.

Also please be mindful that verifying extracted ISO content (i.e. content that wasn't copied in DD mode from a DD image or an ISOHybrid image, but individual binary comparison of each file extracted) is also a completely different beast, and would be a whole different feature in itself.

In other words, this is more complex than it looks and, as with any feature I am trying to provide in Rufus, such as the MD5/SHA-1/SHA-256 computation (which I spent a lot of time optimizing so that it were as fast as possible) if I am to implement it, I want to do it well. So that means solving all of the problems I highlighted above, which will require a lot of time that I don't have right now as I have still plenty of other features that are higher priority than this.

Because of this, I am not planning to add a "verify written data" anytime soon, sorry.

> (and finally, may i remove the checklist stuff? it really isn't applicable to this feature request)

Just leave it unchecked. I'd rather having people go through the checklist and decide what is and isn't applicable, than erroneously assume that it's not applicable to them as a whole, and remove it wholesale. I'm already having enough trouble with people truncating logs, even though I am pretty adamant that it should never ever be truncated.
