### ISSUE TITLE
unsupported image

### ISSUE THREAD

**Issue by LudovicoLowe** [pbatard/rufus#1171]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
hi,
i created an iso of a folder containing .sys and .bss linux 6.03 system files, with WinCDEmu (so in a windows system).
at the moment of loading it, it is said "unsupported image", think due to the MBR missig..
how can i add it to the iso?
thank you.

Log
---
```
Rufus version: 2.15.1117
Windows version: Windows 10 64-bit (Build 17134)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0410
Detected installed Windows Language Pack for 0x0409 (English (English))
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found non-USB removable device 'KINGSTON SUV400S37120G' => Eliminated
Found USB 2.0 device 'Generic Storage Device USB Device' (15A4:1336)
Device eliminated because it appears to contain no media
Found non-USB removable device 'WDC WD10EZRZ-00Z5HB0' => Eliminated
Found USB 2.0 device 'VendorCo ProductCode USB Device' (FFFF:5678)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 489, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {BA07FBC2-0DCE-4B02-80F9-AC3B8F5F6627}
Max parts: 128, Start Offset: 17408, Usable = 4027546112 bytes
Partition 1:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Microsoft Basic Data'
  ID: {F575E732-445A-4C21-AE44-5945B32B3C24}
  Size: 3.7 GB (4026514944 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Scanning image...
ISO analysis:
  Image is an ISO9660 image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'CDROM'
  Size: 70 KB (Projected)
```

**Comment by pbatard** [comment]
I'm sorry but this is not the place to ask how to create a bootable Syslinux based ISO. Also, since there are no MBR's on ISO, this has nothing to do with a missing MBR.

Have you tested that the ISO you created actually booted as a real CD or DVD image (you can do that through VMWare or through other VM software). __Unless__ you have tested that your ISO can be used as a real disc media to boot a BIOS computer, then I'm not going to help you, as this is out of scope for Rufus, and (due to time constraints) there's only so much I am willing to help people with.

This is a pure "how do I created a Syslinux bootable ISO" question, that should be properly __researched__ first (you should have no trouble finding how Linux distros do it for instance, but, __yes__ it might require you to put some time and effort into to try to understand it, which you __MUST__ do if you want to accomplish anything), and, if you are still having trouble, asked on forums that are dedicated to that topic, which this issue tracker is not.

As such, I will close this request as off-topic.
