### ISSUE TITLE
Text in the log is very hard to read when scaled 1.5 on a 4k screen

### ISSUE THREAD

**Issue by ripdog** [pbatard/rufus#1198]
(Hope you don't mind me removing the checklist as this is not a functional error)

The log uses very small text which seems to work fine on an unscaled 1080p screen, albeit somewhat blurry. When I move the log window over to my 4k screen on a 1.5 scale, I find the text becomes uncomfortable to read, with what appears to be anti-aliasing artifacts making it worse. 

I took a photo with my phone, it seems to show the issue.

![20180829_110910](https://user-images.githubusercontent.com/174944/44755939-5aa72d00-ab7c-11e8-97d1-c022d2830129.jpg)

The rest of the UI scales fine on my 4k screen.

**Comment by pbatard** [comment]
I have a 4k monitor and I'm not seeing much of an issue on my display:
![image1](https://user-images.githubusercontent.com/1206968/44787212-66035400-ab8e-11e8-8a75-7cd8f5d55bd3.png)

Granted, the font is not as sharp as one would like, but that has mostly to do with using a non integer zooming factor more than anything else (1.5x vs 2x), and Windows' handling of font scaling. Moreover the log is mostly designed to be used for troubleshooting, so having it look awesomely good is a very secondary item. Unless there are a __very large__ amount of people complaining about this, I'm not planning to waste time working around Windows' improper handling of font scaling: it's 100% Windows' job to make fonts readable at all point sizes and at all zoom factors, not Rufus', so if I would suggest you report this issue to Microsoft so that they improve their font handling.

As such, I will close this issue.

PS: For the record, I'm using a 200% zoom factor on my 4k, which is the much better spot for having an UI that looks great.
