### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tiptop777** [pbatard/rufus#1200]
Good Day, I wrote to you about the Rufus program, the program is good, but it's impossible to make RuFUS create multi-boot flash drives? I would like to write several operating systems on one flash drive. It would be nice that Rufus could create multi-boot flash drives. Thanks!

**Comment by pbatard** [comment]
And it would be nice if people followed the checklist that guides them directly to the FAQ, or look for similar issues, so that they can find out by themselves if their __very common__ question has [already been answered](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiboot_support) over, and over, and over, and over, and over...
