### ISSUE TITLE
Created FreeDOS USB, failed to updae BIOS with it

### ISSUE THREAD

**Issue by weedy** [pbatard/rufus#1203]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Issue description
-----------------

The Award BIOS flasher complains about not having enough RAM. After a bunch of googling I found a Dell page* that lead me through making another USB and that one worked fine. Picking both sticks apart I see the Dell program creates a "disc" with HIMEM.SYS while Rufus makes a very very clean disc without any sort of memory BS.

Could you consider adding another FreeDOS option with this memory manager thing or maybe have it be a menu option just like keyboard locale?
Do I just need to manually add DEVICE=\HIMEM.SYS DOS=HIGH to the CONFIG.SYS?
Is this BIOS flasher just shit and I should ignore this "problem" as a one off?

Dell CONFIG.SYS follows.
```
STACKS=0,0
DEVICE=\HIMEM.SYS /GATEA20=FAST
DOS=HIGH
lastdrive=Z
DEVICE=\RAMDRIVE.SYS 16384 512 1024 /E
SHELL=\COMMAND.COM /e:3072 /p
```
* https://www.dell.com/support/article/ca/en/cadhs1/sln143196/how-to-create-a-bootable-usb-flash-drive-using-dell-diagnostic-deployment-package-dddp-?lang=en

**Comment by pbatard** [comment]
> Could you consider adding another FreeDOS option with this memory manager

I'm afraid not. It's really up to you to add the options you need ontop of the __bare__ DOS that Rufus installs, to achieve what you want.

If were to start customizing DOS memory usage and other options for various scenarios, first, I wouldn't see the end of it (because everyone would now want a different option that suits their specific situation), and second, I'd now have to answer to zillions of e-mails asking me to help them decide what option they should select.

The keyboard locale selection is pretty easy to understand, even for people who aren't familiar with DOS. A mem selection would be a completely different story, and the last thing I want is to have to find myself having to guide hundreds of DOS users on what option is most appropriate for them. Heck, even when I explicitly tell people to try one option and try another if the first one doesn't work, as I do for DD-mode vs ISO-mode with a very prominent dialog, people completely disregard what Rufus tells them and I find myself having to answer support queries that I shouldn't have. Therefore, there's no way I want to go through multiplying options in Rufus where it isn't absolutely needed.

If you are using DOS, then you are required to know what settings you should add to the bare DOS that Rufus creates, in order to have the DOS application you want properly running. &rarr; Rejected.
