### ISSUE TITLE
Would like to select other versions of Freedos

### ISSUE THREAD

**Issue by h3rb** [pbatard/rufus#1218]
6.22 is one version, but earlier versions may hold greater compatibility with the XT

**Comment by pbatard** [comment]
Can't distribute 6.22. Microsoft __owns__ the distribution rights, and HP, who tried to distribute it in a version on their DOS software got a cease and desist from Microsoft.

The only reason MS-DOS was included up to Windows 8.1 is because the DOS files were included in `diskcopy.dll` on the Windows system therefore Rufus did not need to embed them. But that DLL was removed in Windows 10. So that means no MS-DOS.

Now, if you __actually__ have found a verifiable incompatibility between a DOS application running under FreeDOS vs the same application under MS-DOS, __please__ contact the FreeDOS mailing list, as they will be happy to hear from you, since their goal is 100% compatibility with MS-DOS.
