### ISSUE TITLE
Rufus website is down

### ISSUE THREAD

**Issue by cyfrost** [pbatard/rufus#1228]
Hi, I don't know where else to say this but looks like it'd be noticed here. The rufus website is down. Is this a maintenance chore?

![capture](https://user-images.githubusercontent.com/12471103/46996586-d2d0ae80-d13a-11e8-98ca-7fa482c51b30.PNG)

Thanks!

**Comment by blackcrack** [comment]
you meant this ?

```
Your connection is not secure

The owner of rufus.akeo.ie has configured their website improperly. To protect your information from being stolen, Basilisk has not connected to this website.

rufus.akeo.ie uses an invalid security certificate.

The certificate is only valid for the following names:
  www.github.com, *.github.io, *.githubusercontent.com, *.github.com, github.com, github.io, githubusercontent.com  

(Error code: SSL_ERROR_BAD_CERT_DOMAIN)

[Add Exception...]
```

well, this is at my domain the same, because self signed Certificate ..
you trust or you trust not this page.. i trust and add a Exception..

best regards
blacky

**Comment by cyfrost** [comment]
@blackcrack take a look at OP, edited with screen capture.

**Comment by yiijam** [comment]
use this site https://rufus.ie

**Comment by cyfrost** [comment]
@yiijam Thank you, that does it for now. Although it still remains to be seen why the github pages version is down. Also, I was wondering, why not take a https://www.rufus.com domain ? I don't mean to come across as rude or abraisive, just genuinely wondering :)

**Comment by pbatard** [comment]
> Also, I was wondering, why not take a https://www.rufus.com domain ?

It was already taken. And `.com` is for commercial. I'm not selling anything...

Also, next time you open an issue, please check the existing ones. There literally was an issue than answered your questions right before the one you opened (yes, the checklist about looking for prior issues does apply even if it's not a Rufus application problem). See #1227.

As such, since this is a duplicate, I will close this one.
