### ISSUE TITLE
FeatureRequest: add writing speed

### ISSUE THREAD

**Issue by Testato** [pbatard/rufus#1262]
﻿please consider to add a writing speed indication like in Etcher.
It is very useful imho

**Comment by pbatard** [comment]
Asked a few times before, but I'm afraid Zadig is not a benchmarking tool and whereas Etcher writes only images in DD mode, where write speed computation is relatively easy to do, Rufus primarily writes in ISO (File copy) mode, where this is a lot trickier, and where, of course, the write speed provided is pretty much useless since it will never match the actual write speed of the device. And I'm not even talking about Windows To Go (and let me tell you, computing the write speed for this mode will be a lot of "fun", since we don't have access to the size of the files that are being written when the Windows image is being applied...)

I'm afraid I have much more beneficial features to add than what can essentially be qualified as "eye candy" (you'll see some of these new features in 3.5), so, unless someone does send me a fully developed pull request, that works for DD, ISO and Windows To Go mode, and that I won't have to spend a lot of time reworking and applying, you're __not__ going to see any kind of write speed indication in Rufus for 2 or 3 years __at least__.
