### ISSUE TITLE
When mouse is positioned on one of the toolbar buttons and arrows are used to move  between them focus bounces to the button under the mouse

### ISSUE THREAD

**Issue by lukaszgo1** [pbatard/rufus#1290]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Issue description
-----------------
to reproduce:
1. Start Rufus.
2. move the mouse to the Show the log button on the toolbar.
3. move with tab key to the toolbar.
4. try moving with the left arrow to one of the previous controls.

Notice that after very short moment focus returns to the show the log button.

**Comment by pbatard** [comment]
And there we have the second part of "trying to make an application look modern whilst being limited to using very reluctant old Win32 controls".

That toolbar has taken more than a good chunk of the UI redesign time I went through for 3.0, and yes, it does have multiple issues. For one thing, the Log button seems to get selected according to God know what reason that Microsoft is unable to explain.

So I guess the issue you report is related to that, because it appears that, whenever Windows doesn't know what to select on the Rufus UI, it will try to select the log button regardless of what logic dictates it should select.

I literally spent __days__ trying to figure out what I could do about it but got nowhere, and I'm afraid I can't see going back there as a good investment of my time when this is a minor annoyance (if you insist, or if you move the cursor elsewhere, then you should be able to navigate the toolbar with the arrows).

So I'm afraid I'm going to have to decline looking into that issue.

Now, if some day I stumble on the reason why Microsoft's toolbars behave in the way they do, with a workaround on how to prevent the darn log button from being unwillingly selected, I'll apply that workaround. But until then, I'm just going to have to ask you to just accept what I hope you will agree is a minor annoyance.
