### ISSUE TITLE
no good link for upgrades(old version of Rufus)

### ISSUE THREAD

**Issue by DHeerAlex** [pbatard/rufus#1291]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I would make a usb key of the lastest version of Ubuntu Server but like it's an old version of Rufus. I decide to upgrade the software but when I checked it says that there are no updates(upgrades).
So there are no new files to formatte the iso.
image name : ubuntu-18.04.2-live-server-amd64.iso

Log
---
```
Rufus version: 2.18.1213
Windows version: Windows 10 64-bit (Build 17134)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x040C
Will use default UI locale 0x040C
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'fr-FR'
Found USB 2.0 device 'USB DISK 2.0 USB Device' (26BD:9917)
Using autorun.inf label for drive H: 'Ubuntu-Server 18.04.2'
1 device found
Disk type: Removable, Disk size: 32Go, Sector size: 512 bytes
Cylinders: 3899, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x1A70E036
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 29.9 GB (32076988416 bytes)
  Start Sector: 2048, Boot: Yes
Checking for Rufus updates...
Checking release channel...
Checking beta channel...
Updates: Unable to access version data
Checking for Rufus updates...
Checking release channel...
Checking beta channel...
Updates: Unable to access version data

```

**Comment by pbatard** [comment]
Yes, that is because a DDoS attack forced us to change servers, so we are now being hosted by GitHub.
However, GitHub does not serve `.ver` files as `text/plain` which is what older versions of Rufus expect, so older versions of Rufus will reject the update data as invalid, and therefore not see the update.

We have of course dropped the `plain/text` requirement in newer versions, but we can't do anything for older versions, and the only way GitHib will set the Mime type for `.ver` to `text/plain` is if we place a [request to IANA](https://tools.ietf.org/html/rfc6838#section-5) which is a long, cumbersome process and which we see unlikely to be accepted if the whole reason behind registering the new Mime is because older versions of a single application can't read update data otherwise.

Still, if you are bothered by this, you are __encouraged__ to contact IANA to see if they want to register the new Mime and follow up with their requirements.

All you need to ask, really, is that you would like to have files with a `.ver` extension to be registered as `text/plain`. If IANA accepts that, then the Mime can be added to the DB GitHub uses and Rufus updates will work with older versions.

Now, if all you want is to download the latest version to create your Ubuntu USB, you can just get it from https://rufus.ie (or https://rufus.akeo.ie which points to the same page). The URL for that website is plastered __all over the place__ be it in the Rufus about dialog, this GitHub project and so on, so, even if the update check fails, you shouldn't have much trouble downloading the latest version from its official site. Note that there is no difference whatsoever between what Rufus downloads as an update and what you download from the homepage.

As I believe I have answered your question, I will close this request.
