### ISSUE TITLE
Adding feature for integrating driver pack folder into the new installation

### ISSUE THREAD

**Issue by dvdvideo1234** [pbatard/rufus#1303]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the `Log` button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Is it possible in the process of preparing a USB bootable flash drive to integrate also the drivers needed for the specific machine? For example, I have a driver pack for my home server MB as `*.inf` and `*.sys`. Is it possible to integrate these into the newly created installation using Rufus?
So far I made my [own, free script](https://github.com/dvdvideo1234/WindowsBatches/tree/master/usbStickDriverWIM) which does exactly that using the command prompt, however, I want to contribute it to Rufus. Probably a button or a checkbox can be added labeled `Integrate the following drivers' folder into the new installation`, click `Browse` and select the folder.

Log
---
```
Rufus x86 v3.5.1497
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
0 devices found
Checking for Rufus updates...
Checking release channel...
No new release version found.
```

**Comment by pbatard** [comment]
I'm going to have to reject that request for the time being.

The vast majority of Rufus users do not need to add custom drivers and what you are trying to add here is a custom SysAdmin/PowerUser operation to a tool that is not designed to be SysAdmin/PowerUser friendly.

See point 3 from [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want).

From what I gather, this is mostly required for people who install Windows 7, a platform that will be sunset in less than a year, to inject things like USB 3.0 drivers and stuff, so it doesn't strike me as a __must have__.

Also the last thing I want is add a UI button for a seldom used feature, because if I were to start to do that, there are about dozens of features, just like the one you request, that I'd also need to add to the UI on the principle of fairness (because if you get what you request, why shouldn't also the people who also requested an equally important different feature in the past). So the best you'll ever get, if it turns out that the feature you propose becomes requested by more than a handful of users, will be a cheat mode.

Now, I understand that this is not the answer you wanted to hear (especially as you proposed to help add the feature), so maybe I need to point out that, unlike what many people seem to be thinking, developing Open Source software is not about adding every single feature possible under the sun (i.e. _"Hey, wouldn't it be cool if Rufus also did X, Y, Z?"_), even if each feature might genuinely be helpful to a minority of people. That's because, if you do just that, then you quickly end up being faced with feature creep, and maintainability becomes a major headache. So I do try to limit the features I add to the ones that I estimate will see most demand, and what you propose does not currently look like one of them...

Of course, things do evolve, and I am willing to review that stance if, for instance, Microsoft botches another release of Windows 10, or a large group of people starts to use new hardware for which drivers are not natively available by default, and having driver injection does becomes a desirable feature then.

But for the time being, I'm afraid I'll just have to __reject__ this request. Sorry.
