### ISSUE TITLE
Native FAT32 boot method with files larger than 4GB

### ISSUE THREAD

**Issue by kq01526** [pbatard/rufus#1312]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Issue description
-----------------
@pbatard The FAQ already mentions https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_add_multiple_partition_support . But do you realize that this can actually be used to create Win10 USB setup media holding files larger than 4GB while still booting from FAT32 instead of NTFS, i.e. allowing UEFI hardware that is not able to boot from UEFI:NTFS to still boot and even with Secure Boot enabled?

It's described in option 2 over there: https://blogs.technet.microsoft.com/askcore/2013/03/20/creating-bootable-usb-drive-for-uefi-computers/

Would be kinda neat if Rufus could provide a GUI for it, since there is hardware out there after all which does not work with UEFI:NTFS. And this would basically achieve what users were asking for in https://github.com/pbatard/rufus/issues/1245 but without having to alter/split any files (just copying them around and distributing them across two partitions instead).

**Comment by pbatard** [comment]
I believe I already addressed what you request in #1245.

1. People who are adamant that Secure Boot should not be disabled even __TEMPORARILY__ for an installation media appear to be irrational and don't seem to understand what Secure Boot is really about. Adding workarounds for irrational people is never a good use of a developer's time.
2. If you are still bothered that UEFI:NTFS can't be signed for Secure Boot signed (which I would very much do if Microsoft allowed it), then please send your complaints to Microsoft, as they are the ones who have __abusively__ decided that anything GPLv3 can't be signed for Secure Boot.
3. There is __NO__ x86 hardware in existence that I am aware of where a user does not have the ability to disable Secure Boot.
4. The split solution is actually slower and worse (since it is wasteful in space and creates issues for Win7 and Win8  users __who cannot access 2 partitions at once on removable media__) than UEFI:NTFS.
5. If people have issues with regards to their hardware and UEFI:NTFS, I'd rather we work these out (so far they seem limited to old HP hardware and some Macs) than decide that, because a solution only works 99.9% of the time, a complete alternate solution must be provided. UEFI:NTFS as well as the NTFS drivers are Open Source. For one thing, if the issue is with the NTFS driver, I'd __much__ rather have people help troubleshoot it, as it would benefit A LOT more people than the ones who want to install Windows (having an NTFS driver that works on ALL UEFI platforms out there would benefit a very large number of people), and if the issue is not with the NTFS driver, then, considering that the code for the UEFI:NTFS bootloader itself is very small and easy to understand, I'd also prefer to have people try to help with the troubleshooting when I can't replicate their issues due to lack of access to the specific hardware.

All in all, I still see no good argument for implementing the partition, __ESPECIALLY__ as it would need to work for removable media and on Windows 7, Windows 8 and early Windows 10 platforms, __that completely lack the ability to mount two partitions at once__ (IIRC this feature was added in Windows 1703), thus requiring a weird mount/change partition type/unmount/refresh dance for the platforms I mentioned. And what I know of Windows partition refresh (I'm having enough trouble with that in trying to add support to Linux persistent partitions for the next version) does not leave me optimistic about this whole thing being as much as a ball in the park as its proponent suggest...

So, once again, no, I am not planning to implement the "partition split" solution. If people have an issue with Secure Boot having to be disabled, they can take it to Microsoft, because they're the only ones being responsible for that. And if they have a problem with their hardware not working with UEFI:NTFS, then they can open an issue and we'll take it from there.
