### ISSUE TITLE
No artifacts in appveyor!

### ISSUE THREAD

**Issue by Karaulov** [pbatard/rufus#1318]
I can't download night build from appveyor!

![CEAfY2x 1](https://user-images.githubusercontent.com/6445336/58395528-5a778780-8051-11e9-9719-b9fc5a6e582c.png)

Please fix this issue!

**Comment by pbatard** [comment]
There are __NO__ downloadable night builds and there never will.

The reason is, I don't want people to start spreading __UNSIGNED__ Rufus binaries on the internet and say they are "official", because, and this is the part I really, really would like people to understand, this will open the door to malicious actors spreading their own versions of Rufus, laced with malware, and passing them as "official".

There already are "fake" versions of Rufus out there that contain trojans (as a matter of fact there are at least 2 or 3 of those for any new version I release), but of course, when you know that official versions of Rufus are always digitally signed (with a signature that should say _"Akeo Consulting"_), and none of these malicious versions are, it makes it easy to avoid them.

Remember, Rufus is a Windows application that needs to run elevated, it's quite popular, and it's Open Source, which makes it a desireable target to compromise for malware authors.

So, should I start to release unsigned nightly builds, Rufus users would start to __expect__ that running unsigned versions of Rufus is fine (after all, the developer themselves are publishing some!), which would open the door for malicious actors to spread their own unsigned malicious versions to unsuspecting users.

So, the only way I could ever allow AppVeyor artifacts is if I could digitally sign them... which logically mean that, one way or another, I would have to share my private signing key and allow an automated process (which might be subverted) to sign binaries that I haven't validated. Well, there's just no way that will happen, so you're never going to find automated nightly builds of Rufus, ever.

And remember, if you ever see a Rufus binary that is not digitally signed, or one where the signature does not say "Akeo Consulting", then it __is__ a fake version that you should not run.

As I believe I have answered your question in full, I will close this issue.
