### ISSUE TITLE
Error: Undetermined error while formatting [solved]

### ISSUE THREAD

**Issue by MagTun** [pbatard/rufus#1319]
Several questions have been open for this error but they don't provide a solution and all the one I checked were closed so I could post my solution. 
So I am only opening this thread to give the solution (not to ask for help, thus the checklist isn't necessary). 

1. First format your USB with Windows 10 as FAT32: 
To do it, go to `This PC` (<kbd>Win</kbd>+ <kbd>E</kbd>), right click on your USB and select `Format...` and in `File System` choose `FAT32`

> If Windows return an error, open the start menu and type `partition`and select `Create and format hard drive partitions`. In the bottom part of the window, scroll to your usb (you can find it by checking the size of the drive on the left block). Right click on the big rectangle on the right part and select `Mark partition as active` and follow along by assigning a letter and doing a format the USB as NTFS. Then redo step 1. 

2. Once your USB is formatted as FAT32, open Rufus and set all your settings but before clicking on `Start`, click on `Show advanced format options` and unchecked `Quick Format`. This will take a while (the format took 30min for an 8GB usb), but in the end it worked. 

Maybe step 1 can be ignored, but I didn't try.

**Comment by pbatard** [comment]
The problem here (and this is one I am struggling with a lot as I am introducing ext2/ext3 formatting) is that Windows, and especially Windows 10, appears to be aggressively caching the partition data from drives, and besides ejecting the media, there doesn't seem to exist an efficient way to make it refresh its view of the partition layout after it's been modified. The partition caching is problematic because as long as Windows thinks there is a partition occupying this or this range of sectors, it may prevent access to said sectors being written to.

None of the things I've tried to implement so far (calling on VDS refresh API calls, simulating a disable + enable of the disk as you would do in Device Manager) have yielded much success. For one thing, VDS seems to be completely hopeless as clearing the partition data cache, even as it is supposed do so with calls such as [`IVdsService_Refresh()`](https://docs.microsoft.com/en-us/windows/desktop/api/vds/nf-vds-ivdsservice-refresh) or [`IVdsService_Reenumerate()`](https://docs.microsoft.com/en-us/windows/desktop/api/vds/nf-vds-ivdsservice-reenumerate), and thanks to Windows' weirdness, the device disable+enable trick may appear to work fine, but can leave the device disabled the next time you replug it...

So what you want, really, is Windows to acknowledge that the partition layout it is trying to use is obsolete and should be discarded. IMO, the most efficient way to do that is to use the 2 following cheat modes in Rufus:

1. First, you should issue <kbd>Alt</kbd>-<kbd>Z</kbd>. This writes zeroes to the whole drive which should ensure that the partition table gets zapped (though one should know that, if a drive is GPT, there does exist a backup partition table near the end of the drive that could theoretically be used. However, from my experience, Windows does tend to ignore it if it finds there is no primary GPT table.
2. Let the zeroin run for a little while and then cancel it.
3. Issue <kbd>Alt</kbd>-<kbd>C</kbd>, which will cycle the USB port for the currently selected device. Of course, this only works for USB devices, and what's more, only on Windows 8 or later, as Microsoft decided to remove USB port reset, which they introduced in Windows XP, from Windows 7, only to reintroduce it back in 8... Or if you can't cycle the port just eject and reinsert the device.

If you do the steps above, then you will usually find that whatever formatting issue you were having goes away.

It should be pointed out that, obviously, Rufus does zero the partition tables (and a few more sectors just to be safe) before it repartitions and reformats a drive, but as I pointed out, it does appear that Windows was never really designed for on-the-fly changes to partition data, so, even though we apply this and pretty much all the tricks in the book we can think of to tell Windows that it should refresh its vision of the drive layout, the only consistent way we found to make it do that is to make it actively disconnect and reconnect the device (which we can't really automate, even on Windows 8 or later, as a USB port cycle can take up to 30 seconds, and, as I mentioned, disable + enable of a device can lead to that device remaining in a "zombie state").

So if you are getting errors, try the zeroing + cycle trick described above, as it will probably help.
