### ISSUE TITLE
Feature Request - Install From Serial Console

### ISSUE THREAD

**Issue by rbuckley** [pbatard/rufus#1320]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Do you have plans to configure the install menus etc to support installing on a headless system?

Log
---
```
N/A
```

**Comment by pbatard** [comment]
> Do you have plans to configure the install menus etc to support installing on a headless system?

I don't think you are talking about Rufus here, since Rufus is the application that creates the __third party__ installer media (which we don't modify) and it itself does not come with an installer.

If you are trying to install an OS through the serial console, and you find that the OS (which is a completely separate entity from Rufus) does not properly support serial install, then you need to contact the makers of that OS, which is not us...

It's a bit as if you are asking Microsoft to fix an Adobe PhotoShop issue, because Photoshop happens to run on Windows. If you do that, Microsoft will direct you to contact Adobe, as they aren't the software company that produces PhotoShop. The same is true with Rufus and whatever OS you have created a bootable media from using Rufus.
