### ISSUE TITLE
 Rufus how to inject usb3.0 driver

### ISSUE THREAD

**Issue by 38202538** [pbatard/rufus#1323]
First of all, I think rufus are very easy to use, small, fast, and pure.
But when I recently installed the system on my desktop, there was a problem.
Use rufus to add system boot, after entering the system, the mouse and keyboard can not move, how can rufus add usb3.0 driver to iso file

**Comment by pbatard** [comment]
Besides #322 (which probably won't be implemented for __years__ at best), I have no plans to help Rufus users with custom injection of files. Please remember that the prime goal of Rufus is to create a bootable USB that is as close as possible to the ISO that was used, so if you are missing components, then you should modify the ISO so that it contains them.

Injection of USB 3.0 drivers into Windows ISOs is out of the scope of what I can support here, especially as it's only relevant for Windows 7, which will reach official end of life in about 6 months. But if you look on the internet, you should be able to find the answer you are looking for. As such I will close this issue.
