### ISSUE TITLE
One more 'rufus kill my usb'

### ISSUE THREAD

**Issue by alakasame** [pbatard/rufus#1332]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Hello, like manys my (pretty new) USB is dead after using RUFUS.
When I plug it, my win10 got it for a second, send error message and the device disappear
the same appears on diskpart

Whether it's your fault or not, if u know anyways to restore USB tell us plz...
 to all guys using ur RUFUS then got a dead USB that can be a cool ways to say sorry

BTW thx Ive use RUFUS in the past and all was fine =D

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
> like manys my (pretty new) USB is dead after using RUFUS.

1. Are you sure it is dead (for instance did you test with a different OS) and not the victim of a Windows bug (since Windows does have bug that, for instance, will make it look like a flash drive on which you applied a Chromium image is dead when it's just Windows not being able to access it because it doesn't like its partition layout - #759)?
2. Since you say the drive is pretty new, are you sure this wasn't a "fake" drive (i.e. a drive sold by unscrupulous vendors at a cheap price after its firmware was modified to make it look like it is larger than it really is)? Considering that, unlike the long theorized "Rufus bug" that is supposed to kill USB flash drives, yet that no-one has even remotely been able to provide any evidence for, "fake" drives are very much an easy to prove reality (just try to buy the cheapest USB flash drives you can and, if you repeat that long enough with different sellers, you should end up at least a couple "fake" ones) and usually tend to fail as soon as you start to write more data than the actual capacity (e.g. 2 GB or 4 GB for a drive that might report 32 GB or 64 GB), then unless you did test your drive prior to usage with Rufus, with a bad blocks check that can detect "fake" drives, then the possibility that you have been the victim of a "fake" drive should give you some pause about wanting to point the finger right away at an application. __Especially__, statistically, I will continue to point out that, will circa 3 million downloads of Rufus every month, the number of "Rufus killed my USB flash drive!" reports that are raised is quite low, and pretty much what one would expect from people unknowingly having used a "fake" drive. 
3. I'd really like to hear your justification for going with _"Rufus killed my USB"_ and not _"Windows killed my USB"_, which, unless you have concrete evidence to disprove that Windows could be the culprit should logically be equally valid. Or are you making the assumption that because Microsoft is a large company, they don't make mistake (coz they sure do, see above) or don't happen to keep major bugs in their OS for years (they also do: You can __demonstrate__ this by writing a somewhat recent FreeBSD image onto an USB flash drive and then plugging that drive onto a Windows XP or Windows 7 machine, which will result in an instant BSOD. Or, if you want a more recent BSOD that has to do with QA that doesn't appear to have been enacted where you would definitely expect a large company to always enact QA, you can try creating a Windows To Go drive from a Windows 10 1809 ISO, and see it BSOD at boot until you happen to replace `WppRecorder.sys`  with the 1803 version &mdash; Nice QA there, Microsoft!). Thus, brushing off the idea that Windows could have killed your USB, simply because Microsoft has more resources, is quite a dangerous assumption to make. It means that you are either automatically asserting that a group of independent developers can never be as competent, or that independent software can never reach or surpass, the level of quality as one from a large company, which unless you have evidence to back it up (whereas I have already provided evidence of the contrary), is more akin to __prejudice__ than anything else.

Now, unfortunately, I know that a lot of people will choose to read this as _"The developer is simply making excuses for a problem that must exist, since quite a few people have reported it, and they should acknowledge it instead"_, but the fact remain that, when there exists quite a lot of factors that can result in a dead drive, and, as I explained many times over, due to the ways Windows allows an application like Rufus to access a drive (which is way more limited than people think, especially Rufus doesn't actually build and send USB commands on the USB bus, but instead only ever asks Windows to read/write sector X or read/write file 'Y'), even the buggiest application you can think of will have a lot of trouble actually damaging hardware. Therefore, __anyone__ who runs into an issue tracker with the claim of "Application X killed my drive!" is pretty much the same as someone who points the finger to a person in a court room with only the statement _"I believe X is a killer"_ as their "evidence". If you want to convince a jury, you have to provide a bit more facts than a mere unsubstantiated belief.

> Whether it's your fault or not

I am 100% positive it is not.

This has been explained at length. Unless you're a government backed entity (or similar) and working to destroying a very specific set of hardware (there are all kind of flash drives out there, with different controllers, which, without being able to send low-level USB commands, which an application like Rufus actually can't, as it would have to first replace the Microsoft provided Mass Storage driver and a couple DLLs, you'll have a very hard time to generate a failure for, even if your application is super buggy), software that destroys hardware is actually very difficult to develop, even more so by accident!

> that can be a cool ways to say sorry

There again, you are assuming that Rufus or its developer is responsible for a hardware failure that, as I have already explained many times over, cannot be pinpointed to Rufus usage, and/or extrapolating __coincidental__ failures (which are better probabilistically explained from the usage of "fake" drives as well as the expected low life expectancy of flash based hardware, especially cheap one) to assert that the developer does have something to apologize for. Well I'm afraid that is not the case.

What I would be sorry for instead is that, in this day and age where a lot of information is available at one's finger tips, people are still choosing not to do their research to see is there could not exist alternative explanations to explain a failure, before they rush into trying to point the finger at somebody for it. It's nice an all that the Internet provides the means to have crowds point the finger at someone simply because they "feel" that, somehow, they deserve it or that "someone" has to be responsible (but only as long as it's a single easy to reach person, and not a large faceless corporation), but that still doesn't make the practice any more justifiable than if you were to do it in a town hall meeting...

That's not to say that I can't understand how frustrated one might feel when they lose a drive in the middle of an operation, and how the first reaction is to be suspicious of the application they were using while their drive died. But I wish people could stop being irrational and at least grand the same credit to the developers of that application as they do to the developers of the OS, or try to devote as much time gathering some verifiable evidence to back their claim (I can't help but being struck at how few of these "Rufus killed my USB drive" actually name the brand and model of the drive that was killed. If I too were to make an __inappropriate assumption__ I would say that, most likely, it's because these drives are cheap no-name brands that users don't really want to acknowledge they were using in the first place) as they do trying to vehemently try to seed doubts about the behaviour of said application. In other words, what I would like Rufus users to consider, if they happen to lose a flash-based media while using the application is: How comes the first reaction of people, when they are using a OS application and their media happens to die, is to assume that the OS probably wasn't responsible for that failure, but the minute you use an application that didn't come from an OS maker, then that application has to be the culprit?
