### ISSUE TITLE
suggestion - new button

### ISSUE THREAD

**Issue by JDMV17** [pbatard/rufus#1342]
I do not speak English

Bueno mi sugerencia es de añadir un botón en el que se desplegue una ventana para conocer todas las combinaciones que existen para el programa, por ejemplo:

![Ashampoo_Snap_viernes, 19 de julio de 2019_09h45m32s_003_](https://user-images.githubusercontent.com/53090503/61545070-3a8a9180-aa0c-11e9-8091-d010d2df7627.png)

**Comment by pbatard** [comment]
The FAQ already lists all these combination (see https://github.com/pbatard/rufus/wiki/FAQ#Power_keysCheat_modes), and, because they are cheat mode (i.e. I don't want them to be used by people who might not understand what they are doing), I don't want to make them public in the UI.

&rarr; Rejected.
