### ISSUE TITLE
Adding linux distributive in download menu

### ISSUE THREAD

**Issue by serh39** [pbatard/rufus#1361]
Hey dear developers,can you add linux distributive(debian/arch/gentoo/etc) in download menu
links for the download we can found on any mirrors(mirror.yandex.ru(CIS mirror by yandex)/or any other mirrors)

**Comment by pbatard** [comment]
We're planning to do that, but we've been delaying it because it's going to be a massive __pain in the ass to maintain__, since mirrors do change all the time and few of these mirrors are commons between distros. Plus there needs to be some logic to try to match location with a mirror.

All in all, the minute we start to add Linux ISO download support in [Fido](https://github.com/pbatard/Fido) (which is the place you should have posted your query as, Rufus simply reuses Fido for the download feature), I do expect to have to spend some time, every single week or so, maintaining the download list of mirrors for each distros.

Obviously, this means that some automation for the mirror generation will have to occur, as I simply don't have the time to manually perform such maintenance in the long run.

Also, this means that I am going to __seriously__ limit the distributions that are going to be supported. Right now, it's going to be:
* Debian
* Ubuntu
* Arch (maybe... That will depend on how painful adding the first two is going to be).

That's it.

And I can also guarantee that it's going to take way more time than you think (it's not just a matter of copy/pasting a bunch of URLs &mdash; As I explained, the non user-visible maintenance aspect is a crucial part of it), so it's unlikely to happen as fast as you wish.

Hope that answers your question. In the meantime, since Linux folks make ISOs a lot easier to download than Microsoft does with Windows (which is the reason why we added the download feature in the first place), you shouldn't have much of an issue locating and downloading the distribution of your choice for use with Rufus.
