### ISSUE TITLE
Network is unavailable: Internet has not be initialized.

### ISSUE THREAD

**Issue by colotoon** [pbatard/rufus#1370]
Issue description
-----------------
I cant write iso image to flashdrive!
I`m try to write latest Kali linux iso, but got warn dialog about newer version used in iso 
syslinux 6.04 and it ask me download or not.
If i press YES - its not download anything, coz files not exist at the server.
If i press NO - dialog closes and i got nothing.
So, how i can write my iso???

Log
Downloading https://rufus.ie/files/syslinux-6.04/20190226/ldlinux.sys
Network is unavailable: Internet has not be initialized.
Could not open Internet session: Internet has not be initialized.
Extended version was not found, trying main version...
Downloading https://rufus.ie/files/syslinux-6.04/ldlinux.sys
Network is unavailable: Internet has not be initialized.
Could not open Internet session: Internet has not be initialized.
Could not download the file - cancelling

**Comment by pbatard** [comment]
The file(s) do(es) exist on the server (Click on the https://rufus.ie/files/syslinux-6.04/ldlinux.sys link in your browser &mdash; You will find it downloads just fine as it's being served by GitHub/AWS. The first file is part of the fallback mechanism used by Rufus, so it is usually not available, but this is by design so that we can provide a custom `ldlinux.sys` if one has to be used over generic one, i.e. the second link).

So, no, it is not a server issue.

The problem is 100% on your side. Because of how your machine is configured, Rufus is unable to access the internet (`Network is unavailable: Internet has not be initialized.`), so you need to fix that, as Rufus is designed to work in connected mode, and no longer provide support for people using it in any other fashion (because it's too much of a pain to help individual users sort out their connectivity issues).

The issue could be that you use a security solution that prevents applications that haven't been whitelisted, such as anything that isn't a browser, from connecting to the internet. Or it could be something else. At any rate, you will need to sort out the ability for generic applications to access the internet if you want to use Rufus, as the error comes from Windows networking and is not something I can "fix" in Rufus (I can't add code that will create a separate network connection, if your regular network connection reports that it's not able to process requests). And, no, I'm not going to rely on downloads through a web browser (because then I'd have to detect whether browser X, Y or Z is available and do tons of other stuff), just so that the handful of people who are trying to use Rufus in environments where networking __is__ restricted can use the application.

Again, if you want to use Rufus, please sort your networking. If you can't do that, then you're on your own.

The only thing I will say is, if you want to avoid the download, you can try to follow [this part from the Usage Notes](https://github.com/pbatard/rufus/wiki/Usage-Notes#Where_to_manually_copy_the_SyslinuxGRUB_files_if_Rufus_cant_download_them). But I'm not going to help you any further with that either. Please look into sorting your networking issues.
