### ISSUE TITLE
Add a window about the successful completion of the process.

### ISSUE THREAD

**Issue by rom23rom** [pbatard/rufus#1402]
﻿

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
After the image is written to the USB flash drive or after the end of any other process, need to add the output of the message about the successful completion of the process.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
There's already a full progress bar completion, task bar and a sound, so I very much feel like adding yet another prompt would actually be overkill (and annoying) for the vast majority of people.

Please bear in mind that what you might see as something helpful can be seen as redundant or straight annoying to other people, and that I have to strike a balance between the preferences of all Rufus users, rather than just your own.

&rarr; Rejected.
