### ISSUE TITLE
Diff.between booting from USB v2.0 port or USB v3.0 port?

### ISSUE THREAD

**Issue by bsto** [pbatard/rufus#1413]
﻿I put an ISO file onto an USB flash drive with Rufus 3.8
Partition scheme=MBR
Target system= BIOS (or UEFI-CSM)
Use Rufus MBR with BIOS ID=yes
File System NTFS

I have a computer with motherboard which offers two USB 2.0 and two USB 3.0 ports.
When I plugin this USB flash drive into an USB 3.0 port then I can boot successfully afterwards from the flash drive.
Now I put the same USB flash drive into one of the USB 2.0 ports and boot and press F8 to get the BootMenu selection "as usual".
Yes, the USB flash drive appears. I select it and hit a key when I am prompted to do so.
Then it seems to me that the process from USB flash drive is tried but then automatically switches to the "normal" Windows 7 boot partition and boot this WinOS instead of the USB flash drive.

This can be reproduced.

Moreover the same appears on another computer.

It seems to me that (at least for certain Rufus-based bootable USB flash drives) these USB flash drive can only be booted on USB 3.0 ports.

Can someone confirm this?

Is there a workaround?

Is there a log file which shows why the boot from USB 2.0 port was unsuccessful?

However the USB 2.0 port is not damaged. When I boot my hard disk based "Windows 7" system and plugin some USB flash drives I can copy file from and onto it. So its accessible in general.

Thank you
Ben

**Comment by pbatard** [comment]
This is not a Rufus related issue therefore it should not be posted in this issue tracker (which is not a forum where one can post to get advice).

Rufus does not apply any elements that will make a drive's behaviour change depending on whether it is plugged into a USB 2.0 or USB 3.0 port. So that behaviour is 100% external to Rufus.

Also, you didn't follow the check list and didn't post a log of how you created your drive in Rufus.

As a result, I will close this issue. You may want to post on SuperUser or something, which may be more appropriate for generic questions that are not directly related to Rufus usage.
