### ISSUE TITLE
Can't change properties/options for device when trying to burn ISOHybrid

### ISSUE THREAD

**Issue by VoidLord** [pbatard/rufus#1419]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
3.8 and 3.7 versions won't recognize the latest Manjaro Linux ISO(18.1.3) as ISOHybrid, meanwhile earlier rufus versions do recognize it as ISOHybrid and can successfully burn it onto the USB drive.
Tried with latest Arch Linux ISO(2019/12/01) and latest Ubuntu ISO(19.10), both of which are recognized as ISOHybrid.
![rufus-3 8_nwUmpUIltP](https://user-images.githubusercontent.com/24192578/70815700-a532d400-1dd6-11ea-92bd-0e6a67ee995a.png)
![rufus-3 4_DFGaj9mXRT](https://user-images.githubusercontent.com/24192578/70815763-c398cf80-1dd6-11ea-88fc-ff658b4b9fce.png)
If I still try to burn the ISO onto the USB drive, itll convert the USB drive into a weird state (haven't tried booting into it because it doesn't look good to me):
![image](https://user-images.githubusercontent.com/24192578/70817774-ff359880-1dda-11ea-8b01-a41602c6f5e1.png)
![image](https://user-images.githubusercontent.com/24192578/70817839-1d9b9400-1ddb-11ea-9044-6b23428f446d.png)

Log
---
```
Rufus x86 v3.8.1580
Windows version: Windows 10 64-bit (Build 18363)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'Kingston DataTraveler 3.0 USB Device' (0951:1666)
NOTE: This device is a USB 3.0 device operating at lower speed...
Using autorun.inf label for drive G: 'MJRO1813'
1 device found
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1911, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {F28631E9-9CDB-4973-8659-302EFD9353BC}
Max parts: 128, Start Offset: 17408, Usable = 15720217088 bytes
Partition 1:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Microsoft Basic Data'
  ID: {480F2250-5D4C-4244-8C82-AF526724E7E2}
  Size: 14.6 GB (15719185920 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Detected Grub version: 2.04~manjaro
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'MJRO1813'
  Size: 2.4 GB (Projected)
  Uses: GRUB2
  Uses: EFI
Note: ISO mode will be disabled because this ISOHybrid is not compatible with ISO boot.
Using image: manjaro-kde-18.1.3-191114-linux53.iso (2.5 GB)

Computing checksum for 'D:\Downloads\tDownload\manjaro-kde-18.1.3-191114-linux53.iso'...
  MD5:	 2998488a5f9f3e697f73ed2884e8a610
  SHA1:	 47de196e9b3863cdb6f5bd985a53b49a64acb4a4
  SHA256: 2b76b669bc90f9afba0fcf0b8a8231477988ce4078c18e67c1c3a026d5c51d24

```
Log2
---
```
Rufus x86 v3.4.1430
Windows version: Windows 10 64-bit (Build 18363)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0409
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'Kingston DataTraveler 3.0 USB Device' (0951:1666)
NOTE: This device is an USB 3.0 device operating at lower speed...
Using autorun.inf label for drive G: 'MJRO1813'
1 device found
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1911, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {F28631E9-9CDB-4973-8659-302EFD9353BC}
Max parts: 128, Start Offset: 17408, Usable = 15720217088 bytes
Partition 1:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Microsoft Basic Data'
  ID: {480F2250-5D4C-4244-8C82-AF526724E7E2}
  Size: 14.6 GB (15719185920 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Detected Grub version: 2.04~manjaro
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'MJRO1813'
  Size: 2.4 GB (Projected)
  Uses: GRUB2
  Uses: EFI
Using image: manjaro-kde-18.1.3-191114-linux53.iso (2.5 GB)

Computing checksum for 'D:\Downloads\tDownload\manjaro-kde-18.1.3-191114-linux53.iso'...
  MD5:	 2998488a5f9f3e697f73ed2884e8a610
  SHA1:	 47de196e9b3863cdb6f5bd985a53b49a64acb4a4
  SHA256: 2b76b669bc90f9afba0fcf0b8a8231477988ce4078c18e67c1c3a026d5c51d24

```

**Comment by pbatard** [comment]
Sigh.

They do.

See the part from the log you posted that says:
```
Note: ISO mode will be disabled because this ISOHybrid is not compatible with ISO boot.
```

It means that, whereas older versions allowed you to try to write Manjaro in ISO mode, __which didn't work because, unlike other distros, Manjaro is incompatible with it__, and therefore prompted you to choose, __recent__ version of Rufus consider that it's pointless to let users choose between ISO and DD, since ISO don't work, and therefore simply __hide the prompt__.

That's the __only__ change. And it was applied so that Manjaro users (who are not expected to be familiar with what ISOHybrid, ISO mode or DD mode mean) get less confused.

In other words, the Manjaro ISOHybrid is properly recognized as such (the log pretty much tells you just that). You just don't get prompted about choosing the mode you want to write it in, because there's only one mode that works. But it's not because you aren't prompted how you want to write the image that Rufus has ceased to recognize the image as ISOHybrid. It's just a UI change aimed at making boot selection options less confusing and less prone to mistakes that will result in the creation of a drive that can't boot.

Now, if the USB you created with Rufus 3.8 doesn't boot, then that's a Manjaro issue, as you'll see the same thing with Etcher (since the latest versions of Rufus and Etcher are basically doing the same thing when writing the image).

**Comment by pbatard** [comment]
Oh, and by the way, we pretty much removed the prompt __at the request of the Manjaro distro maintainers__, who were annoyed that too many users were trying to write their media in ISO mode in Rufus when they should only use DD mode.

**Comment by pbatard** [comment]
Finally your:

> haven't tried booting into it because it doesn't look good to me

is really your only issue here. Don't assume that something will not work because you __think__ it looks suspicious to you. Instead, it might be helpful to assume that, possibly, the developers who created the image and the utilities you use to write them to USB know what they are doing, and therefore, if they are creating a media in a specific way, it might be worth __trying it__ before giving up altogether and reporting an issue.

**Comment by VoidLord** [comment]
Alright, thanks for the answer.
I searched deep and wide but looks like not enough. Sorry if i wasted your time.
