### ISSUE TITLE
Rufus MSI not working.

### ISSUE THREAD

**Issue by NetPlayChill** [pbatard/rufus#1443]
good day to all. Rufus is not working of some MSI Mother Boards. out of 8 MSI MOBO i tried, only 1 working and that is the old one MSI MOBO. please fix the issue. thank you and god bless.

**Comment by pbatard** [comment]
Ignored the check list &rarr; Closed.

**Comment by pbatard** [comment]
PS: Most likely, you want to see [this](https://github.com/pbatard/rufus/wiki/FAQ#Help_I_created_a_Windows_installation_drive_but_it_doesnt_boot) which, without any relevant information from you because you __chose__ to completely disregard to provide the data you were explicitly required to provide, I am guessing is your issue.
