### ISSUE TITLE
no internet: need to cancel syslinux etc downloads before I get to DD mode

### ISSUE THREAD

**Issue by deadrom** [pbatard/rufus#1447]
need to write a hybrid image in DD mode to several usb pens. each and every time it attempts to download syslinux and all this because of the hybrid, but I need dd mode anyway so thanks but no: the machine is VPN connected and has no internet access. Have to cancel every time or wait. 
Would be good to have an option here to skip checks and run with what you got. I for one would prefer a mode dropdown but I read that was deliberately axed because reasons.

**Comment by pbatard** [comment]
I'm afraid that Rufus is designed to run in connected mode. The ability to proceed if the files could not be downloaded is provided as a convenience, but that's about it.

Handling sysadmin/power-user scenarios such as the one you describe (repeatedly creating images) is not something I want to focus on, because it requires a lot more time to make a utility sysadmin/power-user friendly, and, all things considered, the return on investment is not high enough, especially for an application that is provided to you for free. In other words, sorry, but my time is too limited to go out of my way to add the feature you want for a scenario that few Rufus users are going to require.

See also [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want).

Besides, if you are really bothered by this, you can always copy the files yourself, as per [this](https://github.com/pbatard/rufus/wiki/Usage-Notes#Where_to_manually_copy_the_SyslinuxGRUB_files_if_Rufus_cant_download_them) after which Rufus will not prompt you.

&rarr; Rejected.
