### ISSUE TITLE
[Suggestion]  ISO Creation from Disk/Medium

### ISSUE THREAD

**Issue by blackcrack** [pbatard/rufus#1455]
Hi,

Rufus is at moment only a Image Downloader and Writer to USB-Stick
why not also add a support to create a ISO from the Disk/Medium 
to make it possible to make a Backup of the whole Medium
and let write a iso or a img of the bootable Iso/Medium.

And i guess this code is not much where it support something.

best regards
Blacky

(if you not want, close it instantly .. )

**Comment by pbatard** [comment]
It's already there. Except you're not going to save to ISO (because creating an ISO back would make very little sense) but to VHD.

See https://github.com/pbatard/rufus/wiki/FAQ#Saving_an_existing_drive_to_VHD

Oh, and the resulting VHD will be usable on Linux if you invoke `dd` (since an uncompressed VHD is just a DD image with a 512 footer added, and the footer can't interfere with the rest of the image, even if written to disk).

Next time, please read the FAQ as requested per the checklist you ignored.
