### ISSUE TITLE
[Suggestion] Remove "(Recommended)" from the ISO image mode selection

### ISSUE THREAD

**Issue by damian101** [pbatard/rufus#1465]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Writing a Linux ISO with Rufus in DD image mode generally works, but writing it in ISO image mode can prevent some Linux ISOs from booting, I've come across a few, all of those are ISOs from Arch distributions or Manjaro.
The (" Recommended") behind the ISO image mode can prevent users from reading the explanation above the two options and can deter users from trying the DD image mode if an USB stick using the ISO mode fails.

**Comment by pbatard** [comment]
Well, there are a few issues with that:

* A __LOT__ of Windows users get confused when writing an image in DD mode (can't access their USB drive any longer or thing its has shrunk because of the ESP), so, when both options work the __recommended__ way to write an ISOHybrid is to use ISO mode, because it is the least confusing option for users
* The ability to create ISOs that can work as both optical (i.e. can be extracted in ISO mode) and as a a `dd` image is a __hack__. It genuinely boils down to taking a format `ISO9660` or `UDF` and make it behave in a manner that it was never designed too, with "DD mode" being forcefully applied on top of "ISO mode". On account of this, there are real problems that can manifest themselves when writing in DD mode. For instance, if the DD image part uses GPT instead of MBR and you're running on Windows 7, you will get a BSOD because Windows 7 has a bug where it just crashes if it reads garbage in the secondary GPT, and, because of size differences, the secondary GPT does not get properly written in DD mode. As such, I prefer to recommend the way of creating a bootable media that will avoid some of these issues.
* When I know that an ISOHybrid doesn't work in ISO mode at all, I remove the option. For instance, I have done just that for Manjaro, which you explicitly mention... So this kinda invalidates your point of presenting Manjaro as a problematic distro whereas, if you test with any recent version of Rufus, you will find that the supposed issue you present does not exist. As to Arch, can you point to a specific ISO download I can test?
* If people don't want to read a couple of lines that explicitly tell them "Try this (recommended option) and if it doesn't work try the other option", I really don't feel like it should be my duty to dumb down the application, because this is a very slippery slope. Not everything can be reduced to closing your eyes, pressing a single button and hoping it'll work, sorry. Being able to boot and install an OS will always require a minimum level of investment, and that is how I designed Rufus. If a user doesn't want to put that minimum level of investment, then I will kindly ask that they use a different application, such as Etcher, that is probably better tailored to their expectation.

&rarr; I'm not planning to do what you request. Closing.
