### ISSUE TITLE
A new Logo for Rufus

### ISSUE THREAD

**Issue by srevinsaju** [pbatard/rufus#1470]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
A new logo for Rufus would make it look more professional. The current logo has only a USB as a picture. It can be more relatable to what it actually does.

Log
---
```
None
```

**Comment by pbatard** [comment]
> It can be more relatable to what it actually does.

That's going to be difficult. As a matter of fact, I think a USB flash drive is the closest easily recognizable illustration we can get when it comes to what Rufus does, because it's going to be very difficult to convey "boot" in terms of iconography. Sure you can always try to invent something, but if nobody's going to recognise that, it's pretty much pointless.

I think presenting a USB flash drive, which stands as the most widely used media for creating bootable drives, and also conveys the idea that Rufus is not restricted to creating bootable media only (you can use it to repartition and reformat a non bootable removable media), is actually a pretty good depiction to have, which is why it was chosen in the first place.

I'm therefore going to reject this as I think, unless someone asking for a logo change __actually__ comes up with an image of what they think it should be changed to (rather than a wish to see it changed) and manages to produce something that's more than a revamp of a USB flash drive and that actually manages to convey, in a universal manner, what Rufus is meant to be used for, there's very little incentive to change a perfectly fine logo.
