### ISSUE TITLE
Cross compile appears to fail in modern mingw environment.

### ISSUE THREAD

**Issue by dyeske** [pbatard/rufus#1478]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Cross compiling fails due to various issues in using mingw toolchain.

This was performed on a modern Linux system with the following details.

```
% x86_64-w64-mingw32-gcc -v
Using built-in specs.
COLLECT_GCC=x86_64-w64-mingw32-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/lto-wrapper
Target: x86_64-w64-mingw32
Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir='/usr/lib/x86_64-linux-gnu' --libexecdir='/usr/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --with-headers=/usr/x86_64-w64-mingw32/include --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++,ada --enable-lto --with-plugin-ld --enable-threads=win32 --program-suffix=-win32 --program-prefix=x86_64-w64-mingw32- --target=x86_64-w64-mingw32 --with-as=/usr/bin/x86_64-w64-mingw32-as --with-ld=/usr/bin/x86_64-w64-mingw32-ld --enable-libatomic --enable-libstdcxx-filesystem-ts=yes
Thread model: win32
gcc version 7.3-win32 20180312 (GCC)

Linux slim 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I run the following steps.

1. - `sh bootstrap.sh`
2. - `configure --host=x86_64-w64-mingw32 CC=/usr/lib/ccache/x86_64-w64-mingw32-gcc CXX=/usr/lib/ccache/x86_64-w64-mingw32-g++`
3. - `make V=1`

The compile fails due to this.

```
/usr/lib/ccache/x86_64-w64-mingw32-gcc -DPACKAGE_NAME=\"rufus\" -DPACKAGE_TARNAME=\"rufus\" -DPACKAGE_VERSION=\"3.9\" -DPACKAGE_STRING=\"rufus\ 3.9\" -DPACKAGE_BUGREPORT=\"https://github.com/pbatard/rufus/issues\" -DPACKAGE_URL=\"https://rufus.ie\" -DPACKAGE=\"rufus\" -DVERSION=\"3.9\" -D_GNU_SOURCE=/\*\*/ -I.    -I./ms-sys/inc -I./syslinux/libfat -I./syslinux/libinstaller -I./syslinux/win -I./libcdio -DWINVER=0x601 -D_WIN32_WINNT=0x601 -D_WIN32_IE=0x800 -D_FILE_OFFSET_BITS=64 -D_OFF_T_ -D_off_t=off64_t -Doff_t=off64_t -Doff32_t=long -DUNICODE -D_UNICODE -UNDEBUG -DCOBJMACROS -std=gnu99 -Wshadow -Wall -Wundef -Wunused -Wstrict-prototypes -Wno-restrict -Werror-implicit-function-declaration -Wno-pointer-sign -DEXT2_FLAT_INCLUDES=0 -g -O0 -c -o rufus-stdfn.o `test -f 'stdfn.c' || echo './'`stdfn.c
stdfn.c: In function ‘GetCpuArch’:
stdfn.c:243:7: error: ‘PROCESSOR_ARCHITECTURE_ARM64’ undeclared (first use in this function); did you mean ‘PROCESSOR_ARCHITECTURE_ARM’?
  case PROCESSOR_ARCHITECTURE_ARM64:
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
       PROCESSOR_ARCHITECTURE_ARM
stdfn.c:243:7: note: each undeclared identifier is reported only once for each function it appears in
Makefile:459: recipe for target 'rufus-stdfn.o' failed
```

This appears to be a difference between the native windows toolchain and mingw package.

A quick fix for this appears to be to add this to `rufus.h`

```
#define PROCESSOR_ARCHITECTURE_ARM64 12
```

Then the compile fails again due to a different message

```
/usr/lib/ccache/x86_64-w64-mingw32-gcc -DPACKAGE_NAME=\"rufus\" -DPACKAGE_TARNAME=\"rufus\" -DPACKAGE_VERSION=\"3.9\" -DPACKAGE_STRING=\"rufus\ 3.9\" -DPACKAGE_BUGREPORT=\"https://github.com/pbatard/rufus/issues\" -DPACKAGE_URL=\"https://rufus.ie\" -DPACKAGE=\"rufus\" -DVERSION=\"3.9\" -D_GNU_SOURCE=/\*\*/ -I.    -I./ms-sys/inc -I./syslinux/libfat -I./syslinux/libinstaller -I./syslinux/win -I./libcdio -DWINVER=0x601 -D_WIN32_WINNT=0x601 -D_WIN32_IE=0x800 -D_FILE_OFFSET_BITS=64 -D_OFF_T_ -D_off_t=off64_t -Doff_t=off64_t -Doff32_t=long -DUNICODE -D_UNICODE -UNDEBUG -DCOBJMACROS -std=gnu99 -Wshadow -Wall -Wundef -Wunused -Wstrict-prototypes -Wno-restrict -Werror-implicit-function-declaration -Wno-pointer-sign -DEXT2_FLAT_INCLUDES=0 -g -O0 -c -o rufus-stdio.o `test -f 'stdio.c' || echo './'`stdio.c
stdio.c: In function ‘CreatePreallocatedFile’:
stdio.c:878:43: error: ‘struct _TEB’ has no member named ‘ProcessEnvironmentBlock’
 #define NtCurrentPeb()     (NtCurrentTeb()->ProcessEnvironmentBlock)
                                           ^
stdio.c:878:43: note: in definition of macro ‘NtCurrentPeb’
 #define NtCurrentPeb()     (NtCurrentTeb()->ProcessEnvironmentBlock)
                                           ^~
stdio.c:1000:16: note: in expansion of macro ‘RtlGetProcessHeap’
  pfRtlFreeHeap(RtlGetProcessHeap(), 0, ntPath.Buffer);
                ^
```

I have looked at the struct definitions in winternl.h between native toolchain and mingw and verified that I can compile with sln using VS studio 2019.

I would be happy to help put in the ifdefs so that mingw will work again.

**Comment by pbatard** [comment]
Well, that has to be a difference that you'll need to isolate between your Linux/MinGW environment and a Windows/MinGW environment, because the latter (fully up to date as well) is what I use to produce the version of Rufus I release.

Especially your statement:

> This appears to be a difference between the native windows toolchain and mingw package.

is wrong, because I am certainly compiling with MinGW almost on a daily basis and do not need to define `PROCESSOR_ARCHITECTURE_ARM64` for builds to work.

Therefore, it's hard to give credence to the idea that this is a "modern MinGW environment" issue, because if that was the case, I would experience it too with Windows/MinGW.

My advice therefore is this: Considering that you are buidling a pure Windows application, you do have access to a Windows environment, therefore you should be able to install an up to date MinGW in its default configuration (through msys2). Once you have that, you should be able to confirm that it compiles as expected, and you may be able to isolate the options you use on Linux that may be causing you trouble (because it it does compile on Windows then it should work on Linux, and if it doesn't then this is a problem that is external to Rufus). For one thing, I'm seeing quite a few `/usr/lib/x86_64-linux-gnu` options in your compilation log that seem like they could cause trouble (MinGW on Linux should not be poking anything from the regular `linux-gnu` libraries).

Oh, and for what is worth, you will see that an up to date MinGW compiled just fine 3 days ago, as per AppVeyor (https://ci.appveyor.com/project/pbatard/rufus/build/job/jqkc35ipvdxwdi3g), without producing any error relating to the use of `PROCESSOR_ARCHITECTURE_ARM64`, therefore, unless there is a pure MinGW bug between Linux/MinGW and Windows/MinGW (which again, would not be for us to fix or work around in Rufus) `PROCESSOR_ARCHITECTURE_ARM64` is properly defined when MinGW is properly set up, therefore, if your compilation fails on Linux in a MinGW environment, then it has to be because you didn't use the right options or because you misconfigured your environment.

Now, as much as I'd like to be able to help everyone that asks for it, I have to set some limits to how far I will go and I'm afraid that, unless you can disprove the points I made above, I have to conclude that this issue is due to your environment or configuration options, and therefore not something I want to invest any more time on. Unless you can replicate the same issue on Windows/MinGW, I'm afraid this is something that you will have to sort out on your own, sorry.

&rarr; Closing.

**Comment by dyeske** [comment]
It appears Ubuntu 18.04.4 has the following mingw which is too old.
ii  mingw-w64-common                     5.0.3-1

I tried again on Debian 10 which has the following.
ii mingw-w64-common                     6.0.0-3

This compile worked fine on Debian 10 wsl.

**Comment by pbatard** [comment]
Happy to hear you found your issue. And yes, when you face errors like this, the first thing you should try is see if it still happens with a more recent version of the toolchain.
