### ISSUE TITLE
Stop throwing sponsorhips into Paste memory when performing Rufus with command line options.

### ISSUE THREAD

**Issue by BoQsc** [pbatard/rufus#1482]
# Rufus command line interface is pasting "Rufus.com" into currently active text field.
I noticed that before launching Rufus with command line options, a string "**rufus.com**" is being pasted into any text area where the mouse is focused.

Please stop this.

**Comment by pbatard** [comment]
As opposed to what you think, this is __not__ "sponsoring" paste (I don't own rufus.com, the only domain I own is https://rufus.ie, so it would make literally no sense for me to "sponsor" that domain).

Instead what you are seeing is the result of the "commandline hogger", which is explained at https://github.com/pbatard/rufus/tree/master/res/hogger

`.com` is an executable extension like `.exe`, and the commandline hogger, which is an executable, happens to be named `rufus.com` (just like the rufus UI executable is more or less named `rufus.exe`).

You get it in the commandline because we have to launch `rufus.com` behind the scenes, so it gets listed in the last commands run. Unfortunately, there is no way to remove that from the history. And I can't remove the hogger as people using some commandline applications will vehemently complain otherwise (the hogger exists for a reason).

Note that this is not being pasted in the clipboard. It just a command in the commanline history.
