### ISSUE TITLE
Invalid letter case created

### ISSUE THREAD

**Issue by MrEagle123** [pbatard/rufus#1497]
Hello!
Rufus 3.9.1624 incorrectly compiles syslinux.cfg. It is not case sensitive for folder names. For example, if in the ISO-image there is a folder "JINN" (in capital letters), then in syslinux.cfg it is written as "jinn" (in small letters). Because of this, the flash drive does not boot. But you should change the register "jinn" to "JINN". So everything works right away. Example:

Rufus creates an BAD configuration:
```
DEFAULT loadconfig

LABEL loadconfig
  CONFIG /jinn/data/syslinux.cfg
  APPEND /jinn/data/
```

But this configuration is WORKING:
```
DEFAULT loadconfig

LABEL loadconfig
  CONFIG /JINN/data/syslinux.cfg
  APPEND /JINN/data/
```

You can check it on the ISO-image:
Windows 10 Enterprise LTSC 8in1 (x86/x64) +/- Office 2019 - by Eagle123 (03.2020)

**Comment by pbatard** [comment]
Sorry but that's a problem with the ISO, not Rufus.

If the people who mastered the ISO use uppercase folders, then they should ensure that their config files reflect that, rather than assume that the media content will be located on a case-insensitive file system.

Especially, unless you can point we to set of __official__ ISOs, rather than some poorly mastered clearly unofficial Windows ISO, that exhibit a similar issue, I am certainly not going to add extra code to parse and alter Syslinux or GRUB config files, because this is complex to do properly and runs a high risk of introducing breakage or regressions.

Please stop using pirate Windows ISOs. They will __NEVER__ be supported in Rufus.
