### ISSUE TITLE
UWP version doesn't work selecting "run as administrator"

### ISSUE THREAD

**Issue by ThePirate42** [pbatard/rufus#1504]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I have installed the appx version of Rufus, but when I try to run it (selecting "run as administrator") the UAC appers, I insert the administrator account password and then an error message appears (I've put the text of the message below). If I try to run the app when directly logged in an administrator account everything works. Is this normal? If yes, is there a way to grant administrator rights to Rufus properly?

Log
---
```
C:\Program Files\WindowsApps\Rufus_3.9.1624.0_x64__maxm3x3sw7c4t\rufus.exe

To perform the requested operation, execution with elevated privileges is required.
```

**Comment by pbatard** [comment]
>  Is this normal?

Yes. It's a Microsoft limitation with .appx installed apps, because they really don't want them to run elevated (and also the reason I can't submit Rufus to the App Store because it requires elevation). Microsoft wants all the new Apps to run isolated in their little corner and not access anything of the system, which of course is never going to play well with an application like Rufus.

I would invite you to let to Microsoft know that this is impairing you and that you want the situation to change, because that's the only way there may be any kind of resolution with regards to apps requiring elevated mode.
