### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by RaeesBhatti** [pbatard/rufus#1511]
As fellow software engineer, I just want to let you know that you’re doing an amazing job and the world is better because of your work.
Thank your for building this great piece of software, thank your for making it open source and thank you continuing to work on it!
PS: You’re awesome!

**Comment by pbatard** [comment]
Don't know about the "being awesome" part, especially as (alas this is the case for anyone who ever publishes an application for free) I get many messages from disgruntled users telling me quite the opposite, but I've very happy to hear that you found Rufus useful enough to post this message.

Of course I can't take all the credit, since a lot of the Rufus code comes from other developers, and I am also receiving a lot of additional help, such as the one from translators or from people pointing out issues and helping fix them.

All I can say then is: Thanks for the kind words. I'll do my best so that you continue to find Rufus useful in the future!
