### ISSUE TITLE
with v3.9,there is a 0MB FAT partition

### ISSUE THREAD

**Issue by yws112358** [pbatard/rufus#1513]
and partition lable:UEFI_NTFS
when I make a windows 10 USB driver(standard install:not windows to go) with V3.9
long time before that,i used make it with v 3.8,and there is a  several hundreds MB partition.

partition scheme:MBR 
 target system:BIOS or UEFI
Add fixes for old BIOSes(selected)
Use refus MBR with BIOS ID (selected) and Default 0x80

**Comment by pbatard** [comment]
1. Please follow the check list
2. It's not 0 MB, it's 512 KB, but Microsoft Disk Manager lists all partitions under 1 MB as 0 MB. You will see that it is 512 KB if you use a different partition editor.
3. This is __not__ new from 3.9 (it's been part of Rufus for a long time) and this partition is needed so that you can boot Windows installers that contain an `install.wim` that is larger than 4 GB in UEFI mode, because FAT32 can't be used and because most UEFI systems can't boot NTFS natively, so you need a small FAT partition (The `UEFI_NTFS` one) to load an NTFS driver and then hand over to the Windows boot loader on the NTFS partition.
4. It's all explained [here](https://github.com/pbatard/uefi-ntfs), with additional information in the FAQ, such as [here](https://github.com/pbatard/rufus/wiki/FAQ#Blah_UEFI_Blah_FAT32_therefore_Rufus_should_Blah) and [here](https://github.com/pbatard/rufus/wiki/FAQ#Why_do_I_need_to_disable_Secure_Boot_to_use_UEFINTFS) and you should actually have seen a prompt talking about UEFI:NTFS and asking you to disable Secure Boot after your drive was created.
5. You have not seen this behaviour before because you haven't been using a Windows ISO with a >4GB `install.wim`. Only recent versions of the retail Windows 10 ISOs have one.
