### ISSUE TITLE
Port to macOS and Linux

### ISSUE THREAD

**Issue by mcandre** [pbatard/rufus#1515]
It would be more helpful if Rufus were available to run from non-Windows hosts, such as macOS and Linux. Windows hosts can already use the official Microsoft media creation software to format Windows rescue drives.

**Comment by pbatard** [comment]
It would be more helpful if people followed the MANDATORY check list instead of thinking that it does not apply to them, especially the part that specifically tells them to check the FAQ to find out [if their question has already been answered](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS).
