### ISSUE TITLE
Code improvements results from Cppcheck

### ISSUE THREAD

**Issue by jensdenbraber** [pbatard/rufus#1520]
I ran [cppcheck](https://github.com/danmar/cppcheck) on the Rufus codebase which resulted in the some code improvements. 

Download the results here: 
[rufus_cppcheck.zip](https://github.com/pbatard/rufus/files/4517850/rufus_cppcheck.zip)

**Comment by pbatard** [comment]
Thanks but a couple of things:
* The `style` warnings are way too numerous and useless. All of the ones I've seen so far were intended.
* Be mindful that a lot of the code (ext2fs, libcdio, most of bled), is not something I wrote but something I reused and, in order to be able to update that code, I tend to keep it as close to the original as possible, which means I have no plans to "fix" issues that are reported there.

All in all then, your report contains way too much stuff, which makes fixing the potentially relevant issues a pain in the ass, because I have to sieve through a lot of distracting entries. Also why XML? XML is not designed to be read by humans. Is there nothing better cppcheck can produce?

That doesn't mean that I'm not grateful for the report, but as it stands, it's not as helpful as it could be, which makes me less inclined to want to do anything about it. So if there's any chance you could try to reframe the analysis to something more useful (no style issues, and limited to the top-level code), I would appreciate it.
