### ISSUE TITLE
Constantly ISO image parsing error on v3.10

### ISSUE THREAD

**Issue by LastPust** [pbatard/rufus#1532]
This issue started after update. all of my iso's and usb sticks are useless with v3.10... v3.9 works fine. just wanted to report this problem.

**Comment by pbatard** [comment]
The check list is not optional. Unless you do provide a log as requested, I simply cannot investigate your issue (because, despite what you may think, this is not something I have seen on my end, and none of the ~425,000 people who downloaded Rufus 3.10 so far have reported this issue) and I will have no choice but to close it.
