### ISSUE TITLE
Might a bug.

### ISSUE THREAD

**Issue by EricLucife** [pbatard/rufus#1542]
I use rufus 3.7 and 3.10 to write 'manjaro-xfce-20.0.1-200511-linux56.iso' into my USB drive;, and it looks like that and can not burn into my udisk:
![image](https://user-images.githubusercontent.com/35440115/82324260-f0978100-9a0b-11ea-858c-88784372457f.png)
But 3.1 works well.
![Uploading image.png…]()

**Comment by pbatard** [comment]
The 'START' button is still clickable so I see no issue.

If you are worried about the controls that are greyed in 3.10 but not in 3.1, it's just because ISO mode was disabled for Manjaro images, since it doesn't work, and therefore all the controls that apply to writing in ISO mode will be disabled by default.

But that doesn't mean that you can't write the image.

Please try to actually write the image and only report an issue if it doesn't boot then.
