### ISSUE TITLE
Installer is partially operational when size persistence is equivalent to full

### ISSUE THREAD

**Issue by Ricky-Tigg** [pbatard/rufus#1549]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] Using a different USB drive.
- [x] Plugging the USB into a different port.
- [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the SHA-256 checksum, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Last official ISO image for Bliss-OS (x86_64) was written successfullly for each two cases tested. In each case the _size persistence_ was the only  parameter whose value changed, either **null** or equivalent to **full**. 

Each case was conducted on BIOS and EFI systems.
- Case 1 (here as comparison mean) - persistence: **null**
Installer is fully operational.
- Case 2 - persistence: **full**
Installer is partially operational. While installation has reached the partition section, no key respond to invocations, thus installation cannot be operated further.

Log
---
```
Rufus x86 v3.10.1647 (Portable)
Windows version: Windows 10 64-bit (Build 18363.836)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x040B (fi-FI)
Detected installed Windows Language Pack for 0x0809 (English (English))
Localization set to 'en-US'
Found USB 2.0 device 'Kingston DataTraveler 102 USB Device' (0951:162D)
1 device found
Disk type: Removable, Disk size: 3.9GB, Sector size: 512 bytes
Cylinders: 471, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x00301592
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 1.4 GB (1476679680 bytes)
  Start Sector: 2048, Boot: Yes
Partition 2:
  Type: GNU/Linux (0x83)
  Size: 2.2 GB (2397040128 bytes)
  Start Sector: 2886188, Boot: No
Will reuse 'ldlinux.sys' and 'ldlinux.bss' from './rufus_files/rufus_files/syslinux-6.03/2014-10-06/' for Syslinux installation

Format operation started
Requesting disk access...
Will use 'D:' as volume mountpoint
Deleting partitions...
Deleting ALL partition(s) from disk '\\?\PhysicalDrive2':
● Partition 1 (offset: 1048576, size: 1.4 GB)
● Partition 2 (offset: 1477728256, size: 2.2 GB)
Opened \\.\PhysicalDrive2 for shared write access
No logical drive found (unpartitioned?)
Drive does not appear to be partitioned
Analyzing existing boot records...
Drive has a Syslinux Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Bad Blocks: Checking from block 0 to 29561 (1 block = 128 KB)
Bad Blocks: Using offset 76237 for fake device check
Bad Blocks: Writing test pattern 0x00
Closed Windows format prompt
Bad Blocks: Reading and comparing
Bad Blocks: Check completed, 0 bad blocks found. (0/0/0 errors)
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Partitioning (MBR)...
● Creating Main Data Partition (offset: 1048576, size: 1.4 GB)
● Creating Linux Persistence Partition (offset: 1477728256, size: 2.2 GB)
Waiting for logical drive to reappear...
Using Debian-like method to enable persistence
Formatting (ext3)...
146303 possible inodes out of 585214 blocks (block size = 4096)
29260 blocks (5.0%) reserved for the super user
Creating 18 inode sets: [1 marker = 1.0 set(s)]
++++++++++++++++++
Creating 8192 journal blocks: [1 marker = 102.4 block(s)]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Created 'persistence.conf' file
Done
Formatting (FAT32)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing Master Boot Record...
Partition is already FAT32 LBA...
Set bootable USB partition as 0x80
Using Syslinux MBR
Found volume \\?\Volume{bda94566-a013-11ea-a794-d02c96aaf33f}\
Installing Syslinux 6.03...
Opened \\?\Volume{bda94566-a013-11ea-a794-d02c96aaf33f} for shared write access
Using existing './rufus_files/syslinux-6.03/2014-10-06/ldlinux.sys' ✓
Using existing './rufus_files/syslinux-6.03/2014-10-06/ldlinux.bss' ✓
Successfully wrote 'ldlinux.sys'
Successfully wrote Syslinux boot record
Successfully remounted \\?\Volume{bda94566-a013-11ea-a794-d02c96aaf33f}\ as D:
Extracting files...
Image is an ISO9660 image
This image will be extracted using Joliet extensions (if present)
Extracting: D:\.disk\info (12 bytes)
Extracting: D:\Androidx86-Installv26.0003.exe (4.3 MB)
Extracting: D:\boot\grub\efi.img (4 MB)
Extracting: D:\boot\grub\fonts\DejaVuSansMono-18.pf2 (108 KB)
Extracting: D:\boot\grub\grub.cfg (132 bytes)
Extracting: D:\boot\grub\theme\android-x86.png (31.7 KB)
Extracting: D:\boot\grub\theme\icons\android-x86.png (1.9 KB)
Extracting: D:\boot\grub\theme\icons\android.png (1.8 KB)
Extracting: D:\boot\grub\theme\icons\arch.png (1.4 KB)
Extracting: D:\boot\grub\theme\icons\centos.png (2.4 KB)
Extracting: D:\boot\grub\theme\icons\debian.png (2.6 KB)
Extracting: D:\boot\grub\theme\icons\fedora.png (1.8 KB)
Extracting: D:\boot\grub\theme\icons\forward.png (2.2 KB)
Extracting: D:\boot\grub\theme\icons\frugalware.png (1.6 KB)
Extracting: D:\boot\grub\theme\icons\gentoo.png (3.2 KB)
Extracting: D:\boot\grub\theme\icons\gnu-linux.png (2.3 KB)
Extracting: D:\boot\grub\theme\icons\kubuntu.png (3.8 KB)
Extracting: D:\boot\grub\theme\icons\linuxmint.png (2.5 KB)
Extracting: D:\boot\grub\theme\icons\mageia.png (1.7 KB)
Extracting: D:\boot\grub\theme\icons\mandriva.png (2.0 KB)
Extracting: D:\boot\grub\theme\icons\opensuse.png (2.8 KB)
Extracting: D:\boot\grub\theme\icons\openthos.png (1.3 KB)
Extracting: D:\boot\grub\theme\icons\os.png (1.5 KB)
Extracting: D:\boot\grub\theme\icons\reboot.png (2 KB)
Extracting: D:\boot\grub\theme\icons\sabayon.png (4.9 KB)
Extracting: D:\boot\grub\theme\icons\setup.png (2 KB)
Extracting: D:\boot\grub\theme\icons\shutdown.png (1.7 KB)
Extracting: D:\boot\grub\theme\icons\slackware.png (1.8 KB)
Extracting: D:\boot\grub\theme\icons\theme.png (1.7 KB)
Extracting: D:\boot\grub\theme\icons\ubuntu.png (3.6 KB)
Extracting: D:\boot\grub\theme\icons\windows.png (2.4 KB)
Extracting: D:\boot\grub\theme\menu_bkg_c.png (6.9 KB)
Extracting: D:\boot\grub\theme\menu_bkg_e.png (509 bytes)
Extracting: D:\boot\grub\theme\menu_bkg_n.png (7.3 KB)
Extracting: D:\boot\grub\theme\menu_bkg_ne.png (295 bytes)
Extracting: D:\boot\grub\theme\menu_bkg_nw.png (289 bytes)
Extracting: D:\boot\grub\theme\menu_bkg_s.png (194 bytes)
Extracting: D:\boot\grub\theme\menu_bkg_se.png (210 bytes)
Extracting: D:\boot\grub\theme\menu_bkg_sw.png (209 bytes)
Extracting: D:\boot\grub\theme\menu_bkg_w.png (442 bytes)
Extracting: D:\boot\grub\theme\progress_bar_c.png (295 bytes)
Extracting: D:\boot\grub\theme\progress_bar_e.png (193 bytes)
Extracting: D:\boot\grub\theme\progress_bar_n.png (276 bytes)
Extracting: D:\boot\grub\theme\progress_bar_ne.png (176 bytes)
Extracting: D:\boot\grub\theme\progress_bar_nw.png (178 bytes)
Extracting: D:\boot\grub\theme\progress_bar_s.png (263 bytes)
Extracting: D:\boot\grub\theme\progress_bar_se.png (176 bytes)
Extracting: D:\boot\grub\theme\progress_bar_sw.png (178 bytes)
Extracting: D:\boot\grub\theme\progress_bar_w.png (194 bytes)
Extracting: D:\boot\grub\theme\progress_highlight_c.png (9.3 KB)
Extracting: D:\boot\grub\theme\progress_highlight_e.png (239 bytes)
Extracting: D:\boot\grub\theme\progress_highlight_w.png (242 bytes)
Extracting: D:\boot\grub\theme\sb_frame_c.png (395 bytes)
Extracting: D:\boot\grub\theme\sb_frame_n.png (568 bytes)
Extracting: D:\boot\grub\theme\sb_frame_s.png (632 bytes)
Extracting: D:\boot\grub\theme\sb_thumb_c.png (423 bytes)
Extracting: D:\boot\grub\theme\sb_thumb_n.png (295 bytes)
Extracting: D:\boot\grub\theme\sb_thumb_s.png (288 bytes)
Extracting: D:\boot\grub\theme\select_bkg_c.png (751 bytes)
Extracting: D:\boot\grub\theme\select_bkg_e.png (231 bytes)
Extracting: D:\boot\grub\theme\select_bkg_n.png (216 bytes)
Extracting: D:\boot\grub\theme\select_bkg_ne.png (155 bytes)
Extracting: D:\boot\grub\theme\select_bkg_nw.png (155 bytes)
Extracting: D:\boot\grub\theme\select_bkg_s.png (173 bytes)
Extracting: D:\boot\grub\theme\select_bkg_se.png (155 bytes)
Extracting: D:\boot\grub\theme\select_bkg_sw.png (155 bytes)
Extracting: D:\boot\grub\theme\select_bkg_w.png (232 bytes)
Extracting: D:\boot\grub\theme\theme.txt (1.8 KB)
Extracting: D:\efi\boot\BOOTx64.EFI (1.1 MB)
Extracting: D:\efi\boot\android.cfg (3.2 KB)
Extracting: D:\efi\boot\bootia32.efi (652.5 KB)
Extracting: D:\efi\boot\grubx64.efi (1.1 MB)
Extracting: D:\initrd.img (1.3 MB)
Extracting: D:\install.img (3.4 MB)
Extracting: D:\isolinux\android-x86.png (31.7 KB)
Extracting: D:\isolinux\boot.cat (2 KB)
Extracting: D:\isolinux\chain.c32 (24.0 KB)
Extracting: D:\isolinux\isolinux.bin (44 KB)
Extracting: D:\isolinux\isolinux.cfg (2.4 KB)
Extracting: D:\isolinux\ldlinux.c32 (119.4 KB)
Extracting: D:\isolinux\libcom32.c32 (182.1 KB)
Extracting: D:\isolinux\libutil.c32 (23.6 KB)
Extracting: D:\isolinux\vesamenu.c32 (26.5 KB)
Extracting: D:\kernel (6.5 MB)
Extracting: D:\ramdisk.img (1.9 MB)
Extracting: D:\system.sfs (1.4 GB)
Write error [0x000003EE] Tiedoston levyä on muutettu ulkoisesti, niin että avattu tiedosto ei ole enää kelvollinen.
Retrying in 5 seconds...
Write error [0x000003EE] Tiedoston levyä on muutettu ulkoisesti, niin että avattu tiedosto ei ole enää kelvollinen.
Retrying in 5 seconds...
Write error [0x000003EE] Tiedoston levyä on muutettu ulkoisesti, niin että avattu tiedosto ei ole enää kelvollinen.
Retrying in 5 seconds...
Write error [0x000003EE] Tiedoston levyä on muutettu ulkoisesti, niin että avattu tiedosto ei ole enää kelvollinen.
  Error writing file: [0x000003EE] Tiedoston levyä on muutettu ulkoisesti, niin että avattu tiedosto ei ole enää kelvollinen.
Created: D:\syslinux.cfg → /isolinux/isolinux.cfg
Finalizing, please wait...
Created: D:autorun.inf
Created: D:autorun.ico

Found USB 2.0 device 'Kingston DataTraveler 102 USB Device' (0951:162D)
Using autorun.inf label for drive D: 'Bliss-OS 11.11 (x86_64)'
1 device found
Disk type: Removable, Disk size: 3.9GB, Sector size: 512 bytes
Cylinders: 471, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x011775DE
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 1.4 GB (1476679680 bytes)
  Start Sector: 2048, Boot: Yes
Partition 2:
  Type: GNU/Linux (0x83)
  Size: 2.2 GB (2397040128 bytes)
  Start Sector: 2886188, Boot: No
```

**Comment by pbatard** [comment]
1. You removed data from the log. All the data about the ISO you opened is missing, so I don't know what was the actual ISO you used. Which means I'm not going to bother trying to replicate your issue. Do __NOT__ remove data from the log.
2. `Write error [0x000003EE] Tiedoston levyä on muutettu ulkoisesti, niin että avattu tiedosto ei ole enää kelvollinen.` indicates that something __EXTERNAL__ to Rufus is modifying files after they are being written. You will need to find what that is, because that's the most likely cause of your problem.

**Comment by Ricky-Tigg** [comment]
What a provocative asssumption. You had to decrete all at once in order to choose that an external factor has to be a physical person and thus me.  That kind of personn then you are. There are ways to speak and i won't guess how many ennemies you have already made with that deliberate provocative language. Nevertheless i reformatted the disk, that time without the irrelevant checking of bad sectors; Logs -[rufus.log](https://github.com/pbatard/rufus/files/4696671/rufus.log)- are not identical to the previous ones. You do understand what it means. A program whose logs may vary randomly unexpectedly will make soon or later vanished users' trust in its presumed reliability.

**Comment by pbatard** [comment]
> What a provocative assumption.

I am not assuming. I am just reporting what I'm seeing.
Your log was both missing data that was removed for one reason or another, and displaying data that indicates an underlying problem.

It is you who are assuming that the problems being reported by the original log come from Rufus and are a statement of the program being unreliable, where it is just a report of external issues being observed.

So you are free to accept facts, or reject them, but that that doesn't make them any less valid. When Rufus repeatedly gets an error from Windows that states `[0x000003EE] The volume for a file has been externally altered so that the opened file is no longer valid` when trying to write a file, it's pretty safe to conclude that there is something on your system or your hardware that is causing the issue and that the problem doesn't originate from Rufus, especially when the couple of other instances where I have ever seen `[0x000003EE]` being reported had to do with something completely external to Rufus (such as a failing flash drive).

If you are unwilling to accept that logs reporting a certain kind of error are unlikely to indicate a software bug with the application but rather an external problem that it is up to you to properly investigate, and since you also seem to be unhappy about the level of support you are getting, then by all means please use a different application.

**Comment by Ricky-Tigg** [comment]
I though your speak was just for me. A confirmation that you apply the same method with all is just there at your Git project report channel you then use to mess with users bringing you legitime reports. So its not just with me. Good to know. You must take pleasure from all that. Anyway, since the _case 2_ had evolved  as last log showed, it resulted in new observation while booting through BIOS:
```
Syslinux 6.03 EDD 2014-10-06 (...)
No DEFAULT or UI configuration directive found!
boot:
```

**Comment by pbatard** [comment]
> bringing you legitime reports. 

You mean reports where __essential__ data has been forcibly removed, like the exact name of the ISO being used, or where major errors are being dismissed as something non important?

The check list is very explicit about what I require to provide support to users. If a user decides that some of the elements I asked them to do (such as not removing any data from the log or checking elements that they see as an annoyance without effectively performing the requested action) are not important enough to be followed, then, because they have demonstrated right off the bat that they are unable or unwilling to follow guidelines, I will 

Let me let you in on a little secret here: The propensity for a user to follow the check list is my "brown M&M's" test". If a user can't follow it, it tells me that they are not actually serious about getting help and are more likely to become an annoyance than anything else. Therefore, I will immediately treat them as such, because I genuinely don't have time to try to second guess data that should have been provided or acted upon, and that the user chose to withhold or ignore.

From the replies I am seeing, it looks like trying to get involved with you as little as possible is indeed the right choice, as you appear to be unwilling to take any direction and your second log shows even more write errors, pointing to what is likely to be a defective flash drive rather than anything else. So I will continue to do that. And since you are happily ignoring the many, many issues where I have been helping folks who __do__ properly follow the check list or the advice I give them, and instead try to imply that I _mess with all users bringing reports_, then, because I genuinely don't have time for this, you have also earned yourself a ban.
