### ISSUE TITLE
Cannot create Windows 7 bootable USB - "Image extraction failure"

### ISSUE THREAD

**Issue by droacuarm** [pbatard/rufus#155]
Can someone please help me? I am having trouble creating a bootable iso image of Windows 7 in the 64-bit version of Windows XP SP 2.. Every time I try, I keep getting a "image extraction failure" error.

I tried searching for this error, here, but all I found was a similar topic where an antivirus program seemed to be the culprit with autorun.inf, (see https://github.com/pbatard/rufus/issues/83) but that doesn't seem to be my problem as I tried disabling all programs not related to the necessary operation of the OS, which didn't work.  Any suggestions?

**Comment by martijnCArol** [comment]
I still have problems with the windows 10 iso extraction here the log file 

Extracting: F:\boot\bootsect.exe (93.5 KB)
Extracting: F:\boot\en-us\bootsect.exe.mui (15.5 KB)
  Error reading UDF file /boot/en-us/bootsect.exe.mui

Could not get node connection information for 'USB\VID_ABCD&PID_1234\5&2b206c2b&0&6': [0x00000057] De parameter is onjuist.
Found USB device 'General UDisk USB Device' (ABCD:1234)
Found USB 2.0 device 'Multi Flash Reader USB Device' (058F:6366)
Device eliminated because it appears to contain no media
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 979, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x000EBA88
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 7.5 GB (8052015104 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Checking for Rufus updates...
Checking release channel...
No new release version found.

**Comment by pbatard** [comment]
__Every single report__ I have ever received about:
```
Error reading UDF file /boot/en-us/bootsect.exe.mui
```
turned out to be a corrupted ISO.

Please compare the SHA1Sum of your ISO with the one from Microsoft.

And, since you truncated the log, which prevents me from seeing the actual name of the ISO you used, you will have to figure out where to find the SHA1 by yourself...

Finally, hijacking an existing issue is very much frown upon... This issue is about a __completely different problem__ involving Windows 7, that as fixed. Yours is with Windows 10.

**Comment by Tmp341** [comment]
I don't know if it's related or will solve your problem but try this:
Windows has problem with FAT32 formatted flash drives.Try NTFS formatting.

**Comment by estumn** [comment]
I recently had a similar incident as a perpetrator software found the Power ISO installation it`s only just now blocked Power ISO x64 as the malware software by built-in
smart screen filter Windows 10, I avoid this error by using alternative programs from Rufus website named Rufus portable instead of standart recommend try 
http://rufus.akeo.ie/downloads/rufus-2.15p.exe if not work then download this file manually called Rufus Portable.

**Comment by phonemyintnaing** [comment]
#make sure anti-virus not blocking autorun file extraction
