### ISSUE TITLE
http://rufus.ie doesn't redirect to https://rufus.ie

### ISSUE THREAD

**Issue by fanfan54** [pbatard/rufus#1551]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Issue description
-----------------
Hello,

This issue is not about the Rufus program, but it's about HTTPS on the rufus.ie website.

I just found that, when I type `http://rufus.ie` (or just `rufus.ie`, like many users will do), I'm not redirected to the HTTPS version of your website, I stay on `http://rufus.ie`, which is a (minor, I agree) security problem.

I guess you just forgot a 301 redirect on `http://rufus.ie`, as you didn't forget to put a 301 redirect for users who type `http://rufus.akeo.io`, those users will be redirected to `https://rufus.akeo.ie`, and then finally to `https://rufus.ie`. Many other websites redirect users to the HTTPS version, you didn't forget to do that for `rufus.akeo.ie`, but I guess you forgot on `rufus.ie`

Sorry if this was not the right place to tell you about that
Thank you in advance

**Comment by pbatard** [comment]
No, the lack of HTTPS redirect is actually intentional because some users of older versions of Windows 7 as well as XP users may be lacking the SSL protocols to connect in SSL mode to GitHub especially if using IE  (and I have no control over the default protocols that GitHub allows).

So I left the main URL open to HTTP access. On the other hand, since I was retiring the `rufus.akeo.ie` URLs, I did set an SSL redirect there, because I don't expect many Windows XP/7 users to use that URL to access the site.

Considering that I am providing a utility that can help XP/7 __upgrade__ to a more modern version of Windows, and even as these OS have stopped being supported, I don't want to place them in a position where they can't even download a utility that allows them to upgrade... which means I want to leave HTTP access available.

Hope that answered your question. Sadly it's not just a matter of me having forgotten to apply the redirect.

Oh, and just for reference, the proper channel to report issues with the Rufus web site is to do so in [the dedicated repo](https://github.com/pbatard/rufus-web).
