### ISSUE TITLE
Flagged as malware

### ISSUE THREAD

**Issue by NVader2000** [pbatard/rufus#1553]
﻿

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Rufus is being flagged as malware by Carbon Black. Whitelisting is not an option. Other formatting tools (e.g. Yumi, Universal USB Installer) are not flagged. Please advise.

"The application rufus-3.10p.exe attempted to access the raw disk on the device. This is potentially due to Ransomware."

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Please report that issue to Carbon Black.

Other applications work one way, Rufus works a different way, and as you should expect, Rufus does have a __legitimate__ requirement to "access the raw disk on the device" (since, unlike Yumi and UUI, we may write raw images).

This is 100% a Carbon Black issue, and if your expectation is that I am going to go out of my way to try not to trigger a security solution that prevents __legitimate__ raw disk access, then you are misdiagnosing the problem.

Also see [this](https://github.com/pbatard/rufus/wiki/FAQ#Antivirus_X_reports_that_Rufus_contains_malware).

I will close this issue now.
