### ISSUE TITLE
Rufus freeze on "Scanning image" with iso opnsense

### ISSUE THREAD

**Issue by thelittlefireman** [pbatard/rufus#1575]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
When i try to load the opnsense iso "OPNsense-20.1-OpenSSL-dvd-amd64.iso" which can be found here [https://opnsense.org/download/](https://opnsense.org/download/) amd64/dvd, rufus is blocked on "Scanning image" and i can't flash it.

Log
---
```
Rufus x86 v3.11.1678
Windows version: Windows 10 64-bit (Build 18363.900)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x040C (fr-FR)
Will use default UI locale 0x040C
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'fr-FR'
Found USB 3.0 device 'Kingston DataTraveler 3.0 USB Device' (0951:1666)
Found VHD device 'Disque virtuel Microsoft'
Device eliminated because it is a Windows Sandbox VHD
1 device found
No volume information for drive 0x83
Disk type: Removable, Disk size: 32 Go, Sector size: 512 bytes
Cylinders: 3774, Tracks per cylinder: 255, Sectors per track: 63
Partition type: SFD (Super Floppy Disk) or unpartitioned
Scanning image...
ISO analysis:
  Image is an ISO9660 image
```

**Comment by pbatard** [comment]
Just tested. Rufus doesn't freeze. It's just that the OpnSense maintainers decided to shove thousands of files onto an ISO (as opposed to what other live distros do, which is to create a single squashfs archive with all the content that then gets mounted), so, of course, scanning the ISO takes forever.

If you do wait, you will see Rufus complete its scan... and tell you that the ISO can't be converted to bootable USB, since it uses a custom boot method that is neither GRUB nor Syslinux nor EFI (and yes, I know they say EFI boot is supported, but they certainly did not add any `/efi/boot/bootx64.efi` boot loader on the ISO, so whatever method they settled on for UEFI boot is __not__ something that's compatible with standard disk boot, which we need to create a bootable USB).

I think there's probably a __reason__ why https://opnsense.org/download/ also proposes, besides the ISO installer, which appears to be squarely aimed at creating a bootable DVD optical media, the following option:
> vga: USB installer image with live system capabilities running in VGA mode as GPT boot. On amd64, UEFI boot is supported as well. 

If a distro proposes both an ISO and a USB image, it usually means that the ISO image they provide can't be used for anything but optical media, and that, if you want to create a USB bootable media, you should __not__ use that image but the USB one...

Now, that's not to say I may not try to see if I can improve the way Rufus scans ISOs so that it might be faster for ones with loads of files and subdirectories. But, considering that there is no actual freezout, and that the image you are attempting to use is should clearly not be used for USB boot (because, even if it had the boot loaders, the conversion from Ridge Rock to FAT32 would probably leave the file system unusable anyway, since symbolic links and important file attributes would not be preserved), I am considering that there is no actual underlying problem to fix here and close this issue.
