### ISSUE TITLE
Fat32 in CSM mode

### ISSUE THREAD

**Issue by kuznet1** [pbatard/rufus#1615]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Why don't we allow using fat32 in CSM mode? I see no reason for that. Moreover, using fat32 we can make universal bios/efi media, which can boot by any approach.

**Comment by pbatard** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#Why_doesnt_Rufus_create_a_Windows_installation_USB_that_can_be_booted_in_dual_BIOSUEFI_mode

Also see the <kbd>Alt</kbd>-<kbd>E</kbd> cheat mode.

Finally, NTFS does universally work in BIOS mode (please point to a report of a media that can boot in BIOS mode from FAT32 but not NTFS... I'll be waiting) and also FAT32 cannot accommodate recent retail Windows ISOs because they contain an `install.wim` file that is larger than 4 GB (which FAT32 cannot support).

**Comment by kuznet1** [comment]
Sorry, I searched "fat32" in faq and didn't found that question
