### ISSUE TITLE
Mention in wiki that some UEFI do allow you to add custom key or signature

### ISSUE THREAD

**Issue by unixandria-xda** [pbatard/rufus#1619]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
The Wiki suggestd that the absolute only way to use UEFI:NTFS is to disable secure boot entirely.

However this is not true, as some OEMs allow you to trust certain keys or signatures.

For instance on my ASUS Zenbook 14:

1. Boot to UEFI firmware setup
2. Hit F7 to get to advanced mode
3. Click on security
4. Scroll to secure boot, click on it
5. Click key management
6. Click authorized signatures
7. Click append, then cancel
8. Select Rufus's .efi loader (both efi/boot/your_arch.efi and efi/rufus_ntfs_yourarch.efi)
9. Select ok
10. F10 to save and rebooot

Yes, I am well aware that secure boot is more like Android Verified Boot than an actual security solution, in that it Verifies the bootloader (think of it as Verified Boot, not Secure Boot). However, it must be admitted that it is more secure to tell your PC to trust Rufus's signature than to just not check.

I think it advisable to include in the Wiki that you can tell your pc to trust the signature of UEFI:NTFS, and provide instructions when possible (ie, the ones i provided)

Log
---
```
n/a
```

**Comment by unixandria-xda** [comment]
And on my PC at least, it's only one or two more steps than disabling it entirely

**Comment by pbatard** [comment]
The FAQ is aimed at the vast majority of people who either don't have the option to add a specific bootloader hash or for whom the process will be a lot more complex than the simple operation of temporarily disabling it. Any Wiki or FAQ aims at providing general information on a topic rather than exhaustive hyper-detailed data about all the various ways one can address an issue, else you end up spending your life writing and maintaining a Wiki and not doing much else.

I don't think I want to start mentioning custom bootloader enrolment on account that:
- People who know about it will understand that, if they want to, they can use that instead of disabling Secure Boot
- I don't want to be bombarded by follow up question of _"Where can I find bootloader enrolment in my UEFI settings?"_ and _"Can you help me with the enrolment procedure on this specific machine?"_. Especially, a generic FAQ that is aimed at all PC users is not the place you want to start adding specific procedures for _"If you have an ASUS Zenbook 14, then you should perform the following 10 steps. If you have a Gigabyte Whatnot, then you should perform the following 15 steps. If you have a Lenovo Bleep, then you should perform these 13 steps. If you have a Dell Huh, then you should perform these 8 steps, etc._"

As much as I understand that you'd like the Wiki to be as exhaustive as possible, from where I stand, it just doesn't seem worth it, especially as you only need to __temporarily__ disable Secure Boot for UEFI:NTFS (once Windows gets to its first boot you can re-enable it) and therefore there's no much difference between enrolling the UEFI:NTFS bootloader and __temporarily__ disabling Secure Boot, as you will end up with pretty much the same in terms of security.

&rarr; Rejected.

**Comment by unixandria-xda** [comment]
If you have secure boot disabled for ubuntu install it doesn't sign proprietary drivers forcing you to either keep it disabled or go through the process yourself manually

I would at least mention something like "Some OEMs allow enrolling a custom hash. Please consult your OEM website for that, as we provide no support here". At least make people aware of it
