### ISSUE TITLE
Let a bootable UEFI-DVD-ISO boot from USB flash drive too? Add missing "bootx64.efi"?

### ISSUE THREAD

**Issue by pstein** [pbatard/rufus#1624]
﻿I have an UEFI-based ISO file for a tool on windows (NOT a WinOS itself).
If I burn this ISO onto a DVD and boot it on an UFEI computer (without Secure Boot) everything works.

However If I put this ISO with Rufus onto an USB flash drive the USB flash drive does not boot and show an error message:

"Could not locate 'EFI\boot\bootx64.efi': Not found

Yes, the file and the directory is missing.

After a long search I found in a german computer magazine years ago a hint:
Surprisingly a DVD-bootable ISO is NOT automatically bootable from USB flash drive  due to different handling of Bootmanager.

Interesting. I have not expected that.

But first of all, I would have expected from Rufus to show at this point a warning popup such as:
"USB flash drive will not be bootable due to missing \EFI\boot\bootx64.efi"
...but Rufus silently does: NOTHING.

The article mentioned a workaround on how to make such an USB flash drive bootable afterwards anyway:
Just copy from a 64bit Windows 7 system (resp ISO) the file "bootmgtw.efi" onto the USB flash drive into the corresponding directory and rename it to "bootx64.efi".

Is this possible by extracting (a similar/same?) file from a Wndows 10 (UEFI?) ISO as well?
Are there important differences between bootmgtw.efi files from Windows 7 and Windows 10 resp. between Windows 10 versions?

Maybe Rufus could add this file automatically from the currently active, running Windows 10 system or an additional Windows 10 ISO which the User provides? This would circumvent possible license problems.

Can this be added to Rufus?

Peter

**Comment by pbatard** [comment]
1. You didn't follow the check list and **choose** not to provide a log for your "UEFI-based ISO file for a tool on windows", which would help.
2. Rufus [already does what you suggest](https://github.com/pbatard/rufus/blob/ba406843f40d1a2e6af4b19d36fcfd37ea4a8fd0/src/format.c#L2147-L2163), however what you fail to realize is that this **only applies to Windows 7 x64 ISOs**. Windows 10 ISOs are different and have no need whatsoever for such a workaround. Especially, unlike Windows 7 ISOs, they do come with `efi\boot\bootx64.efi`, if you don't have that file on your custom ISO, then it was not properly mastered. And you really shouldn't pick or extract `efi\boot\bootx64.efi` UEFI bootloaders at random and expect your media to boot anyway. Bootloaders are specific for an ISO, and the only UEFI bootloader that is guaranteed to work is the `efi\boot\bootx64.efi`.
3. You need to fix your ISO or use an official Windows 10 ISO, which you will find works just fine for UEFI boot with Rufus (since it does have the `efi\boot\bootx64.efi` and therefore no need for a workaround). I don't support **UNOFFICIAL** Windows ISOs, period, because, as you should understand by now, these can too easily be crippled by people who have no idea what they are doing and remove critical files, such as `efi\boot\bootx64.efi`, at random.

As I believe I have answered your question, I will close this issue.
