### ISSUE TITLE
how do i build the code ?

### ISSUE THREAD

**Issue by knasim** [pbatard/rufus#1662]
how do i build the code ?

**Comment by pbatard** [comment]
Visual Studio 2019 or MinGW.
If you need more help than this, then I will ask you to please do your research, as I expect someone who wants to build Rufus from source to already be able to compile a simple "Hello World" C application in either Visual Studio 2019 or MinGW.

And please note that, if your question is really: _"How do I build Rufus so that it can run on Linux (or on Mac)"_, the answer to that is: You don't. Rufus is a Windows-only application.

As I believe I have answered your question, I will close this issue, as I'm afraid I have little time to hold people's hands on how to proceed with either Visual Studio 2019 or MinGW, especially as **all** the resources you need are already out there.
