### ISSUE TITLE
MBR as default mode

### ISSUE THREAD

**Issue by mrx23dot** [pbatard/rufus#1663]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Issue description
-----------------
Please make MBR as default selected method. I wasted 2hours with UEFI but couldn't get it working. (things should be getting easier with time, but not with BIOS-es)

MBR will run on UEFI, but not vice versa.

**Comment by pbatard** [comment]
> MBR will run on UEFI, but not vice versa.

I assume that you mean BIOS-compatibility as MBR is **not** a boot mode, and it doesn't "run" anything.
And if you are talking about BIOS-compatibility, your statement is not always the case. That depends if UEFI-CSM is enabled, which a lot of UEFI platforms will have disabled by default (even more so as Intel is currently pushing for CSM/BIOS-compatibility to be removed from UEFI platforms altogether).

Moreover, in this day and age, the vast majority of people will be using UEFI systems, and Rufus **will** display the following explicit message if you happen to boot a GPT/UEFI Windows media either on a BIOS-only platform or a UEFI one where CSM takes precedence:

![ERROR: BIOS/LEGACY BOOT OF UEFI-ONLY MEDIA](https://raw.githubusercontent.com/wiki/pbatard/rufus/images/legacy_boot.png)

For the record, the decision to default to GPT/UEFI rather than MBR/BIOS (or even MBR/BIOS+UEFI) was made very deliberately. We actually used to have MBR/BIOS as default, and switched to GPT/UEFI when it became apparent that UEFI systems were the majority.

As to the reasons why we don't create a dual BIOS+UEFI media for Windows, this is [explained in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Why_doesnt_Rufus_create_a_Windows_installation_USB_that_can_be_booted_in_dual_BIOSUEFI_mode).

I am therefore not going to change defaults that are the result of a very deliberate decision, on account that a **minority** of users are displeased with it, when the whole point is to make sure that the **majority** of users will end up with the most appropriate Windows installation for their platform (and don't waste their own time having to reinstall their OS because they wanted it install in UEFI mode and it got installed in BIOS/CSM mode).

Furthermore, I have always designed Rufus with the expectation that its users do have a minimum level of knowledge about MBR/GPT and BIOS/UEFI (which is why, for instance, we are throwing unfiltered terms like CSM in the UI), because we consider that installing an OS should not be attempted without basic boot knowledge. As such, we very much want people who see it differently, and expect a _"I should not have to look to look and understand options, but just press a single button"_ to be daunted enough by the UI to look for a different application. In other words, we deliberately chose not to sugarcoat or hide elements that we believe should not be glossed over and in that respect, we have very different design goals from Microsoft's Media Creation Tool (so please don't make the mistake of assuming that, because two applications are meant to achieve a similar goal, they should also have the same defaults).

&rarr; Rejected.

**Comment by pbatard** [comment]
> UEFI/MBR could be preselected based on detection.

Yeah, I thought about trying to do something like that, and the end result is the custom MBR, that gets applied to GPT/UEFI windows bootable drives (since GPT can have a Master Boot Record &mdash; Yes, this is confusing) and that produces the `ERROR: BIOS/LEGACY BOOT OF UEFI-ONLY MEDIA` notice.

Now, with regards to doing more than this, the problem is that most UEFI platforms come with Secure Boot enabled, so adding a UEFI boot loader that would somehow allow the user to select BIOS/CSM mode would require going through the Secure Boot signing process, which means giving up on the GPLv3 license, which I am very reluctant to do (I chose that license for a reason), and which is also costly.

All in all, the cost/benefit ratio of developing a custom bootloader that reports the current boot configuration to users in all possible cases, and lets them pick the one they want to use is simply too high (and not just in terms of money but in terms of time). This would benefit too few people compared to other features that I still would like to add to Rufus, so, whereas I definitely considered doing something like what you suggest (especially with regards to reporting to users whether Secure Boot is enabled, as it seems to be a major point of confusion and trouble), I had to reject it due to the overall cost of doing so.

**Comment by mrx23dot** [comment]
Sounds like reading MBR as TRUE gives a definite answer that we have to use legacy mode.

Here is a quick way of testing it, (2nd answer, there is an MBR signature 55h AAh on a specific location )

https://superuser.com/questions/510485/how-to-tell-which-physical-disks-have-bootable-mbr

**Comment by pbatard** [comment]
The drive you created initially has the `0x55 0xAA` signature so that the MBR code that displays the message executes on UEFI systems. The drive is for UEFI installation. And Rufus is the application that writes those bytes (not the BIOS or UEFI).

As to reading the MBR of existing HDDs, it doesn't tell anything, especially as the user might not have a disk set up, or might want to switch from BIOS-bootable to UEFI-bootable.

Please do a little bit more research. Yes, software developers can miss elementary solutions. But that's the exception rather than the norm, so you're better off assuming that if an application doesn't use a simple method to achieve something, it's not because the developer didn't think of it, but because the developer rejected it for a good reason.
