### ISSUE TITLE
Create Rufus in Microsoft Fluent Design

### ISSUE THREAD

**Issue by Ostrjs28** [pbatard/rufus#1677]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Create Rufus with Microsoft Fluent Design.

It would be very nice if Rufus has a theme manager integrated by default to change the design in the future e.g. to current Microsoft Fluent Design.
https://www.microsoft.com/design/fluent/#/

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
The 2.x &rarr; 3.x UI redesign **was** a best effort to make Rufus Fluent-like.

Considering that it took about 4 months of **full time** work to get there, that it's not just a matter of editing some XAML and be done with it (we have very specific constraints, in part because we still can't just tell Windows 7 users to get lost), and that it was a massive effort, I am not in a hurry to go through a UI redesign anytime soon, especially as, as far as I a concerned, Rufus looks more than Fluent enough to me (since the redesign **was** based on an actual Fluent Design mockup), and we're not designing a music player where it makes sense to provide theming.

The best you are going to get for now is a dark mode, but even that is super low priority.
