### ISSUE TITLE
DragonFlyBSD is not supported

### ISSUE THREAD

**Issue by dvv35hjrd** [pbatard/rufus#1678]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I cannot create a bootable Live USB for DragonFlyBSD with rufus 3.13.1730.

https://www.dragonflybsd.org/download/
http://mirror-master.dragonflybsd.org/iso-images/dfly-x86_64-5.8.3_REL.iso

I dragged and dropped the iso file to rufus and then get this error message.

**Unsupported image**

**This image is either non-bootable, or it uses a boot or compression method that is not supported by Rufus...**

Log
---
```
<
Image provided: 'C:\Users\Smith\Desktop\dfly-x86_64-5.8.3_REL.iso'
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Note: The selected ISO uses Rock Ridge 'deep directories'.
  Because of this, it may take a very long time to scan or extract...
Disk image analysis:
  Image does not have a Boot Marker
ISO label: 'DragonFly_v5.8.3'
  Size: 2.4 GB (Projected)
  Has a >64 chars filename
  Has a Rock Ridge deep directory
  Note: This ISO uses symbolic links, which will not be replicated due to file system
  limitations. Because of this, some features from this image may not work...>
```

**Comment by pbatard** [comment]
BSD ISOs use their own custom boot method, instead of using longstanding ones like GRUB or Syslinux.

As such they are not supported by Rufus, because the return on investment of trying to support BSD, especially for an application that you get for free, is simply not worth it.

Moreover, https://www.dragonflybsd.org/download/ indicates that you can download either an **ISO** or a **USB** image. If your plan is to create USB bootable media, you should off course download the latter, which should work with Rufus. For BSD, the only time you should use an ISO is if you are going to burn an actual optical disc.
