### ISSUE TITLE
Can you provide a check code?

### ISSUE THREAD

**Issue by 18617146050** [pbatard/rufus#1698]
MD5 SHA-1 SHA-256

**Comment by pbatard** [comment]
Unneeded because the application is digitally signed, therefore an SHA-256 validation check is automatically performed for you as part of the digital signature check when Windows opens the executable.

In other words, if you happen to have downloaded an executable that is either corrupted or compromised, the signature check will fail. Therefore, providing a separate SHA-256 is completely pointless.
