### ISSUE TITLE
Run several copies of Rufus

### ISSUE THREAD

**Issue by eXPert-nnm4evr** [pbatard/rufus#1749]
Hello. Why is there no setting in Rufus to enable / disable the ability to run multiple copies of a program? Sometimes I need to create several bootable USB disks for testing computers, and I have to use several programs for this, or I could just run several copies of your program (Rufus). (C) Googole Translate.

**Comment by pbatard** [comment]
Because too few people need that feature, and it would take a lot of time to add, on account that the application would need to make sure that it doesn't attempt to access the same drive.

It's just too much effort for too little benefit, and you need to understand that Rufus is not designed as a power user/sysadmin utility. In other words, advanced features like this, that would not benefit the vast majority of Rufus users (who only need to create a single drive), are not something that I am willing to spend time on, as I just don't have enough development time available to devote to these.

See also https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want.

As I believe I have answered you question, I will close this issue.
