### ISSUE TITLE
Rufus does not find ISO (with solution)

### ISSUE THREAD

**Issue by RenatoLopes771** [pbatard/rufus#1785]
﻿

Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [X] Using a different USB drive.
  - [X] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

Rufus can NOT find ISO. 

Well actually, it's looking into the wrong place. I thought of naming my issue like this in case other people come across this error. It's more of a feature request.

When I download rufus, it goes into the "downloads" folder. However, it goes to the downloads folder of the administrator rather than the current user I am in. If I click on the address bar it will show downloads and not the user, making it tricky for laymans to find the file they want.

Therefore I request that rufus open on the same folder it was downloaded OR open on the current user folder.

I had to go to my user folder and to the downloads of that folder to find what I wanted.

Similiar issue I found: https://www.bleepingcomputer.com/forums/t/698369/rufus-cant-detect-iso/

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
> However, it goes to the downloads folder of the administrator rather than the current user I am in.

Did you create an explicit _Administrator_ user then?

On a standard installation of Windows 10 for instance, there is no _Administrator_ user account under `C:\Users` and considering that very few people are reporting this issue, I expect this to only happen if you create an actual _Administrator_ account.

In other words, I don't believe this is an issue that actually warrants fixing, because for people who don't have a formal _Administrator_ account, the default location will be their user's Downloads folder, and I'd expect people who did create a formal _Administrator_ account to be able to easily locate the files, if they find that the default Downloads folder being opened by Rufus is missing them.

And since you didn't provide a log, I'd also like to know what version of Windows you encountered this issue on.

**Comment by RenatoLopes771** [comment]
> 
> 
> > However, it goes to the downloads folder of the administrator rather than the current user I am in.
> 
> Did you create an explicit _Administrator_ user then?
> 
> On a standard installation of Windows 10 for instance, there is no _Administrator_ user account under `C:\Users` and considering that very few people are reporting this issue, I expect this to only happen if you create an actual _Administrator_ account.
> 
> In other words, I don't believe this is an issue that actually warrants fixing, because for people who don't have a formal _Administrator_ account, the default location will be their user's Downloads folder, and I'd expect people who did create a formal _Administrator_ account to be able to easily locate the files, if they find that the default Downloads folder being opened by Rufus is missing them.
> 
> And since you didn't provide a log, I'd also like to know what version of Windows you encountered this issue on.

Precisely. I have an administrator account and a user account without admin rights. I installed rufus on this user account.

I am using Windows 10 version, recent updates.

**Comment by pbatard** [comment]
>  I have an administrator account and a user account without admin rights. I installed rufus on this user account.

Then, because Rufus runs elevated, this is the same as running it as the administrator account, and, if you do create a formal administrator account and a user account without admin privileges, then I expect you to be aware that elevated apps will behave as if they were running as the admin and use the default admin locations for Downloads, user settings and so on.

As such, because this is an issue that affects too limited a number of people, and because, again, I expect those people to be able to locate content that resides outside of the Administrator account, I am not planning to do anything in Rufus to address this specific situation. It's simply not worth the effort, sorry.
