### ISSUE TITLE
Using RAMDisk when creating a Windows To Go installation

### ISSUE THREAD

**Issue by rigon** [pbatard/rufus#1822]
This is an improvement to be considered. Creating an Windows To Go installation is very slow when used with a USB stick. USB sticks are usually bad dealing with 4K writes operations, and creating a WTG requires a lot!!!

What I'm proposing is a new way to build the media in two steps:
1. Instead of writing directly in the device, it is possible to create a virtual disk for a temporary filesystem (ideally in RAM, the pagefile can help if you don't have enough) and use that to build the installation.
2. Once completed, write the virtual disk to the desired device. After that, resize the partition in order to have access to the unallocated space left at the end of the device.

In fact this is already possible, but would be nice seeing that being supported natively by Rufus:

1. In Windows, open the **Disk Management** tool. There create a VHD with at least 16GB, using the menu option **Action** > **Create VHD**. If you have a [RAMDisk ](https://sourceforge.net/projects/imdisk-toolkit/), use that as location, it will help speed up even further.
2. Rufus will recognize the new virtual disk as possible device after being created.
3. Create the Windows To Go installation as usual, using the virtual disk.
4. Once completed, head back to **Disk Management** and detach the virtual disk (right click on the virtual disk > **Detach VHD**).
5. On Rufus again, select the USB stick as device and the virtual disk file as *Boot selection*. Hit **START**.
6. Done! Resize the partition on the device to fill the free space.

This process is WAAAYYY faster than the currently implemented.

**Comment by pbatard** [comment]
I appreciate the suggestion, but I don't think I want to add that natively to Rufus, as you correctly pointed out that, if you do care about improving Windows To Go creation performance, you can already use Rufus to create the Windows To Go drive to a VHD of the appropriate size, and then write that VHD using Rufus.

All in all, I don't see much benefit in adding a convoluted code path for Windows To Go creation, when the people who really do care about performance will manually perform the steps you indicate (which aren't that complicated) and the people who don't really care about Windows To Go creation performance will just let Windows run and do something else.

Also, and __THIS__ is the actual critical part, people who actually do care about Windows To Go performance do use a drive where 4K/random I/O is fast, rather than the first consumer USB flash drive they have lying around because, if you don't, then it doesn't matter how fast the Windows To Go drive is being crated: __The overall Windows performance will be atrocious__.

So I will posit that it's actually _better_ not to optimize the Windows To Go creation, because, if someone is using a drive that is actually unsuitable for running Windows To Go, they will get a super poor write performance when creating the drive in Rufus, which may help them consider using a better drive.

On the other hand, if I were to go with what you advocate, and the user happens to have one of the modern flash drives that's relatively good at sequential writes but very poor at random I/O, then they may think everything is fine, when it most certainly isn't, because the minute they launch Windows, they will definitely not see the performance that they expected from the time it took to create the drive.

As such, I am going to reject this request on the ground that users need to get an idea of how good or bad their Windows To Go drive will run, and trying to hide the performance of a drive that is ill suited for Windows To Go will not help anyone...

My rule of thumb for Windows To Go is actually as follows: If Rufus can't create your Windows To Go drive in less than 15 minutes, then your drive is __unsuitable__ for Windows To Go, and you should use a different one because not amount of trickery with ramdisks, VHDs and whatnot will make the drive magically perform well once Windows is running from it.
