### ISSUE TITLE
About the UEFI:NTFS #1825

### ISSUE THREAD

**Issue by tavrez** [pbatard/rufus#1826]
You closed #1825 
My rufus version is 3.17 portable which I got from github minutes before creating issue., I just missed the version line when I dragged the mouse to copy.
My system is x64.
Also used a real flash and rufus, still no luck.

Just wanted to complete missing informations, but you are obviously not interested, alright.

**Comment by pbatard** [comment]
Feel free to extract the `bootx64.efi` from the uefi-ntfs image or partition that was created.

You will see that it was signed for Secure Boot by Microsoft.
![Image1](https://user-images.githubusercontent.com/1206968/141536418-3a31d04e-b304-4db7-939a-cdaa8319615d.png)

And no, Rufus does not embed 2 copies of the uefi-ntfs data or anything, so if your systems can boot from a properly Secure Boot signed executable, then the issue is with your system.

Again, this was tested, and you are the only person to report the issue. We made a big deal of Rufus 3.17 providing Secure Boot compatibility, so if it was universally broken, it would have been universally reported.

Therefore, the problem is entirely on your side.
