### ISSUE TITLE
Failed to extarct iso, and now the usb is not detecting ANYWHERE

### ISSUE THREAD

**Issue by matei9** [pbatard/rufus#1857]
Issue description
-----------------
So, i have an 32 gb falsh drive, i flased a xububntu 18.04 image and it failed to extract iso. Now, when i restart the pc, it's stucl on "restariting" until i remove the drive, if i turn on the pc with the flash drive on, it won't boot. It isn't detected in disk managent, mini partition tool, or even in manajro with gparted! Any help?

Log
---
```
Sorry, i don't have.
```

**Comment by pbatard** [comment]
>  i flased a xububntu 18.04 image and it failed to extract iso

More accurately, it looks like the drive failed while you were writing the xubuntu image, which resulted in Rufus reporting an error during extraction (rather than Rufus somehow causing an error that resulted in your drive failing, which is [simply not possible](https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive)).

A failed drive can indeed prevent a computer from shutting down or rebooting if it fails to send the USB device descriptors in a timely manner.

Unfortunately, if you are unable to recover the drive, even when using a different computer or when running Linux, it most likely means that your drive is dead, and you should replace it. Unlike what you may read online, there is no "magic trick" to recover a dead drive, especially if you were sold a fake drive (a fake drive is a drive that was modified to report more space than it really has).

Considering that there isn't much that can be done to help, I will close this issue.
