### ISSUE TITLE
Selecting an ISO changes some settings unexpectedly

### ISSUE THREAD

**Issue by mattyway** [pbatard/rufus#186]
If "Use Rufus MBR with BIOS ID:" is unticked before selecting an ISO image, it will be reticked after selecting an ISO image. I would expect that all settings would remain the same after selecting an ISO.

**Comment by pbatard** [comment]
After much reflection, I just going to discard this request.

While, for a user, this may look like an "easy" fix, it is anything but. As a matter of fact, "smart UI" (and intelligent settings preservation) is about the one thing you'd really want deep learning algorithms to take away from the programmer because:

1. These features are __incredibly__ difficult to properly implement manually, as to do so requires formulating all the paths in which a setting should or should not be altered, and even in an seemingly simple application like Rufus, if you want to do it properly, there probably exist about 100 individual factors (a.k.a. possible states &mdash; I wish I was kidding!) that may need to be taken into account, just to determine how a setting should be altered by the application.

2. Crafting and maintaining a state machine, which is really what you'd be after here, is also __mind-numingly__ boring... In fact, this kind of boring, repetitive and prone to human error stuff (because, boy are state machines prone to human error and demanding an innate amount of testing for every possible path) is just the kind of thing that automation was invented for... but sadly, computers are not yet "smart" enough to craft a UI state machine on their own. :disappointed: 

So, all in all, and while I understand that this will cause minor UI inconveniences here and there, I think I'll just continue to sit and wait for the day where a good deep learning UI automation library is created, that can free developers from having to literally spend __days__ ensuring that the less travelled UI paths behave in a fashion that users will find as intuitive as possible.
