### ISSUE TITLE
USB drive unusable after incomplete Rufus session

### ISSUE THREAD

**Issue by cysjunk** [pbatard/rufus#1874]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I had to cancel my Windows 11 To Go USB because it hanged at 62.6%, my computer went to sleep while Rufus was writing the files. I can't use the USB again, when it's plugged in I can't use dskchk (hangs), Disk Management (hangs), I can't even use an external partition manager (hangs while loading the drive). Everything involving disk partitions hangs when I have the drive plugged in, including Rufus itself. Rufus will launch when the drive isn't plugged in, when I plug it in again it crashes. I think Rufus did indeed destroy the drive. If not could someone help? It's a flash drive, not a hard drive.

Log
---
```
No log
```

**Comment by pbatard** [comment]
> I had to cancel my Windows 11 To Go USB because it hanged at 62.6%

Most likely it hand because your USB was defective.

Rufus was writing to the drive, and got to the __already__ defective part, which is what caused it to hang, not the reverse (i.e. it's not Rufus hanging that caused the drive to fail).

Applications that write to a drive tend to detect when a drive fails. That does not mean that the application was responsible for the failure.

> I can't use the USB again, when it's plugged in I can't use dskchk (hangs), Disk Management (hangs), I can't even use an external partition manager (hangs while loading the drive). Everything involving disk partitions hangs when I have the drive plugged in, including Rufus itself.

Then your drive is most likely dead and you will have to replace it.
You may see if it's accessible from Linux or some other OS, but by the looks of it, you won't be able to recover your USB drive as it has a hardware issue.

> I think Rufus did indeed destroy the drive.

That's simply [not possible[(https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive).

Instead what happened is that:
1. Your drive failed
2. Rufus detected the drive failure, as it was writing to it.

As there isn't much that can be done, considering your symptoms, I will close this issue, as you will have to replace that drive.
You may also want to double check that you weren't sold a _fake drive_ (i.e. a drive that falsely reports more capacity that it really has, which will tend to fail in the manner you describe as soon as you go over the actual capacity of the drive(, and make sure you run a bad blocks check on any future drive you use.
