### ISSUE TITLE
How can I verify my USB disk do not have any malware(Or the USB disk only including the ISO file)?

### ISSUE THREAD

**Issue by Nillouise** [pbatard/rufus#1882]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
If my window system have malware, and I use this system and rufus to write a official win10 ISO(I known I can use md5 to check it) to USB disk, how can I verify my USB disk do not have any malware(Or the USB disk only including the ISO file)? 

Sorry about ask this simple question, but this question confuse me a long time, I read the FAQ, but I can't find a clear answer.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
This is beyond the scope of what I can provide for.

If your system has malware, then there is no way you can validate that there won't be malware on the USB drive, because there are just way too many means malware can be added, even if you verify the content (because there are simply too many vectors of infection that can be used).

But again, this is not the right place to ask this kind of question. Please go to a security oriented user forum, which this issue tracker isn't.

Now, what I can point to with regards to assuring that the Rufus executable isn't malware, and that, when running it, it won't install malware, is [this](https://github.com/pbatard/rufus/wiki/Security). But as soon as you have a media that is read/write, it doesn't matter if the application that wrote to it is beyond any suspicion, because it's game over, since malware can infect whatever it wants after the application is done with the USB.
