### ISSUE TITLE
Created an image for linux and an error  occurred and does not recognize the usb

### ISSUE THREAD

**Issue by PedroDuarteDev** [pbatard/rufus#1890]
I created an image for elementary os and half way through an error occurred and when i tried to start again rufus does not recognize the usb.
The usb is recognized by the device manager but i cant format it and also convert it back to gpt using diskpart.
![1](https://user-images.githubusercontent.com/70894768/159372317-43754ae8-a365-4bd0-aa01-57e4622e79e6.JPG)
![2](https://user-images.githubusercontent.com/70894768/159372320-b9556237-829c-4d45-bb57-8c49e66705cf.JPG)

**Comment by pbatard** [comment]
> half way through an error occurred

This tends to indicate that:
1. The flash memory of your USB drives was __already__ defective by the time you started using Rufus
2. Because of this, when Rufus started to write to the defective blocks, your USB drive failed altogether
3. As a result, Rufus reported an error to let you know that there was a hardware issue with your drive.

Unless you can recover it on a different machine/different OS, your USB drive is most likely dead. Especially, because they use the same circuitry as card readers, a lot of flash drives will fail in the manner your describe, with the device being "detected" by Windows bu reporting no media. So the best thing you can do really is recycle your flash drive, as it will be a waste of time to try to recover it.
