### ISSUE TITLE
Portable SSD can't be format after using Rufus

### ISSUE THREAD

**Issue by IvanSong140** [pbatard/rufus#1895]
Dears, 
I found the issue that I can't format the portable SSD after using Rufus, And I am 100% sure no hardware problem, I had the Plextools checked my SSD, and I found it can't be format because of the partition was write protected which have a read me file described as following  "this partition was created by Rufus (https://rufus.ie).
<img width="405" alt="2022-03-30_070545" src="https://user-images.githubusercontent.com/102631561/160720840-6ef52f6b-0c25-449d-afb2-6b51eeea0f4e.png">
It is used for booting NTFS and exFAT partitions in UEFI mode. For details, see https://github.com/pbatard/uefi-ntfs."
It is better to check what is the problem is, to avoid any further problem of this  @pbatard 

![image](https://user-images.githubusercontent.com/102631561/160720881-06a2251e-623c-4ea5-8295-9dee6c11a32f.png)
![image](https://user-images.githubusercontent.com/102631561/160720987-b476b497-b8bf-4d11-be2c-a4c3f4d87ff0.png)
![image](https://user-images.githubusercontent.com/102631561/160721272-f125e33d-9853-4c0a-bfae-2df4ff8558c9.png)
![image](https://user-images.githubusercontent.com/102631561/160721196-25fba08b-c462-4a94-8f80-477a73bae54f.png)
![image](https://user-images.githubusercontent.com/102631561/160721391-954bd7a3-18ca-4360-8b97-d383ecdfc660.png)
![image](https://user-images.githubusercontent.com/102631561/160721528-df7e4ffd-7e99-4bc1-96e4-28cd2a4fb406.png)
![image](https://user-images.githubusercontent.com/102631561/160721675-01de7abb-1892-43a0-a1c4-32ad3ed045ab.png)
![image](https://user-images.githubusercontent.com/102631561/160721772-d28037ea-896a-4f8d-a4cd-01e8fd180b0c.png)
Every time I try to format, it tells me the disk is write protected, can't format

![image](https://user-images.githubusercontent.com/102631561/160721967-f246e4aa-0074-4aa4-88cf-745a0862b738.png)

**Comment by pbatard** [comment]
> And I am 100% sure no hardware problem

And, if you can't reformat it in Linux or some other OS, I am 100% sure it __is__ a hardware problem.

Your drive failed in the typical fashion that many flash drives fail, where, on detecting that he flash memory is compromised, the flash drive controller sets the drive to "read-only"/"write-protected" in order to give you a chance to read the data.

[It is simply not possible for software like Rufus to damage a flash drive, period](https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive). But if you do think otherwise, please contact the manufacturer of your flash drive, to tell them that you _believe_ that there exists software that can damage their hardware, because, if there's even a remote possibility that this could be true, they will have all the incentive in the world to help you prove that assertion (since they are bound to lose money on RMA otherwise).

However, considering that, in the 10 years that Rufus has existed, with many people like yourself adamant that, _"no, if a drive fails while using this or that software (because, if you look around, you'll find that people are accusing software like balenaEtcher of about the same thing when they experience a __coincidental__ drive failed), then it must mean that the failure was caused by that software!"_, not a single manufacturer or expert has ever produced even the slightest evidence to sustain the possibility that software could be responsible for such failures, I believe that you will have a hard time getting people to rally to the idea that software, and especially software running on Windows, where the abstraction layer means that USB drives are not accessed any differently than any other non USB drive, can damage hardware.

> It is better to check what is the problem is, to avoid any further problem of this @pbatard

The problem is that flash memory is a lot more unreliable than people realize, no matter how reputable the brand, and flash based hardware will fail regardless of the software being used, especially if you happen to write a large amount of data to it.

And there's really nothing I can do to avoid these kind of problems, as, again, and despite what many people think, Rufus is __not__ sending special USB commands, that people also think might cause damage if there was a bug in the application, but instead, Rufus is simply telling Windows "write that file on this drive" or "write that block on this drive", with no need whatsoever to bother with sending USB, SATA or whatever some people think could lead to "potentially dangerous" commands being inadvertently sent.

So, the only advice I can give you, after making sure that you can't recover the drive on a different OS (because Windows does have some weird bugs that sometimes make it look like the hardware is defective, though these typically would not result in a drive being seen as write-protected), is to RMA your drive and again, if, against all evidence of the contrary, you still believe that software could have caused your hardware failure, get in touch with some experts from your drive manufacturer, as, once more, they are sure to have a vested interest in trying to prove you right, if you are that confident that it is in fact Rufus that caused your issue.
