### ISSUE TITLE
Rufus error

### ISSUE THREAD

**Issue by LordBarren** [pbatard/rufus#1899]
I can't make a bootable usb using Rufus..help me. Discription in the photo
![Screenshot 2022-03-21 162715](https://user-images.githubusercontent.com/102891109/161411962-c3ee2bfc-15a3-428e-9ce9-46e33033f54c.png)
![Screenshot 2022-03-21 162747](https://user-images.githubusercontent.com/102891109/161411967-c11ca5e7-aad9-4d15-b1a7-5c2a853afa88.png)

**Comment by pbatard** [comment]
You have an overzealous security solution that prevents __legitimage applications__ like Rufus from creating an `autorun.inf` file, because your security solution was poorly designed to assume that any `autorun.inf` file is nefarious.

You will need to find what application that is (most likely it's your antivirus, but it may be something else) and contact the developers of that application to tell them that they are doing a very poor job indeed, and that they should __NOT__ prevent the creation of `autorun.inf` files that only contain an extended label and an icon.

Considering that there's absolutely nothing more I can do for you (next time, please try to follow the check list okay? It's not that hard, and you should have found other similar issues if you had done so), I will close this issue.
