### ISSUE TITLE
Fake rufus copy, with a replicate look

### ISSUE THREAD

**Issue by UltraToon** [pbatard/rufus#1907]
When searching up "rufus" in the google search engine, the first result is a replicate website of rufus, that is a scam. 

I verified that the downloads from the website are viruses, and should not be used.

![image](https://user-images.githubusercontent.com/92064752/163598844-8db17b8e-45aa-49f0-8cbf-fb46fae98b4f.png)

![image](https://user-images.githubusercontent.com/92064752/163598876-3781525f-c686-4afe-82c3-20549f6d0887.png)

**Comment by pbatard** [comment]
Please report it to https://safebrowsing.google.com/safebrowsing/report_badware/?hl=en. 

Also, your first "result" is actually an Ad (since it is prefixed by ___Ad___), and therefore this is not actually a result.
Some people are trying to profit off Rufus, and appear to be paying good money to place ads that unscrupulous users like yourself will believe are an actual search result, when they certainly aren't. So please be mindful that not everything displayed in a Google search might be an actual search result.

And if you want to help, report that site to the link I gave you, as there is only so much I can do to try to weed out these fake sites.

**Comment by pbatard** [comment]
Addon: You may also want to report this deceptive ad at https://support.google.com/ads/troubleshooter/4578507?hl=en.

**Comment by kiencuongpo** [comment]
https://chrome.google.com/webstore/detail/ublacklist/pncfbmialoiaghdehhbnbhkkgmjanfhe
