### ISSUE TITLE
Rufus for macOS (Message for project admin)

### ISSUE THREAD

**Issue by yap241986** [pbatard/rufus#1910]
I want to collaborate with Rufus and so I had started the development of a version of Rufus for macOS. If you say to me that's ok, I finish the development. I can translate the macOS App in Italian, French and English.

**Comment by pbatard** [comment]
I appreciate the effort, but I'm afraid that this is not how it works.

Hopefully you can appreciate that there's simply no way I can commit to supporting your work before I see its outcome, because there are just too many unknown, and I can simply not state that something is "affiliated with Rufus" when there's absolutely nothing that you can show me.

First of all, you do not need my "blessing" to create a Rufus derivative for macOS, Linux, or whatever. The GPLv3 license allows you do just do so, without even having to ask me. Of course, if you choose to do something like that, I would prefer that you indicate that this a derivative that is completely separate from the main project, so that you don't give your users the impression that you are only using a well established name to push a project that isn't affiliated with Rufus and may or may not meet the same standards onto them.

Also, I'm afraid the fact that the only porting point you are talking about is translation, whereas, if you are actually porting Rufus to a different platform, then you should naturally be able to use the existing translation framework from the main application, and therefore will not have to worry about translating the app, leads me to think that you haven't really started to look at what the porting effort actually entails.

For instance, I wouldn't mind knowing how exactly you are planning to add the ability to create Windows bootable drive with UEFI:NTFS (since you can't use FAT due to `sources/install.wim` being larger than 4 GB) on macOS. Does macOS come with a native NTFS driver? Or if not, do you have plans to write a GPLv3 version of one? And what are you plans for the various features that Rufus provides, such as downloading Windows ISOs (which is based on [running a Windows PowerShell script](https://github.com/pbatard/Fido)) or creating Windows To Go drives (which is based on having access to the WIM API, and needs the [invocation of the Windows exeutable `bcdboot.exe`](https://github.com/pbatard/rufus/blob/master/src/format.c#L1435-L1449)).

As I hope you can expect, I can't say that I am that interested in having a bare mimimum version of Rufus for Mac, that is lacking too many of the functionality of the Windows version, as there is simply no way I will want to associate myself with that project.

So, once again, I will tell you that you are free to start the development of a Rufus _derivative_ for macOS, and you absolutely don't need my blessing. But I'm afraid that I will not be involved with your project unless you actually have something to show for it. But I don't really see how you can achieve that without sinking A LOT of development time reinventing elements that Windows provides natively and that are the basic reason why I don't really ever see a macOS version of Rufus, that I can consider supporting becoming a reality...
