### ISSUE TITLE
windows 11 blocked KB5012643

### ISSUE THREAD

**Issue by xjoao97** [pbatard/rufus#1914]
Issue description
-----------------
new windows 11 update blocks everything would it be possible to unlock in the new version of rufus ??
KB5012643

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
> blocks everything

Please define everything. I have no idea what your "everything" means.
What item from [KB5012643](https://support.microsoft.com/en-us/topic/april-25-2022-kb5012643-os-build-22000-652-preview-43a75ee7-d857-4943-a2b9-f961538bd2b0) is your issue?

> would it be possible to unlock in the new version of rufus ??

You seem to be under the __misguided__ impression that Rufus alters the Windows installation files, probably based on the __very wrong__ belief that, in order to bypass the Secure Boot and TPM requirements, we alter Windows components.

__That is not correct__.

The way the requirements are bypassed is by creating registry keys __for the Windows installer__ (since the restrictions are enacted in the installer and NOT in the actual installed version of Windows). As such, and this needs to be stressed out, __ALL__ of the Windows components that get installed are the __UNMODIFIED ORIGINAL MICROSOFT VERSIONS__. Or, to better help you understand how the Windows 11 bypass works, it's exactly as if the Windows installer was a commandline application that had some options such as `--bypassTPM` or `--bypassSecureBoot`, that Microsoft did add (but does not use by default) in the original installer executable, and Rufus is simply adding those options on the commandline when you choose to bypass TPM/Secure Boot. In short, we're using a feature that Microsoft provides but does not use.

Therefore, Rufus does not have the capability to alter the behaviour of your installed version of Windows. Never did, never will do. And that is actually part of the mandate with which Rufus is designed: help with the installation of OS, by creating USB media that behave as close as possible to how an optical media would behave. And whereas we chose to add the bypass for some (but not all) Windows 11 requirements, we only did so because this could be enacted by passing options to the installer without the OS behaving any differently or being altered in any way, compared to how it would have been installed through optical media.

And this also means that your request is pointless. Rufus does not "hack" Windows to "unlock" things. If the installed version of Windows does not work as you want, you will need to solve that issue with Microsoft because, maybe, as is the case with the Windows 11 installer, they have added some options that allow you to "unlock" the "everything" you want... whatever that is.

As such I will close that issue. But I will still be interested to hear what you "blocks everything" actually means, and what exactly you could do prior to KB5012643 that you can't do any more.
