### ISSUE TITLE
Stuck at NTFS Fixup 100%

### ISSUE THREAD

**Issue by xeinebiu** [pbatard/rufus#1949]
![image](https://user-images.githubusercontent.com/50703441/173453438-49f7f9e6-91cd-4e70-b359-de61db1f4fee.png)

Antivirus (Windows Defender) is disabled.

There is a constant reading speed from the device as well.

![image](https://user-images.githubusercontent.com/50703441/173453692-6c809ec5-8dfa-4a8a-8ac7-47e4e67c2d6b.png)

**Comment by pbatard** [comment]
Log is accessible even when Rufus seems stuck.

Please provide your log as I genuinely cannot help you without it.

Also, this could be an indication that your drive is actually defective, so I would __strongly__ advise you to run a bad blocks check, like the checklist that you ignored advised you to do.

**Comment by dion-pro** [comment]
This happened in my Kingston 32 GB USB 3.2 Disk. When I eject it, it responds.

**Comment by pbatard** [comment]
> Please provide your log as I genuinely cannot help you without it.

**Comment by xeinebiu** [comment]
In my case, my USB does not respond anymore. No media type found an error.

I do not think Rufus broke it though as I have been using Rufus since 2015-16. I used the device on a Xiaomi MiBox S which formatted my drive, then I wanted again to make it bootable with Windows and I was facing an NTFS Stuck error.

I tried the AID with Mackbook and it took quite some time and said the USB is healthy, but RUFUS still was failing. After 4-5 of RUFUS Failing, the USB stopped completely responding.

So, I can't help guys more than this.

**Comment by pbatard** [comment]
@xeinebiu,

Thanks for the report. So the reason for the "Stuck at NTFS fixup" is that your USB was failing, which makes sense, but is obviously not a problem that Rufus can fix.

Because this is a frequent problem (Flash drives do fail a lot more frequently than people expect), I'm going to assume that the same thing is true for @dion-pro, so I'm going to close this call, especially as one has to realize that the "NTFS Fixup" step is one where we simply call Windows checkdisk and wait for it to complete (Rufus does absolutely nothing but wait on a Windows native utility call to complete). So you would encounter the exact same issue if you called Windows' checkdisk manually and, obviously, because I am not Microsoft, I can't alter the behaviour of checkdisk if it appears stuck or uses 100% CPU.

**Comment by xeinebiu** [comment]
@pbatard feel free to close the issue as per my side it is how I described above.

At the time I opened this issue the USB still was working for copying files but since now it does not work at all, I assume it was a USB Failure.

**Comment by JonnyTech** [comment]
> After 4-5 of RUFUS Failing, the USB stopped completely responding.

Cheaper USB drives, especially plastic body ones, do get rather warm and are unable to dissipate heat well. Programs like Rufus have a very long and consistent write cycle which causes the drives to get very warm indeed. If you are doing 4-5 cycles of Rufus operations without giving the drive a suitable period to cool down then it will generally result in a drive failure (the most common situation being the firmware locking it permanently in read-only mode). I tend to alternate drives or have a small usb-powered fan pointing at the unit to avoid such failures.

These observances are my own, with multiple tests performed on many, many cheap plastic USB drives; the types given away free at conferences and exhibitions. Sometimes just two runs is enough to destroy a drive. And as each version of Windows gets bigger, then the Rufus write cycle gets longer, therefore the drives get warmer. Hence, I believe, that explains why we are getting more and more reports of drive failures.

Also, I have personally observed people running Rufus twice in quick succession in order to "make sure that the data is written correctly". I strongly advise against this procedure as it can kill the drive during the second write period.

**Comment by xeinebiu** [comment]
@JonnyTech 

If this is true, then I expect the USB Drive got broken after the MacBook Pro did a full AID Scan and the device got very hot. As the process took almost one hour and the USB was all hot during that time, it makes sense why it was completely broken.

![image](https://user-images.githubusercontent.com/50703441/174444143-b7ab1be4-16ee-4ebf-88f3-ec280f03799b.png)

**Comment by xeinebiu** [comment]
I still wonder, why it was failing only on "fixing NTFS". Is there any specific part of the USB which could be failing for this process?
