### ISSUE TITLE
Support for .wim file compression

### ISSUE THREAD

**Issue by msoxzw** [pbatard/rufus#1955]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
A .wim file can be compressed into an .esd file, so none of files in a Windows ISO are larger than 4 GiB, and consequently NTFS driver and its by–products could be circumvented.

The following codes are PowerShell commands used for comprssing "install.wim" into "install.esd", which require administrator privileges and consume a significant amount of CPU time and memory. 
`Get-WindowsImage -ImagePath "install.wim" | ForEach-Object {dism /Export-Image /SourceImageFile:"install.wim" /SourceIndex:$($_.ImageIndex) /DestinationImageFile:"install.esd" /Compress:recovery}`

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
This has been proposed time and time again, but if you look at it objectively, straight copy of the original content of the ISO is much better than any other solution, especially as chain loading the bootloader from an NTFS partition costs nothing in terms of space or time (and __is__ compatible with Secure Boot).

Plus, the NTFS solution is compatible with Windows 7, which the wim compression solution isn't (because you can't just "mount" and ISO on 7, and you'd have to temporarily extract the file first).

Unless you can point to a major problem with the UEFI:NTFS chain load solution, I'm just not going to bother and recommend to people who just don't seem to like NTFS chain loading to use whatever method they are happy with.

Or, to put it in clear and simple terms: _I have better things to do than to redesign a solution that both works just fine and is super efficient_.

&rarr; Rejected.
