### ISSUE TITLE
Windows 11 Updates on unsupported hardware

### ISSUE THREAD

**Issue by deepindersinghbti** [pbatard/rufus#1978]
﻿I am planning to create a Windows 11 bootable flash drive for my unsupported PC using Rufus. Will I receive the updates after the upgrade? If no, is there any other workaround to enable updates for unsupported hardware?

**Comment by pbatard** [comment]
> Will I receive the updates after the upgrade?

We've seen nothing that indicates that Microsoft is doing or is planning to do anything special for platforms that don't meet the official system requirements for Windows 11.

At any rate, this is not a Rufus issue. Rufus allows you to bypass the requirements to install Windows if you want. What happens to your installed version of Windows is entirely up to Microsoft because, despite what a lot of people appear to think, Rufus does not actually modify any of the installed Windows binaries.
