### ISSUE TITLE
Suggestion for an unique selling proposition 😄: Allow to inject Drivers

### ISSUE THREAD

**Issue by schittli** [pbatard/rufus#1993]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- n/a I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- n/a The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Issue description
-----------------

**Thank you very much for sharing your great work!**

I have a probably small but very useful suggestion for a feature, which no other USB Tool has 😄:
When starting the Windows installation, it is helpful now and then to load drivers first. For example, many Motherboards have embedded RAID Controllers, but to use them, it's complicated:
1. Download the Drivers
2. Create a separate USB Stick. Hope that you get the right disk format. 
3. Add the Drivers to the USB Stick
4. Boot Windows Setup
5. Manually load the drivers:
6. Select the right Driver and load it
7. Repeat 6. until all Drivers are loaded (AMD RAID needs 3 Drivers...)

Because the Windows Setup automatically recognize and load existing Drivers, it would be great if Rufus would allow this process:
1. The User downloads all required drivers into e.g. `c:\temp\usb-drivers\<one Directory per Driver>`
2. In Rufus, the user presses the "inject drivers" button and selects the Folder: `c:\temp\usb-drivers\`
3. Rufus creates the USB Stick and injects all the Drivers

Thanks a lot, kind regards,
Thomas

**Comment by pbatard** [comment]
> I have a probably small

Not sure what you mean by small, but if you mean "easy to add", I don't think you looked closely at what injecting drivers into a WIM image entails. It's not as simple as copying a bunch of files.

> but very useful suggestion

From your limited point of view, it may be "useful", but for the wider picture of Rufus users, it may not be as useful as you may imagine it is, as my view on this is that not that many people, outside of mostly folks encroached to using Windows 7 (which [I have ceased to support](https://github.com/pbatard/rufus/wiki/FAQ#Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED)), have actually much use to that feature. Also, my understanding is that if you use a recent version of Windows, Intel, AMD and Microsoft have worked together to make support for RAID drivers less painful. Finally, in most of the current software RAID scenarios I know, you wouldn't use software RAID fort the OS drive, but instead use a (non-RAID) SSD, and reserve RAID for a non OS volume, in which case Windows Update will sort you out. So, again, all in all, I am seeing only a limited set of cases where what you describe would actually be that useful...

> for a feature, which no other USB Tool has

Which begs the question: If it really was that much in demand by users, why hasn't anybody bothered to add it?

But let me cut to chase here: Because my goal is to help Windows users as much as I can __as long as the cost of doing so does not outweigh the benefits__ (which basically means there needs to be a large enough number of users that would actually benefit from a feature and warrant the cost of testing and maintaining it in the long run), I have already considered whether I wanted to add such a feature in Rufus, and the answer I came to is that the cost/benefit ratio was simply too high.

As such, I have no plans to add driver injection to Rufus at this stage.

Now, if someone comes up with a scenario where a large percentage of Windows 10 and Windows 11 users are expected to be left stranded because their hardware requires a driver that the Windows 10 and Windows 11 installer does not provide natively (and I'm afraid that your RAID example falls a long way from qualifying for that), I may revise that decision. But until then, I will request that users who need drivers that Windows does not natively provide in order to complete the base installation of the OS look at alternate methods of doing so.

Oh, and you may also want to have a look at [this relevant FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want).

&rarr; Rejected.
