### ISSUE TITLE
Feature request - Create an empty bootable USB drive

### ISSUE THREAD

**Issue by o-l-a-v** [pbatard/rufus#2005]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Issue description
-----------------
I'm requesting the ability to create a bootable USB without any files on it. Then one copy over the files to boot after Rufus is done formatting, creating the partition scheme and target system, which all could be user customizable options in this scenario.

Just to give one scenario where this would be nice: The bootable [Western Digital SSD sanitize tool](https://wddashboarddownloads.wdc.com/wdDashboard/application/EmbeddedLinux.zip) one can download when the WD Dashboard software does not recognize a memory stick.

* The downloaded tool is in a ZIP, not usable with Rufus as is.
  * *A current workaround is to use something like "Folder2Iso" to create a ISO file of the "Img\\**to-esp**" folder.*

**Comment by pbatard** [comment]
The feature you want is already there.

Rufus allows you to create blank FreeDOS, Syslinux, GRUB, Grub4DOS or UEFI:NTFS bootable media, onto which you can copy whatever content you want:
![Image1](https://user-images.githubusercontent.com/1206968/181909205-a2b14f80-9e59-42a9-b62e-5757e326303f.png)

Furthermore, the sanitize tools you mention are UEFI bootable, so you don't need Rufus to do anything special besides formatting a partition to FAT32 (which it will happily do if you select "Non bootable") and then extract the content of `Img/to-esp` onto it.

Most likely here, what you want to do (since there's a `syslinux.cfg` file in the archive) is:
- Create blank Syslinux 6.04 drive using FAT32 as the file system in Rufus
- Extract the content of `Img/to-esp` onto it
As this should give you a dual BIOS+UEFI bootable drive.

Note that, because creating blank bootable media is an advanced feature, you will only be proposed the options after you click _Show advanced drives properties_.

As I believe I have answered your question, I will close this issue.
