### ISSUE TITLE
Enhancement: structure the log text

### ISSUE THREAD

**Issue by GeoDecouvreTout** [pbatard/rufus#2008]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
A simple enhancement could be to structure the log text to highlight the different steps and make it easier to read, using headings, blank lines and separators as in the following example:

```
========================================
  USB device
========================================


========================================
  Image
========================================


----------------------------------------
[1] Format
----------------------------------------


----------------------------------------
[2] Partition
----------------------------------------


----------------------------------------
[3] Extracting files
----------------------------------------


----------------------------------------
[4] End
----------------------------------------


========================================
  USB device
========================================


```

**Comment by pbatard** [comment]
I'm afraid that the log is not destined to be easy to read for users. Even if it may contain some messages that are targeted at folks that __may__ decide to have a look (such as the one that tells them how to enable the listing of a drive that is hidden by Rufus, but please bear in mind that any message that is __actually__ aimed at being reported to the user will be displayed as a UI alert) its purpose is mostly to help me, the developer, analyse issues if something goes wrong.

I hope that you can appreciate that, if you start with what you suggest, then we open the door for every other log "enhancement" on the planet to make it more palatable for the end-user, such as _"I don't understand what this part of the log says, can you please make it more readable for the common user?"_.

I'm afraid I only see a zero or negative benefit in doing what you suggest, so I'm going to have to reject this request. I'm not designing the log so that it is easy to read.
