### ISSUE TITLE
[Feature] updater should (ask to) delete old versions

### ISSUE THREAD

**Issue by thecakeisalie25** [pbatard/rufus#2012]
﻿

Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log. 
- [X] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [X] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
It would be neat if, after using the self-updater, it gave me the option "Launch and delete current version" along side "Launch". That way I don't have to open up my documents folder and delete it manually.

Log
---
```
Rufus x86 v3.18.1877
Windows version: Windows 10 Pro, 64-bit (Build 19044.1865)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
1 device found
Disk type: Removable, Disk size: 4GB, Sector size: 512 bytes
Cylinders: 492, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 2
Disk GUID: {175E4872-FDE5-4E8D-9184-32A1E1E6D490}
Max parts: 128, Start Offset: 17408, Usable = 4047469056 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'MemTest86'
  Detected File System: FAT16
  ID: {9E96933A-A367-42C4-8F6B-0AA7B8AD4A8E}
  Size: 249 MB (261095936 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000004
Partition 2:
  Type: EFI System Partition
  Name: 'EFI System Partition'
  Detected File System: FAT16
  ID: {2B4D37F4-9A96-4C1F-B804-42C3D5705BBF}
  Size: 249.0 MB (261078528 bytes)
  Start Sector: 514048, Attributes: 0x0000000000000000
Checking for Rufus updates...
Checking release channel...
New release version found!
Downloading https://github.com/pbatard/rufus/releases/download/v3.20/rufus-3.20.exe
File length: 1.3 MB
Successfully downloaded 'rufus-3.20.exe'
Download signature is valid ✓
```

**Comment by pbatard** [comment]
I can see where you're coming from, though I'm not sure whether I want to do this, as I don't consider it a major impediment, and there are definitely some people who want to keep the old version (plus it adds a bit of complexity because now we need 2  applications to communicate with one another so that the new version knows that it's being requested to delete the old one).

This means that, if I were to do it at the very least I'd have to add a new checkbox in the upgrade dialog asking the user if they want to delete the old version, and at this stage, because it should be a lot less time consuming to do so, I am not planning to introduce changes to the current dialog layout until I have moved to using XAML Islands for the UI, even for something as minimal as a new checkbox (mostly because the current non XAML way of handling dialogs forces us to manually handle all the various zoom factors and window resizing, and it makes little sense to go through an exercise that we should be able to sidestep once we have XAML).

Now, unfortunately, it'll probably be a couple of years before Rufus switches to an XAML UI. So I will close this issue for now, while taking a note about this request, and once we have an XAML based UI for Rufus, I will decide on whether I want to add it.
