### ISSUE TITLE
WindowsToGo 11 will not shutdown completely.

### ISSUE THREAD

**Issue by changedsoul** [pbatard/rufus#2027]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I do not know if this is normal behavior for a WindowToGo windows 11 USB boot, but my laptop will not fully power down when shutting the system down. It seems to get to a good shutdown state, but something with the external USB makes it never fully power down.
I have to hold the power button down to shut it off.

The light on the USB disk blinks blue when active, and when shutting down, its quite active, but just before the screen goes black, the led turns red, then goes dark, and the laptop "looks like its off" but it not not fully powered down.

**Comment by pineapple63** [comment]
Im not entirely sure, but i know some computers continue to provide power to the USB ports after shutting them down

**Comment by pbatard** [comment]
I'm afraid this is your environment. Nobody else is reporting this, and while testing Windows 11 To Go myself, I've never had issues powering computers down.

From what I gather, you didn't test on any other computer but this specific laptop of yours, so it looks like this is a problem between your laptop and Windows.

Oh and keeping USB ports powered is independent of shutdown state (since shutdown is a CPU state, and you can have a CPU shut down while the computer is still providing power to ports).

Considering that this issue is unlikely to have anything to do with Rufus, I will close it. I would advise you to post on Windows forums or on user forums for your specific brand of laptop.
