### ISSUE TITLE
Your tool cannot download older syslinux files

### ISSUE THREAD

**Issue by ropucyka** [pbatard/rufus#2032]
All they very small size, why not built in program?
And download them manualy not enough, they must be placed to subfolder with fuckin unknow name.

Rufus have problems with downloading them many years (OMG)

fuckin clown

**Comment by pbatard** [comment]
As far as I know, the only users who have an issue with the downloads are ones who use an obsolete non updated OS, such as Windows 7, or who work in a non connected environment. Of course, since you didn't bother to provide a log, I can only guess in which category you might be falling here.

The root of the matter is actually that it would be "clownish" of me to waste my time developing for these environments.

But hey, feel free to throw invectives at the developer of an application that you paid exactly $0 for as if they were your own personal slave, and make sure to __never ever__ attempt to see the situation from their perspective. That's sure to get you very far in life...
