### ISSUE TITLE
Separate checkbox options for TPM & Secure Boot

### ISSUE THREAD

**Issue by monu50** [pbatard/rufus#2034]
Checklist
---------
- [✔] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [✔ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Issue description
-----------------
Rufus provides option to disable TPM and Secure Boot option while creating the bootable USB for Windows 11. For many of the laptops/computers the Secure boot is available but TPM is not, and choosing the option Disable TPM/Secure Boot will disable both and adds 1-2s delay in booting if Secure boot is disabled.

If both these options can work independently like two options in dialog, 1- Disable TPM, 2- Disable Secure Boot will be beneficial for the users who want to only disable TPM checks.

**Comment by pbatard** [comment]
I don't think you realize that "bypass" does not equate "disable".

Bypass means: "If it's available, let the final installation of Windows behave __EXACTLY__ as it would if the feature had not been bypassed. If it's not available, prevent Windows from disabling the installation altogether".

I cannot stress this enough: if you have Secure Boot available, choosing to bypass Secure Boot along TPM does absolutely __nothing different__ with regards to how your installation of Windows would behave if you had two separate options for Secure Boot and TPM and only chose the TPM one.

Therefore, your request is pointless, as you are trying to address a Windows behaviour that does not exist in the first place.

And no, because all the Secure Boot and TPM bypass do is add a registry key that tells the Windows __installer__ (not the final installation of Windows) to proceed in case one of the above is missing, there's no "secret setting" that Microsoft will check in the final installation of Windows to detect whether Secure Boot was bypassed during the installation or not. All the final Windows installation does check is whether they are present on the system or not, which is precisely why, even if the Secure Boot bypass was enabled, if you do have Secure Boot, Windows 11 will have no clue that you did apply the bypass for installation.

&rarr; Rejected
