### ISSUE TITLE
Rufus cannot access my device

### ISSUE THREAD

**Issue by MMMMMoris** [pbatard/rufus#2041]
For no reasons, it just cannot access my hard disk, any one of them, neither the one installed on my laptop, nor the one I have been using. Windows explorer can access it, everything is okay except rufus, I don't know why. The only change I have made to my system is to turn off the switch of using Administrator Authority on every application once I turn on the laptop(actually user account control I guess, translated from Chinese , run all Administrator as permitting)
![image](https://user-images.githubusercontent.com/63332824/189499012-18b86a10-35a1-45f0-ab5e-29a03f8952d1.png)
![image](https://user-images.githubusercontent.com/63332824/189499029-106046f0-b49d-4233-9609-7667811e1e50.png)
![image](https://user-images.githubusercontent.com/63332824/189499052-9a6464c2-5f20-47b6-90ff-8dc5d5d3f160.png)
Anyway ,it doesn't work as the other application do.

**Comment by pbatard** [comment]
Because it will completely erase everything that's on it, Rufus is designed __NOT__ to access internal hard disks.

Only external __USB__ disks, such as flash drives can be accessed, but even then, Rufus will not list large fixed drives by default, to avoid someone erasing a backup drive instead of flash drive by mistake.

If one of the disks above is really a USB drive, and you are okay with __DELETING ALL THE DATA THAT IS ON IT FOREVER__ then you can tell Rufus to list it by following [this entry from the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected).

As I believe I have answered your question, I will close this issue.
