### ISSUE TITLE
Error during installation: DRIVER IRQL NOT LESS OR EQUAL

### ISSUE THREAD

**Issue by mohsen67t** [pbatard/rufus#2043]
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.

Issue description
-----------------
When installing Windows and after choosing the partition for installation, everything went well, the Windows files were copied and the installation was done, and Windows automatically restarted, but I encountered this error in the second step of the installation.

Error: Your PC ran into a problem and needs to restart.
Stop Code: DRIVER IRQL NOT LESS OR EQUAL
What Failed: rt640x64.sys

![photo_2022-09-12_23-48-28](https://user-images.githubusercontent.com/25227960/189737612-63067f4a-0e1a-4512-99bc-40758beebed1.jpg)

**Comment by pineapple63** [comment]
First thing i would do is verify that the ISO you are using is genuine, and has not been modified or gotten corrupted in some way

If you used a media creation tool ISO, then that could be the source of the problem (as i have had strange things happen with media creation tool ISOs)

**Comment by mohsen67t** [comment]
I downloaded this ISO file directly from the Microsoft site

This URL: https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso
File name: Windows11_InsiderPreview_Client_x64_en-us_25197.iso

And I put the ISO file in the flash memory without any manipulation through the Rufus software

![Untitled](https://user-images.githubusercontent.com/25227960/189830200-74a68339-0463-4fb4-8eba-82afb811c421.jpg)

**Comment by pbatard** [comment]
Please post about this issue on a Windows user forum.

Windows installation problems such as this one have nothing to do with Rufus, since Rufus does not alter any files from Windows (not even for the installer).

Therefore, you __will__ encounter the same issue regardless of whether you used Rufus to install Windows or not, which means that this issue should not be reported in the Rufus issue tracker, as you will not obtain the kind of help you are hoping to get, since this is not a Windows installation help forum.

As such I will close this issue as it is off-topic.
