### ISSUE TITLE
Not sure if its bug 

### ISSUE THREAD

**Issue by modz2014** [pbatard/rufus#2045]
Hey I think is a bug between copying files over to usb as I found out with the older version  of refus I was able to burn and boot from usb and install windows 10 but some windows drivers didn't copy over 

I used older version of refus I was able to install  windows 10 properly and nstalled drivers as it was happening on a macbook pro 

I thought I was stuck on windows 7 

I tried different windows 10 iso and still was happening so it can't be the iso image 

I tried another software which I don't like to use and was working fine

Love the Gui easy to find your way around it not like most complicated ones

**Comment by pbatard** [comment]
The log(s), that were requested by the check list would indicate whether Rufus "forgot" to copy files.

Please __DON'T__ assume that the issue you describe should be easy to reproduce, as without the log(s), it's impossible for me to have enough parameters to do so.

So please provided the log(s) that were requested when you opened the issue, as I cannot investigate your issue otherwise.

For the record, considering that such a bug if it existed would be reported by many many people (Rufus is downloaded more than 1 million times ach month), and that the code that extracts the ISO content is exceedingly straightforward and unlikely to miss a file during copy, without further information from you, and especially without the log(s), I have to dismiss your issue as an environmental one.

You should also understand that Windows was never designed to be installed on a Macbook, and that installation issues are exceedingly unlikely to have anything to do with Rufus.
