### ISSUE TITLE
XFAT  Linux

### ISSUE THREAD

**Issue by necrose99** [pbatard/rufus#2056]
﻿https://www.pendrivelinux.com/make-an-exfat-bootable-usb-flash-drive/#:~:text=In%20order%20to%20make%20an,Legacy%20BIOS%20and%20EFI%20booting.  
 hears the pestersome  manual way..  

https://github.com/pbatard/efifs/releases/download/v1.9/exfat_x64.efi  FS driver UEFI is avalible . 

my fav live iso , the has  squashfs creeped to nearly 5 gigs as  squashfs ... most Linux's ntfs maybe  xfat was recently made FOSS
per use case xfat/ntfs is included but i'm not quite sure how well the stick would boot via ntfs..     since itts a Forensics capable rather a toss up of which will work.  
https://cloudblogs.microsoft.com/opensource/2019/08/28/exfat-linux-kernel/ 

GPT boot like Fat32 / xfat primary

**Comment by pbatard** [comment]
I have no idea what you're on about or what you want.

However, you may need to be made aware that UEFI:NTFS, which can be installed by Rufus, does support exFAT as well as NTFS.
So all you have to do is:
* Click _Show advanced drive properties_ if they are not already enabled (this enables _UEFI:NTFS_ to be listed in _Boot selection_)
* Select _UEFI:NTFS_ in _Boot selection_
* Select _exFAT_ as _File system_
* Press _START_
* Copy whatever onto the exFAT partition, which will now be bootable in UEFI mode, provided that you have a relevant UEFI bootloader and support for exFAT in your kernel/init script/whatever.

By the way, you don't have to tell __me__ that _"https://github.com/pbatard/efifs/releases/download/v1.9/exfat_x64.efi FS driver UEFI is avalible"_. I'm the guy who created and published the damn driver there...

Finally, don't expect Rufus to support exFAT alongside NTFS for Linux distros anytime soon, unless you can provide a valid comparitive study that explains why exFAT has huge advantages over NTFS, or why you do expect distros to stop supporting NTFS alongside exFAT if they do support exFAT. Just like I have no plan to add exFAT support to create Windows bootable drive (even though Windows does support exFAT alongside NTFS since Windows 8) when NTFS __is working just fine__, I have no plan to add exFAT support to create Linux bootable drive, when I very much expect that NTFS will work just fine.
