### ISSUE TITLE
Unused variable in uprintf() call

### ISSUE THREAD

**Issue by marcosfrm** [pbatard/rufus#2067]
https://github.com/pbatard/rufus/blob/b2bf29f65263f973d7511212a8b732b019cb98cb/src/wue.c#L784

Unused `wim_index`.

`WIMUnmountImage()` will print WIM index anyway.

**Comment by pbatard** [comment]
That's not unused. Unused would be if we set that variable and didn't pass it to any call, which is very much __not__ the case here.

Also, please bear in mind that `WIMUnmountImage()` may fail, which is the precise reason why we want to to print the index, so that the user (or the developer of the app ;)) gets an idea about what WIM index caused the issue during unmount.

I could also elaborate on why we see it better to print the index in the message we output before we enter a call that might fail, rather than with each error message in the call that fails...

&rarr; Rejected as "not an actual unused variable" (but please don't let that discourage you from looking at the code, coz there are most likely things in there that I overlooked and that could definitely be improved).

**Comment by marcosfrm** [comment]
Unused in the `uprintf()` call: there's no `%d` specifier...

**Comment by pbatard** [comment]
Oh, I missed that - you're absolutely right. I'll fix it!

**Comment by pbatard** [comment]
Stealth actual commit that closes this is cee21b1981c8c621fae33892c16fac25e748a0c3 because mistyped in your name in the part where I thanked you in the previous one (D'OH!).

**Comment by marcosfrm** [comment]
:) thanks.
