### ISSUE TITLE
What is the benefit of stopping Windows 7 support?

### ISSUE THREAD

**Issue by top31** [pbatard/rufus#2081]
What do you gain from stopping Windows 7 support?
I can't upgrade My device is not compatible with Windows 8.1 + 10 + 11
What do you think should I delete rufus now or what

- [ ] Actively prevent Rufus from running on Windows 7 (It's been 3 years since EOL: LET IT GO!. Plus, it'll still be better than what happened with XP, where we couldn't even produce an incompatible platform message at launch...)

**Comment by pbatard** [comment]
> What do you gain from stopping Windows 7 support?

Time, better maintainability, and not having to deal with __entitled__ people.
Obsolete systems do hold development back. For instance, having to support an obsolete system like Windows 7 is directly responsible for adding complexity in handling partitioning, formatting, UI, Windows To Go, and so on, and it's never as simple to handle as `if not Windows 7 then`. Also, I'm no longer going around maintaining Windows 7 platforms just so I can test stuff.

Pas experience with Windows XP users, and their own form of entitlement, have also very clearly demonstrated that, as a developer, I have absolutely nothing to gain in trying to support systems that have been retired by Microsoft longer than I should, because almost every interaction I had with obsolete OS users was of the same kind as yours, with folks under the impression that, because I am providing an application for free, it _must_ mean that my time is also free and that I have nothing better to do than support an obsolete OS for them.

You are free to use Windows 7 if you wish, and I am not going to delete old versions of Rufus that should work there.
But you are not __entitled__ to force developers to support Windows 7 forever and I am actually trying to set up a clear watershed to __HELP__ users who are still running Windows 7, so that they get a clear indication that they will need to use an older version of Rufus for their platform, to __AVOID__ what happened with Windows XP, where the application suddenly stopped being able to launch at all (because even sorting out an application that can launch and display a simple error message on an obsolete system can be an issue), and they were let without a clue as to what you should do.

Now, to the brutally honest, if you are using Rufus on Windows 7 and are going to create issues to berate the developer for planning to add a message that simply duplicates [what we are already explicitly stating in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED), then, yes, I'd much rather you deleted Rufus and never contact me again.
