### ISSUE TITLE
I found a same name app.

### ISSUE THREAD

**Issue by SungHerobrine97** [pbatard/rufus#2092]
https://play.google.com/store/apps/details?id=com.mixapplications.rufus&pli=1

Hey,I'm MixerWangDev.

I found an application with the same name, but I don't know if it is an official application.

It's a [link for check](https://play.google.com/store/apps/details?id=com.mixapplications.rufus&pli=1)

**Comment by pbatard** [comment]
Well, they state pretty explicitly on the link you pointed to:

> Note: this is an unofficial app.

So that's your answer there. Also see [this entry from the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Do_you_plan_to_port_Rufus_to_LinuxMac_OSSome_other_OS).

I'm fine with people trying to create derivative work from Rufus since it's Open Source, but if they do, I would expect a developer not to try to hijack the name "Rufus" as well as the icon to trick users into thinking that this is affiliated in any way with the actual Rufus application. So, clearly they are trying to trick users into thinking that this is direct derivative work that we approved, whereas it isn't, and I have therefore reported them to Google for [impersonation](https://support.google.com/googleplay/android-developer/answer/9888374).

Thanks for letting me know about this. I will close this issue now, as it is now in Google's hands,
