### ISSUE TITLE
Rufus device format warning example

### ISSUE THREAD

**Issue by StereoVision** [pbatard/rufus#2095]
This morning I have erased involuntarily all my data on my 64GB SD card. Clips, radio technical books, folklore music, all of them was formatted.
It's my wrong.
But I want share with you my experience about program of this kind.
Last year I was experiment with bootstrap records. And I wrote some little unofficial programs for 16-bit DOS. I will attach picture from one of them. It works fine, but I can't do it for flash memories. I hope to see Rufus works with this or at least similar protection level like on the picture.
https://ibb.co/Pc4kgm8
Thank you before hand.

![MBR-boot](https://user-images.githubusercontent.com/7265752/204128184-dce4e53b-f3c0-444a-93a2-3afa53fea976.jpg)

**Comment by pbatard** [comment]
Rufus already has tons of protections to prevent people erasing the media they don't want.

For one thing, we don't list large drives or USB HDDs by default.
And it lists drives in order of size, which means that a backup drive, which is usually expected to be larger than anything you would typically use to create a bootable drive, will not be selected first.
Also, since you're pointing to your own little "protector", you probably understand that there is no universal way to protect a drive in Windows, and I am definitely not going to ask people, who might be creating drives day in and day out, to type the LABEL or add some extra step that, when things are considered logically, are going to be massively annoying.
Also, and since you are talking labels, this is the part that you should really have been paying attention to, Rufus does display a very prominent message __WITH THE LABEL OF THE DRIVE IT IS GOING TO FORMAT IF IT HAS ONE__, that should have given you a clear hint that you were about to format the wrong drive. For instance, if you had labelled your SD card `My Backup Drive [***DO NOT FORMAT!***]` this is what you would have seen in Rufus:
![Image1](https://user-images.githubusercontent.com/1206968/204134324-3eb0120a-f81a-45c8-8dad-b5bc6cf1099a.png)
And the label of the drive is also prominently displayed in the _Device_ dropdown, for even more means to avoid the mistake you just describe:
![Image3](https://user-images.githubusercontent.com/1206968/204134427-28e7b91c-a5c6-48fd-9501-065cb52f711d.png)
So, really, instead of asking every purveyor of an application that can format a drive to add convoluted extra protection schemes, all you had to do, even without changing the label, was create an `autorun.inf` at the top of your drive with something like:
```
[autorun]
label = My Backup Drive [***DO NOT FORMAT!***]
```
so that Rufus (and other utilities) display a big hint to remind you that the drive you have selected is the wrong one.

Finally, and I cannot stress this enough, using an SD card alone for backing up data means that you don't actually care about this data, because SD cards are the actual worst media in terms of reliability, and have such a rate of failure that you should __ALWAYS__ consider that it's going to fail tomorrow. So, if you didn't keep a separate backup of the data you had on that SD card, that loss is really entirely on you because it was bound to happen one way or another.
