### ISSUE TITLE
[Question] - Renaming Already Recorded Image On Flash Drive by Rufus?

### ISSUE THREAD

**Issue by RemixPL1994** [pbatard/rufus#2101]
Hello, I am interested in something.

For example, I am recording the image of Ubuntu v14.04 LTS Triumphalna-Turtledove and Trusty-Tahr on a pendrive and when I load the image and select the pendrive on which it is to be recorded, in "Volume Name" Triumfalna Turtledove 14.04.1PL is shown.

Triumfalna Turkawka 14.04.1PL is the original name and if I do not change it, after recording this name is visible in the file explorer in the system.

I can change this name to another and call it, for example, Ubuntu v14.04 LTS - x32, and this name will also be displayed correctly in the end after recording the image on a flash drive.

But originally when I want to change the name of the device / image straight from the system file explorer, there is a character limit because the image was recorded in FAT32 with MBR.

And the maximum I can enter is UBUNTU-X32 because more characters are blocked / not supported. And all characters must be capitalized.

My question is this. Can I use Rufus to change only the name of the already recorded image to, for example, change the name from UBUNTU-X32 to, for example, Ubuntu v14.04 LTS - x32, i.e. separately uppercase and lowercase letters and a larger number of characters than originally supported when changing directly from system?

If Rufus doesn't have the option to change just the name, is there any other system-level way to do this?

I already tried renaming with Unlocker v1.9.2 and IObit Unlocker v1.3.0 and it still doesn't help.

I know that this question is not specifically addressed to Rufus, but maybe, as the author of this software, you know a way or another program, a tool that allows you to change the name of an already recorded image to anything you want without the default / original limit?

Sometimes, for example, I will record an image with the original name as Vistax322022 and I would like to change this name to another more accurate one and it is impossible to do it / I can't do it from the system level.

The only way I know is to re-record the image in Rufus and enter the new correct name, but the recording of a new image takes longer than just a quick name change, especially if I have several flash drives where I would like to sign them differently.

Or maybe it would be possible to add an option to Rufus like rename image / reload image name on current recorded image and device?

Thank you very much in advance for answering.

**Comment by pbatard** [comment]
On Windows, the way you get File Explorer to display a name that is not constrained by the limitations of the file system (such as 11 UPPERCASE characters for FAT32) is through `autorun.inf`.

That's how Rufus manages to have Windows file explorer display `Triumfalna Turtledove 14.04.1PL` even though the __actual__ volume name for the partition was set to `TRIUMFALNA_` due to the FAT32 limitation.

In short, you can have File Explorer display whatever label you want (including international characters, or very long labels) by simply creating a `autorun.inf` text file at the top of the drive with something like:
```
[autorun]
label = Ubuntu v14.04 LTS - x32
```
Then File explorer will display that name instead of the volume name (note that it may require restarting Explorer... or the computer before that happens).

See also https://github.com/pbatard/rufus/wiki/FAQ#why-does-rufus-create-an-autoruninf-file-isnt-that-dangerous

As I believe I answered your question, I will close this issue.
