### ISSUE TITLE
Rufus Error: Access to the device is denied [0x00000005]

### ISSUE THREAD

**Issue by kangarooo** [pbatard/rufus#2131]
Rufus Error: Access to the device is denied [0x00000005]

Solution- Make such messege: that maybe Windows 10's Ransomware Protection, and need to disable it for usage of Rufus.

It is supposed to prevent encryption of personal files (mostly to extort money), so it seems to prevent low-level access to drives.

To check and disable it in Windows 10, go to the Windows Settings (The cog wheel in the Start Menu), then to "Updates and Security", "Windows Security" (on the left), "Virus protection". Then at the bottom, there is "Ransomware protection". Click on it, then turn off "Controlled folder access". (This of course leaves your files vulnerable, should there be undetected Ransomware on your machine, but you have a backup anyway, don't you?)

https://www.winhelponline.com/blog/rufus-error-access-device-denied-0x00000005/

https://superuser.com/questions/1538716/can-not-create-a-bootable-usb-in-windows-10-access-denied

**Comment by pbatard** [comment]
Or, you know, maybe invite people who open an issue to go through a checklist that asks them to read the FAQ, where there is an [specific entry for this](https://github.com/pbatard/rufus/wiki/FAQ#error-0x00000005-access-is-denied) that does __explicitly__ mention _Controlled Folder Access_.

Please also understand that I cannot make an error message mention all the software that can cause error 0x00000005, because there is simply [way too many of these](https://github.com/pbatard/rufus/wiki/FAQ#incompatible-software).

Next time, please follow the check list because it is very much there for the 99.9% of people who __erroneously believe__ that the check list does not apply to them.
