### ISSUE TITLE
Can't select FAT32 format in dialog box (trying to create bootable Win USB for Bootcamp)

### ISSUE THREAD

**Issue by plastikfan** [pbatard/rufus#2132]
﻿

Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
As title says, the only option in the format drop down is NTFS. However, using NTFS for the format can not work for bootcamp as macOS can't not write to an NTFS drive when trying to download the windows support software (drivers). I have tried using a separate FAT32 usb stick just for the support sofware but the support software MUST be on the same usb stick as the bootable ISO otherwise the apple bootcamp software does not recognise the fact that the ISO is on 1 usb and the support software is no another. They must all be on the same drive, which means it has to be FAT32.

I can see from screen shots that FAT32 can be used, but how do I make this option available? It is not in the dropdown, only NTFS is.

I am using version 3.21.1949 of rufus:

![rufus win10-22h2 WRONG](https://user-images.githubusercontent.com/49785914/211918169-aa9d03f2-601d-4977-abd1-a033eb812a8e.jpg)

macOS version: big sur
windows version: win10-22h2

I couldn't find anymore info in your wiki, so raising this issue is a last resort.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
FAT32 cannot be used with recent versions of Windows ISOs because they contain a file that is larger than 4 GB, and the maximum size for files that can be written onto a FAT32 media is 4 GB. This is a limitation of the FAT32 specs (so it is not possible to work around it).

Considering that Rufus is a Windows applications and therefore that you have access to a Windows platform, I would suggest that you inject the drivers/support software there, __especially__ as, if actual injection is needed, then I strongly doubt that the Apple folks implemented the whole __Windows specific APIs__ that allow one to actually _inject_ drivers into a Windows `.wim` image (because that would be a lot of time and money spent duplicating Windows software for very little benefit). Plus, considering that the >4 GB issue has been relevant since Windows 10, I would expect people to have reported a similar problem to yours a long time ago.

Moreover, looking at https://support.apple.com/en-ie/HT204923 as well as https://support.apple.com/en-gb/HT201468, which are the official Apple page that relates to installing Windows in bootcamp, it doesn't look like the Windows installation media needs to be modified in the slightest to be able to install Windows, and rather, it is only once Windows has been installed onto the target bootcamp partition that Apple will install the necessary drivers (but that'll be on the bootcamp installation partition, __not__ on the installation media). Especially, I refer to this:

> After Windows installation completes, your Mac starts up in Windows and opens a ”Welcome to the Boot Camp installer” window. Follow the onscreen instructions to install Boot Camp and Windows support software (drivers). You will be asked to restart when done.

Which seems to further my point that it's only after Windows have been installed, from a standard unmodified media, that the Windows support software will be installed.

Furthermore, the  __official__ Windows installation process documented by Apple also appear to indicate that you don't need to create a USB bootable media using a third party, but instead should simply point the BootCamp assistant to a Windows __ISO__:

> A 64-bit version of Windows 10 Home or Windows 10 Pro on a disk image (ISO) or other installation media. If installing Windows on your Mac for the first time, this must be a full version of Windows, not an upgrade.
>
> *  If your copy of Windows came on a USB flash drive, or you have a Windows product key and no installation disc, [download a Windows 10 disk image from Microsoft](http://www.microsoft.com/en-us/software-download/windows10ISO).
> *  If your copy of Windows came on a DVD, you might need to [create a disk image](https://support.apple.com/en-gb/HT203909) of that DVD.

In short, it looks like you are not following the official installation instructions, and instead are following to what you __think__ the installation should entail, and are running into imaginary issues because of this.

Still, if you __really__ want to waste your time into trying to inject files from Mac onto a Windows installation media that was created by Rufus, here's what you can do:
1. In Rufus click on "Show advanced drive properties". This will display some more UI elements and, more importantly, grant you access to more boot options in the "Boot selection" menu
2. In "Boot selection" choose "UEFI:NTFS"
3. In "File system", choose "exFAT" (since, unlike NTFS, exFAT should be natively supported by Mac OS).
4. Click START and let Rufus do its job
5. You'll noticed that you did __not__ select an ISO in Rufus. This is normal for this process. Now, you need to pick your Windows ISO, mount it or open it with something like 7-zip and extract the full content of the ISO onto the USB drive you just created.
6. You now have a Windows installation media that you can modify from Mac as you requested. However, this is as far as I will help you with this, so if you have a follow up, you will have to ask them on Apple forums, as Rufus is __NOT__ designed to help people install Windows on anything else than hardware that has actually been designed to install Windows (meaning, coming from a manufacturer that doesn't believe that they are above being bothered to follow __OPEN__ standards like UEFI, ACPI and whatnot).

As I believe I have answered your question, I will close this issue.
