### ISSUE TITLE
Alleged boot issues with media that have a boot parition larger than 32 GB

### ISSUE THREAD

**Issue by mikko70** [pbatard/rufus#2154]
I want do request to  improve program.

i hope option make only necessary size usb-stick.
Nowadays sticks come bigger and bigger. Too huge stick size can cause problems to work correct in some systems.
I think if Rufus can do example 64GB stick with 10GB image  16GB stick and all extra size go in unused area.
It is possible do afterwards with partition manager, but i think it is fine if Rufus can do it with select option.

**Comment by pbatard** [comment]
> Too huge stick size can cause problems to work correct in some systems.

Do you have verifiable examples of that. Coz it looks to me like, if this is true, is up to the manufacturer of the BIOS/UEFI firmware to fix this, especially as, in the case of UEFI, they would be in clear breach of the UEFI specs.

As I hope you can appreciate, I don't addressing "hear and say" issues, because it's both a complete waste of time and impossible to validate. So unless you can provide an example that I can investigate, I'm going to pass on this.

The other problem is that if I were to do what you suggest, I'd have to decide of a cut-off (who's to say that 10 GB is fine and 64 GB isn't? How can this even be validated?) and answer a number of puzzled users wondering why their XY GB drive is not showing XY GB after formatting with Rufus. So this would have to be a cheat mode... which would probably not be that helpful.

So, I'm going to need a heck of a lot more of information about this alleged issue, as well as verifiable examples of systems that are being affected.

**Comment by marcosfrm** [comment]
Have you tried "Add fixes for old BIOSes"? Some very old Award BIOSes (not UEFI at all) from 2006~2008 only work with it enabled.

For _prior art_, Microsoft's Media Creation Tool always limits the partition size to 32 GB, leaving the remaining space unpartitioned. **But** it only supports FAT32...

**Comment by pbatard** [comment]
> For _prior art_, Microsoft's Media Creation Tool always limits the partition size to 32 GB

That's fine but that still doesn't provide me with real-life examples of hardware having an the issue OP alleges exists.
