### ISSUE TITLE
No Extended Windows 11 Installation Image option in Rufus when selected Win11_22H2_xxxxx_x64.iso

### ISSUE THREAD

**Issue by rtek1000** [pbatard/rufus#2172]
I noticed that Rufus can run on Linux, **_but it depends on Windows to be used._**

The "[media creation tool](https://www.microsoft.com/en-gb/software-download/windows11)" is an executable program for windows: "[mediacreationtool.exe](https://go.microsoft.com/fwlink/?linkid=2156295)"

In the [issue](https://github.com/pbatard/rufus/issues/2049) (linked), they said that it is necessary to create the ISO using this tool

> Created iso with the media creation tool 4.15GB. Shows the extended image option.

But there is alternative to download the ISO directly.

What's the difference between these two ways to get the ISO?

Is there no way for Rufus to recognize the downloaded ISO directly?

Reference: https://www.digitalcitizen.life/install-windows-11-unsupported-hardware/

**Comment by pbatard** [comment]
> I noticed that Rufus can run on Linux

I'm not sure how you noticed that, because Rufus certainly cannot run on Linux.

You may be able to _partially_ launch the UI in WINE, but, because WINE is missing 90% of the Windows APIs calls we need, it won't be able to list any devices, or format them, or do anything.

So, **NO**, Rufus cannot run on Linux.

> ***but it depends on Windows to be used.***

Rufus is a Windows application only. If you attempt to run it on Linux, you are 100% on your own.

> What's the difference between these two ways to get the ISO?

Explained here: https://github.com/pbatard/rufus/wiki/FAQ#how-can-i-validate-that-a-windows-iso-is-a-genuine-retail-version

The MCT ISO is a reconstructed image that is **different** every time you run the application. This means that you can never be sure that it hasn't been modified or isn't corrupted.
On the other hand, the retail ISOs are the same for everyone, and are very easy to check for corruption or alterations.
Rufus allows the download of **retail** ISOs, and downloads them directly from Microsoft, as if you were visiting https://www.microsoft.com/en-US/software-download/windows11.

> Is there no way for Rufus to recognize the downloaded ISO directly?

If you use a retail ISO, and you have validated that it has not been altered (by checking its SAH-1) **and are running Rufus on a supported platform** (which currently means Windows 8.1 or later &mdash; Windows 7 is no longer supported and will not have the Windows User Experience dialog), then Rufus will have no trouble working with your ISO.
