### ISSUE TITLE
Ok, that was actually a better advise than it might seem.

### ISSUE THREAD

**Issue by Amar15878** [pbatard/rufus#2177]
Ok, that was actually a better advise than it might seem. 
The log gave me the answer.
Thanks for your time.

_Originally posted by @te0k in https://github.com/pbatard/rufus/issues/134#issuecomment-112147939_
            how exactly did you solved it?

**Comment by pbatard** [comment]
@Amar15878, how about you post your own log so that we can help you.

The reason why people of #134 managed to get help is they actually posted a log, instead of expecting that somebody would be able to _guess_ whatever issue they were having.

It's IMPOSSIBLE to help someone who refuses to provide enough data.

**Comment by pbatard** [comment]
No log &rarr; Closed.
