### ISSUE TITLE
Feature request: add option to disable creation of additional 1MB UEFI NTFS compatibility volume

### ISSUE THREAD

**Issue by Arkadiumx** [pbatard/rufus#2185]
Hi, firstly, apologies if this is the wrong place to submit a feature request, I'm not very familiar with how GitHub works. I just use it to make gists.

My UEFI Firmware has support for bootable NTFS, as most modern hardware does, so it would be a very nice addition to add a tick box like "disable NTFS compatibility volume". 

Thank you for your work! <3

**Comment by pbatard** [comment]
Not gonna happen since there is no reliable way to tell if you're going to need it or not, and I don't want users who do need it to be able to disable it by mistake.

Plus, I do consider that if you are annoyed to see a 1 MB extra partition on a media that you will most likely be using only once, and that has no negative effect whatsoever, it's really your problem, because it shouldn't be up to software that address your irrational annoyances with something that, again, has no other negative effect but to use 1 MB on your drive.
