### ISSUE TITLE
Rufus selecting cancle button on default.

### ISSUE THREAD

**Issue by donotprikel231** [pbatard/rufus#2189]
The resaon im posting this is because what rufus is doing is an issue with me and maby others. I want a confermation before cancaling an operation because i had a 10 GB iso flashing to my drive and i wen to check it was around 46 hours into flashing and at 95% and when i pressed enter after im thinking i click on another window it cancied the operation and now im forced to restart the Painstaking time wasting again. I want a fix to this Please.

**Comment by pbatard** [comment]
I think the main issue here is that you are using hardware that's unsuitable for your task. If it takes 2 days to write 10 GB to a USB flash drive, clearly you should invest in a faster drive and faster hardware.

Or, if that is not achievable, then please don't expect developers to add workarounds that are only there because your hardware or environment are ill suited for the task you are trying to accomplish.

As a developer of an application that you get entirely for free, I'm afraid I don't have time to spare to compensate for the use of low end environment, in the exact same manner as I am no longer supporting obsolete environments like Windows 7 or Windows XP. You can still **try** to use Rufus there, but please don't expect anyone to support you if you do.

&rarr; Rejected, especially on account that, if I were to add what you wish, I'd get grievance from people who are actually using hardware that's properly suited for the job complaining that having to confirm twice if they want to cancel is both an annoyance and a waste of their time.
