### ISSUE TITLE
New releases (Builds) of W11 Pro (March 2023) do not accept extra Rufus settings

### ISSUE THREAD

**Issue by rcqs88** [pbatard/rufus#2224]
Issue description
-----------------
The latests Rufus version is used. Issue happens with the W11 March 2023 builds

Tried several times: 
with the new Windows 11 release [like Windows 11 Professional (22H2) 64bit Dutch Build 22621 1485 (release end March 2023)]

The problem are the extra Rufus option you have while creating a Boot W11 install USB drive.

None of the extra option (like: use a local account; etc.) are accepted and the W11 installation gives an error and stops. 

This happens after the first reboot of the installation; then after a while a message like following does appear (translated from Dutch):
...'error in "antwoordbestand" for installation cannot Parse for fase [specialize] at MS deployment'...

Both W11 Pro builds released by MS in March 2023 do this; earlier W11 Pro (Dutch) release (like from Nov. 2022) have no issue and install completes even with all extra Rufus options used. 

When none extra options are used the install will complete and W11 will work.

Problem is also that it does not do this on every laptop (which is very strange). 
But I had the same issue on a (very new) Acer and a Lenovo laptop.

It seems MS is messing around in the slipstream/mrp files changed by Rufus (when extra options are used). 

I hope Rufus developers find the issue soon.
Regards,
RCQS88

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
Well, I'd like to look into this, but my issue is that I don't have access to retail March build ISOs, since these are not accessible to the general public.

So I'll have to close this issue and wait for either the 23H2 release or a Windows 11 refresh that happens before that, and that produces public ISOs that I can actually have access to.

Now, if you can provide an official public link to a Windows 11 ISO that exhibits the issue, I might reopen this issue, but until then, I simply can't look into it.
