### ISSUE TITLE
[Feature Suggestion] Internal Hard Drive Select Option

### ISSUE THREAD

**Issue by XSpark0** [pbatard/rufus#2266]
Under Advanced Drive Properties, i would like to see an Option for "List Internal Hard Drives". Currently i only see "List USB Hard Drives" option.

"List Internal Hard Drives" option would be very useful for when using "Windows To Go" option. 

I would be then able to install Windows 10 or 11 to Blank Internal Hard Drive Partition, uncheck "Prevent Windows To Go from accessing internal disks" and then i can just reboot and boot straight to clean install by hitting F10 on keyboard and then selecting the hard drive i just installed "Windows To Go" on. 

I wont have to go through the hassle of going through Windows Setup thing and also wont have to go to buy USB adapter for Internal Hard Drive. Windows setup would be quicker than normal and silent to install with "List Internal Hard Drives" option.

**Comment by pbatard** [comment]
Too dangerous and will likely lead to loss of data that, even we can pin the blame squarely on the user, will be the source of arguments. The problem is that, as soon as users become aware that there is an option that lists more drive, and if, for any reason, they don't see their external drives, they will try said cheat mode and end up formatting an internal drive with valuable data by mistake.

The best you are ever going to get in Rufus is the <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>F</kbd> **TOTALLY UNSUPPORTED** cheat mode, that *may* list SATA drives that have the hotplug attribute set (which is something you *may* be able to set in your BIOS depending on what BIOS you have). If you do try this cheat mode, you are entirely on your own however, and, again, if this is not what you want, then I will kindly ask that you use a different application.
