### ISSUE TITLE
Simple Question not an issue feel free to close it when you reply

### ISSUE THREAD

**Issue by willzyx-hub** [pbatard/rufus#2283]
Hi Bro, i wanna to ask how did you get Verified Publisher when your cert doesn't even Installed on the Windows itself ?

Edit : I mean how did you sign it ?

**Comment by pbatard** [comment]
I purchased a very expensive [EV code signing certificate](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage#get-or-renew-a-code-signing-certificate) since that's the certificate you need to be able to get UEFI bootloaders signed for Secure Boot.

And, sadly, as is the case with almost anything, the more you look like you're wealthy, the more people and companies say they will trust you...

**Comment by willzyx-hub** [comment]
> I purchased a very expensive [EV code signing certificate](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage#get-or-renew-a-code-signing-certificate) since that's the certificate you need to be able to get UEFI bootloaders signed for Secure Boot.
> 
> And, sadly, as is the case with almost anything, the more you look like you're wealthy, the more people and companies say they will trust you...

Btw if there is any Free Alternative, to make the .exe and Bootloader signed ? I signed with my Free Digicert certificate but it only get Verified Publisher only if the cert is Installed on the system.
