### ISSUE TITLE
(4.2.2074) Missing password expire flag when auto creating user

### ISSUE THREAD

**Issue by nex86** [pbatard/rufus#2298]
I'm not sure if this is intented that the password expires on first boot so you can set your own password,
but if not, the flag "PasswordExpires=FALSE" is missing here.

Just wanted to point this out.

**Comment by pbatard** [comment]
it is intented that the password expires on first boot so that users are forced to set a password.

That's why we issue `net user "<USERNAME>" /logonpasswordchg:yes` on first boot as well per https://github.com/pbatard/rufus/blob/master/src/wue.c#L174-L180.

So we don't want `PasswordExpires=FALSE`.
