### ISSUE TITLE
Lost all my data lol

### ISSUE THREAD

**Issue by user18081972** [pbatard/rufus#2305]
Sorry gonna ignore the format, dont care if you ban me or whatever. had a rough day.

Just wanted to say:
Why does Rufus show mounted VHDs as if they are just regular flash drives?
Rufus normally never shows internal disks, and a mounted VHD is pretty close to just an internal disk.

I suggest they only show up if you check "List USB drives" or something.

(I know its my fault btw, i should have checked, it gives a warning message no less)
I just always went under the assumption that without checking "List USB Drives" it would never show anything but flash drives.

**Comment by pbatard** [comment]
> Why does Rufus show mounted VHDs as if they are just regular flash drives?

Because a lot of people use it for testing or for create __transient__ images.

From my point of view, VHDs are ill suited to store important data, because you are multiplying the potential points of failure (one with VHD corruption and one with corruption of the underlying disk on which the VHD reside). As such, I consider that VHDs are fair game to be treated as transient removable drives and therefore Rufus lists them by default.

You should also know that Rufus should list drives in the order of size, starting with the smallest, which means that, in most cases, people who insist on using VHD to store data they want to preserve should still be mostly safe from formatting the wrong drive, as one can expect their USB drive to be smaller than their VHD.

Rufus does make some effort to avoid having people formatting the wrong drive by mistake. But there's only so far we can go without these efforts becoming a __major__ annoyance to users. So that's why VHDs are listed by default, and, as with anything, it is up to you to pay attention to the drive you format, and learn a valuable lesson if you do happen to format the wrong drive by mistake.
