### ISSUE TITLE
Winget rufus not available?

### ISSUE THREAD

**Issue by romulasry** [pbatard/rufus#2311]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I can't find Rufus in the cmd winget install would be nice to have it there. Just a thought. Thanks in advance for your time.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
I'll think about it, but, to be fair, since we're already publishing Rufus on the Microsoft Store and the steps to produce each new release have [become a major time sink that can't be easily automated](https://gist.github.com/pbatard/c0230e82d9d0227196c42813747f6237), I'm not sure I want to add an extra step in there every time I publish a new version.

Especially, I obviously want winget to handle all the archs.

So this will strongly depend on whether I (or somebody else) can produce a one-click-no-input-needed script that can produce a winget package.

At this stage, considering that I don't expect that many people to use winget for Rufus, and since Rufus is a self contained executable anyway, I'm going to defer this request until I decide whether I want to produce a winget package or not.
