### ISSUE TITLE
Have issue with Rufus burning Windows 10 22H2 to USB memory stick.

### ISSUE THREAD

**Issue by Apache060** [pbatard/rufus#2313]
Hello,

hope someone can help me I have been using Rufus for sometime, I use version 3.19 and it works fine, but now I have the following issue after Rufus burned the Windows 10 22H2 ISO to memory stick and I tried to boot from the memory stick the following error message appeared on the screen the message says that Rufus have made a recovery and cannot boot from the memory stick.

Any help would be appreciated 

thanks

**Comment by pbatard** [comment]
I'm afraid your issue is very unclear, as you do not reveal the __exact__ message you are getting when trying to boot.

There is no such thing as _"Rufus have made a recovery and cannot boot from the memory stick"_, so I am going to __assume__ that your issue is [THIS](https://github.com/pbatard/rufus/wiki/FAQ#user-content-ERROR_BIOSLEGACY_BOOT_OF_UEFIONLY_MEDIA) in which case you need to follow the advice given on the screen or in the FAQ entry.
