### ISSUE TITLE
rufus Unable to recognize modern SSD USB drives

### ISSUE THREAD

**Issue by LoopholesInTheHeart** [pbatard/rufus#2321]
I purchased a large capacity USB flash drive online, which is different from traditional USB flash drives and uses the same process as SSD.
The link to the product is https://item.jd.com/100040789478.html
On my computer, it is recognized as a disk drive and cannot be recognized by Rufus
As an example, on my computer, their attributes are
<img width="724" alt="jeGb2iPvIo" src="https://github.com/pbatard/rufus/assets/20888477/f6f2767e-6764-48fc-8628-e750c9a5a892">
In Windows Device Manager and Disk Management, it looks like this

<img width="858" alt="bZs0H7IlPL" src="https://github.com/pbatard/rufus/assets/20888477/3a457020-bb61-41ed-a70f-5ab04fc9c838">

**Comment by LoopholesInTheHeart** [comment]
Some Chinese translations in the window
可移动 -> removable, This is a removable mobile device
基本 -> basic, generic device, in this case, might mean unpluggable, like system disk0
in the right window
磁盘驱动器 -> Disk drive,Similar to a hard disk, it indicates the storage medium

**Comment by pineapple63** [comment]
You will need to enable List USB Hard Drives, which is found under the advanced drive properties section

**Comment by pbatard** [comment]
It's probably UASP, but as long as it's USB, Rufus should be able to access it without problem.

But since it's detected as an external large disk/HDD/SSD, Rufus will not list it by default, and you need to enable it as @pineapple63 mentioned. See https://github.com/pbatard/rufus/wiki/FAQ#user-content-Help_my_USB_drive_is_not_detected.

Considering that I am pretty sure this will answer your question, I will close this issue.
