### ISSUE TITLE
Flash drive vanished

### ISSUE THREAD

**Issue by GeorgyTrubetskoy** [pbatard/rufus#2323]
After burning ISO image on the flash drive on the computer and formatting it for another work, the flash drive is vanish after connecting it to computer. It is not visible in the file system, but it visible in the disk manager. 
The developers are irresponsible people who didn't test it properly.

**Comment by pbatard** [comment]
> It is not visible in the file system

That's because __Windows__ can only display the content of Windows file systems, and it will not display Linux file systems.

> The developers are irresponsible people who didn't test it properly.

Next time, please test whether your drive actually boots, before wrongly assuming that because you can't see its content from Windows, it will not work.

There are literally thousands of file systems, and each OS will only support a few, so you will __always__ find a way to create a perfectly working bootable drive that whatever OS you use won't list the content of.
