### ISSUE TITLE
Rufus windows feature menu is not appearing on latest windows 11 downloaded from official website today 06-oct-2023   | --> (Win11_22H2_EnglishInternational_x64v2)

### ISSUE THREAD

**Issue by 1Syeds786** [pbatard/rufus#2334]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
As of today, 2023.10.06, Win11_22H2 is__still__ the old 22H2 v2 that was released in May of this year. Microsoft has not yet updated their website to start distributing 23H2.

Therefore, it doesn't matter if you downloaded the ISO today or in May, and your issue has nothing to do with the date of the download (Microsoft does __not__ secretly update theirs ISOs because that would break the well knows SHA-1... which, incidentally, you were asked to provide).

So, let me start by stating that the Windows User Experience dialog appears for me and for pretty much everybody else that uses the official ISO.

Therefore, since you __chose__ not to provide a log, despite being explicitly being asked to do so, I'm going to have no choice but to make __assumptions__ about your environment and why, on your specific environment, you don't get to see the dialog.

So, without further ado, I'm going to assume that you are running Rufus on Windows 7, where you will never see the dialog, and close this issue.

Next time, if you actually want to receive help, please follow the guidelines, because they are here to help YOU!
