### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by maddin200** [pbatard/rufus#2338]
/src/syslinux/win/ntfssect.c:132
Code:
    return ERROR_SUCCESS;
    CloseHandle(VolumeInfo->Handle); // <-- unreachable
    err_handle:
    return rc;
  }

**Comment by pbatard** [comment]
Syslinux project issue. See https://repo.or.cz/syslinux.git/blob/HEAD:/win/ntfssect.c.

Can you please report this to the Syslinux mailing list? Because there is not much point in doing anything in Rufus if the parent project isn't patched in the first place and as far as possible, we prefer picking up fixes from upstream.
