### ISSUE TITLE
latest win 11 23h2 customization

### ISSUE THREAD

**Issue by rajkumarindia** [pbatard/rufus#2354]
Rufus 4.3 with win 11 23h2 official iso not prompting for customization.

Like bypassing 4gb limit and TPM requirements.

**Comment by saintyuk** [comment]
Seems fine for me? Any further details?
![Screenshot 2023-11-01 145038](https://github.com/pbatard/rufus/assets/64711695/c5c2fccd-7573-4751-8ca5-e5cc82c52a9f)

**Comment by pbatard** [comment]
@rajkumarindia, please provide your log, or I will close this issue.

**Comment by Dook1** [comment]
I have the same issue.
[rufus.log](https://github.com/pbatard/rufus/files/13246067/rufus.log)

**Comment by pbatard** [comment]
I'm pretty sure the issue has nothing to do with using 23H2 and will happen with every recent Windows ISO.

@Dook1, your issue is that the __Windows__ ISO mounting facility (because for version detection, Rufus does mount the ISO itself but instead it asks Windows to do it) doesn't seem to be able to mount your `G:\Microsoft Windows 11, version 23H2, build 22631.2428 (updated October 2023) - Оригинальные образы от Microsoft MSDN [Ru]\ru-ru_windows_11_business_editions_version_23h2_x64_dvd_bcc01258.iso` image.

This is a Windows internal issue, not a Rufus issue, and as such, it is yours to fix.

Foe one thing, I'd try moving the ISO to the C: drive and rename it to something shorter like `Windows 11 23H2.iso`.

**Comment by netcore-jroger** [comment]
I have same problem.

CPU: i7 6700HQ
OS: Win10 Pro 22H2

**Comment by pbatard** [comment]
@netcore-jroger, please provide your log or I will ignore your issue.

**Comment by netcore-jroger** [comment]
Sorry, I don't use it often, I forgot. Need to click the start button to get that dialog box to pop up.

**Comment by rajkumarindia** [comment]
Im grateful to you for taking up the issue.

Im out of station .

Will  send tomorrow.

Thank you  and wish you all the best

**Comment by nbartley** [comment]
The bypass still works, you just have to not enable a network connection during setup. If you do, the bypass fails.

**Comment by pbatard** [comment]
No log &rarr; Closed.
