### ISSUE TITLE
Rufus corrupted a usb flash drive,

### ISSUE THREAD

**Issue by Regomy** [pbatard/rufus#2371]
I was installing a windows iso on a flash drive as a portable, but then when I hit cancel (had to leave) and rufus canceled the operation for 5 minutes, I got tired of waiting and closed it via task manager and removed the flash drive, the next time I put the flash drive into the computer I couldn't open it, couldn't find out the size and other information, when I tried to format it in explorer it froze. If you insert this flash drive and try to open rufus it won't open, but take it out and it starts. I can't provide logs as rufus simply won't even start, I've tried other programs to clean/format the flash drive but they can't start with this flash drive either.

As a matter of fact, I'm asking for advice on how I can fix my USB flash drive, not as a rufus problem, however, still broke it rufus. So-so. If there is a folder with logs from rufus, please tell me where it is and I will download the latest logs that are there.

Here's the logic, when I insert the flash drive RUFUS hangs, when I take it out I get a message underneath that says
- Found USB 2.0 device 'VendorCo ProductCode USB Device' (346D:5678)

https://gist.github.com/Regomy/b9735551a7a1ae7525e114010121be40 
or 
- Device eliminated because it appears to contain no media (new line) 0 devices found

- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [X] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [X] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [X] I also tried one or more of the following:
  - [X] Using a different USB drive.
  - [X] Plugging the USB into a different port.
  - [X] Running Rufus on a different computer.
- [X] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

**Comment by pbatard** [comment]
Looks like your drive was already failing when you were using Rufus (which is most likely the reason why you tried to cancel in the first place).

So, what happened is:
1. Your drive became defective while Rufus was trying to write to it (pure hardware error that had nothing to do with Rufus but everything to do with the unreliable nature of consumer USB flash drives)
2. Because the drive had already failed, the writing operation in Rufus took much longer than expected (since Rufus will pretty much wait forever until the drive responds) and you tried to cancel it.
3. The cancellation from Rufus didn't work, as Rufus was still waiting from Windows to report success or error on a write I/O call, so you killed Rufus from task manager.

Considering that none of 2-3 had any incidence on the fact that your drive would have failed regardless of what application was being used to write data to it or how the operation would have been cancelled, and that, from what you report, the flash memory on your USB media has failed (and as a result made the USB media controller switch to "no media detected" mode since it is no longer able to access the flash), there's really not much advice that can be provided to recover your drive.

If it's under warranty, you will have to RMA this flash drive to its manufacturer to get a new one. That's the only advice I can provide.

See also https://github.com/pbatard/rufus/wiki/FAQ#user-content-Help_Rufus_damaged_my_flash_drive and https://github.com/pbatard/rufus/wiki/FAQ#user-content-Rufus_cant_detectformat_my_drive_and_reports_that_it_is_readonly_or_contains_no_media.

**Comment by pbatard** [comment]
Since this looks like a pure hardware problem, I will now close this issue.
