### ISSUE TITLE
https://rufus.ie/en/ has become hideous; I had to re-enable Ublock Origin for the site

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pbatard/rufus#2386]
Checklist
---------
- [X ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [X ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below. [I have ticked the box, but the question is irrelevant.]
- [X ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it. [I have ticked the box, but the question is irrelevant.]

Additionally (if applicable):
- [NA] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [NA] I also tried one or more of the following:
  - [NA] Using a different USB drive.
  - [NA] Plugging the USB into a different port.
  - [NA] Running Rufus on a different computer.
- [NA] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

[NB - EDITED: accidentally I submitted the issue half-way through.]

I have not for years seen such an advert-infested mess as I saw when just now I visited https://rufus.ie/en/ - and I had vivisted that site not too long ago. Admittedly I use various tools to clean up webpages, including Ublock Origin. I found that I had disable Ublock for the page. I have now reverted that decision. I do appreciate Rufus, and I understand that you might need to make money, but that website almost has me looking for a replacement for Rufus. Moreover, the way that the site is at the moment makes Rufus look dodgy, i.e. like malware or similar.

Log
---
```
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
[Irrelevant.]
```

**Comment by pbatard** [comment]
If you have an issue with the ads that __Google__ places on the web page (over which I have very limited control, because, as you should expect, the last thing I want is spend my life filtering each ad when Google is supposed to do that job), please report it at https://support.google.com/google-ads/answer/7660847?hl=en.

Google, not me, is the entity that decides the ads that display. I do try to filter some of the most obvious crap (gambling, esoteric, etc.), but there's only so much Google lets me filter, so, again, since I don't have a historical vision that allows me to see what ad what served when (and even if I were able to do that, which I am not, then I'd need you to disclose your IP address along with the time of your visit), you need to contact Google directly, with one of the forms that they readily provide, to report an issue with an ad served by Google.
