### ISSUE TITLE
The partition format cannot be modified in later versions

### ISSUE THREAD

**Issue by acolasialiuliu** [pbatard/rufus#2401]
I'm installing manjaro and prompted after selecting the image -You selected an ISOHybrid image file, but the file is not compatible with the ISO/File copy mode. Therefore, it is mandatory to use the DD image write mode.
And the partition formatting and other operations are grayed out, and I changed to version 3.0 to be available.

**Comment by pbatard** [comment]
That's the whole point.

ISO mode was removed for Manjaro, because I can **NOT** guarantee that your drive will boot or install Manjaro properly.

As the message indicates, there are circumstances where the distro maintainers make is so that their ISO will simply not work properly unless you use DD mode.

Now, if you insist on using ISO mode, by going to an older version of Rufus, you are 100% on your own, and I will **not** bother to try to help you out if you come back to this issue tracker to report that you tried to install Manjaro in ISO mode and it dodn't work.
