### ISSUE TITLE
ParrotOS clone issue. Cannot copy all files at the right size like the .iso files for ParrotOS.

### ISSUE THREAD

**Issue by dan-robotics** [pbatard/rufus#2413]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Rufus cannot copy all ParrotOS files to USB Disk 32GB! 
1. It would be nice if it can detect if C: space is low and need additional space to finish copy the temporary files, and ping you for the error or if it cannot copy the same files at same size. (Kindly, I am not sure if this could be shown on the check image function of the program, as I was in a rush to finish 5GB image and do it quick.) 
2. I tried to create the image about a couple of times. No errors during the process but when I realise that I need to check the files if have same size like what's on the image, I saw that an file called "filesystem.squashfs" (4.7GB) was not copied entirely (not sure if it did not copy cause of the low space on disk C: for temporary files or because of another issue), and image cannot boot on UEFI or Legacy Boot. I manage to copy the files and I am able to run the image now, but it took me a while. I am happy that my problem is solved.

Log
---

```
Rufus x64 v4.4.2103
Windows version: Windows 11 Pro x64 (Build 22631.3007)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0809 (en-GB)
Will use default UI locale 0x0809
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found 517 officially revoked UEFI bootloaders from embedded list
Found 2351 additional revoked UEFI bootloaders from this system's SKUSiPolicy.p7b
Found USB 3.0 device 'Kingston DataTraveler 3.0 USB Device' (0951:1666)
Using 'autorun.inf' label for drive E: 'Parrot security 5.1.1'
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3772, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x00916C45
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Detected File System: NTFS
  Size: 28.9 GB (31027335168 bytes)
  Start Sector: 2048, Boot: Yes
Partition 2 (UEFI:NTFS):
  Type: EFI System Partition (0xef)
  Detected File System: FAT12
  Size: 1 MB (1048576 bytes)
  Start Sector: 60602312, Boot: No
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Detected Syslinux version: 6.04/20200816 (from '/isolinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Parrot security 5.1.1'
  Size: 4.7 GB (Projected)
  Has a >4GB file
  Uses: Syslinux/Isolinux v6.04
  Uses: EFI
Using image: Parrot-security-5.1.1_amd64.iso (4.6 GB)
```

**Comment by pbatard** [comment]
1. You appear to have truncated the log, which you were told not to do. Please bear in mind that you need to provide a log that shows the complete operation you did to create your boot media, or else, I'm going to assume that you might be trying to conceal something, such as an explicit error or warning during copy.
2. Considering this, I'm also going to assume that this is the **classic** issue of overzealous AntiVirus solutions preventing files from pentesting distros (such as Kali, Parrot and so on), that obviously contain executables that can be misclassified as malware, from being copied. Rufus does not bypass security solutions, so, if a security solution wants to prevent a copy or delete a file after copy, you will have exactly the issue you described.
3. I am not seeing any issue on my side. The file is properly copied and not deleted. But I am pretty sure this is because I'm not using the same security solution as you do.

Also, this is not an issue with temporary files. Rufus does not make any use of temp space as it copies the files in chunks directly from the ISO. If temp space is used, then it's the system (Windows) doing USB caching, but in that case, this is a pure Microsoft problem, as we have zero control over it.

Because of all the above, as well as the missing data from your log, I'm going to close this issue, especially as there really is nothing for me to do, since, again, this is not due to temp space or anything Rufus has any control over, and it only occurs in your specific environment.
