### ISSUE TITLE
Windows 11 23H2 V2 don't bypass hardware requirements

### ISSUE THREAD

**Issue by drigoskalwalker** [pbatard/rufus#2438]
Basically this
Windows 11 23H2 V2 don't bypass hardware requirements.

I got the message "Hardware not supported"
![this-pc-can-not-run-windows-11](https://github.com/pbatard/rufus/assets/161599535/3427c91b-ce2c-4288-b258-10b8a0a14277)

Before the V2 image rufus worked to bypass hardware requirements, now no more.

My setup is Xeon 2696v3 no TPM.

**Comment by JonnyTech** [comment]
Please complete the issue template:

```
PLEASE READ THIS CAREFULLY:

1. You *MUST* read and complete the steps from the checklist below, by placing
   an x into each [ ] (so that it shows '[x]', NOT '[ x]' or '[x ]'), BEFORE
   clicking on 'Submit new issue'.

2. Failure to perform these steps, WHICH ARE ONLY THERE TO HELP *YOU*, will
   usually result in your issue being dismissed without notice.

3. If you are reporting an issue when trying to run Rufus, or when trying to
   boot a media created by Rufus, you *MUST* provide a log, period. Please do
   not assume that the developer(s) will be able to "guess" the specifics of
   your environment, what image you used, what type of media you used it with
   or the many many other critical parameters that the log provides data for.
   To investigate an issue, a log from Rufus is ALWAYS required.

4. If you still *choose* not to provide a log when reporting a problem, you
   agree that your issue will be closed without any further investigation.

YOU HAVE BEEN WARNED.
-->

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Log
---

<FULL LOG>
```

**Comment by pbatard** [comment]
Indeed, we want the data that was requested for you.

Otherwise, considering that you are the **only** person using 23H2v2 to report this issue (and, with Rufus downloaded close to 3 million time each month, currently a lot of which being for Win11 23H2v2 installs), I will have to dismiss your problem as purely environmental.

Please don't assume that, because you are experiencing an issue, it is a global issue that is/will affect everyone else.

Considering that Rufus does **not** provide any bypasses for older CPUs and whatnot, my guess is that with 23H2v2, Microsoft started to recompile Windows to use extensions that only modern CPUs provide, and that you are using a CPU that is lacking these extensions.

Obviously, there is nothing I will be able to do in Rufus to help you if that is the case (I can't magically recompile Windows to make it work on CPUs that lack features that Microsoft **gradually** makes mandatory).

**Comment by drigoskalwalker** [comment]
Nevermind, I bought WinToUsb from Hasleo Software, checked the "bypass system requisites" and worked like a charm.

The version of rufus I used was 4.2 and 4.4, and for sure with this lastest ISO as I described before the bypass didn't work.
And yes, my CPU have all necessary extensions, just check in the intel ark.
I think the problem is with TPM again, something changed.

Thank you for your time.

**Comment by pbatard** [comment]
Well, since you did not provide enough data (including data that validates precisely how you create the media and what options you used) and nobody else is reporting a similar problem, I will close the issue.

For your reference, I did validate a full install of Windows 11 23Hv2 near the time it was released, on unsupported hardware (without TPM) and saw absolutely no issue.

**Comment by dbell68** [comment]
Since 23619 (IIRC), Rufus is no longer enabling bypass of the TPM check when running setup from the USB and upgrading a prior release. I managed to get 26058 (dev) installed by replacing setup.exe and some of the appraiser*.dll files with those from 23619 but the issue remains. I just built a USB with 26080.1100 ISO that dropped today and it fails the TPM check. I think MS must have changed how they are doing the sys req validation.

**Comment by dbell68** [comment]
I had upgraded to all of these prior W11 insider dev versions (since June 2023) running setup.exe from USB built from Rufus:
![image](https://github.com/pbatard/rufus/assets/49237983/597a45e6-b158-4d16-b8cd-9594793bab99)

**Comment by pbatard** [comment]
I'm afraid I don't support insider releases.

See https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_Insider_builds_NOT_SUPPORTED.

**Comment by dbell68** [comment]
@pbatard - ok but at some point these won't be insider anymore, and without an update Rufus, won't be able to solve this need.

**Comment by pbatard** [comment]
Yes, and I'll look into **then**. But not before.

I've wasted too much time investigating Insider features and changes that never made it into a release not to know better.

Besides, as much as I'd like to take credit for the bypasses, I didn't come up with them. From what I can tell, after Microsoft __deliberately__ added them to the Windows installed, someone from Microsoft made them public, so that they started to be reported on tech news sites, so that, after I checked them out, I decided to add them to Rufus. And you will notice that there is a direct dependency to Microsoft's goodwill there. In other words, despite what many people appear to believe, Rufus is not hacking Windows or its installer to bypass the system requirements, but using a method that is provided by Microsoft. So if Microsoft decides to remove that method, I'll probably wait to see if someone publicizes another way because I have neither the time or will to hack Windows or its installer. And if noone comes with a solution that I can use in Rufus, I'll probably just drop the bypasses for newer versions of Windows.

Which is why, I am not planning to do anything to try to "solve" this, even less pre-emptively.

**Comment by drigoskalwalker** [comment]
The point is, there's no insider preview thing.
The problem occurred in the final release as I said before.

I know that will not make any sense but I think there's a difference between locale images.
I'm from Brazil and I got the TPM bypass not working in the  23H2 V2 PTBR image.
Maybe you are trying in the US image and it's working for you.

I solve my problem using WinToUsb from Hasleo.
But I do like Rufus, and would like to see it working in the future.

Nevertheless, thanks for your work.

**Comment by pbatard** [comment]
@drigoskalwalker,

1. I was replying to @dbell68, who is using Insider releases and who piggybacked on this issue instead of opening a new one, since the issue you opened was not for Insider releases.
2. I just tested 23H2 V2 PTBR image on the oldest unsupported machine I have (a Dell Optiplex 390 with **no** TPM) and saw no issue. Therefore, __as expected__, since I can guarantee that the checks for requirements is universal and does not change depending on locale, your assertion that this is something to do with using Brazilian image is wrong.
3. You still did not provide the log, that was requested of you, of how you created your media, therefore I simply cannot rule out that you just did not select the right options there.
4. All you got as an error is that your system does not meet the system requirements for Windows 11 23H2v2. You are misreading that you got an error about _"TPM bypass not working"_ but the error message you shows does not state anything about TPM. So please don't assume that your issue is with the TPM bypass not working, because I am pretty sure it has nothing to do with it.
5. On that topic, please bear in mind that the TPM/Secure Boot/RAM bypass is only for TPM/Secure Boot/RAM. It does nothing for other hardware requirements, such as CPU having specific extensions and other hardware requirements that Microsoft may introduce in new releases of Windows (because hardware requirements do evolve and Microsoft does not keep them the same for all Windows 11 releases). Another very likely possibility is that the Xeon processor you use is missing CPU extensions that are part of Windows 11 system requirements, and which Microsoft did not enforce until 23H2v2. And to explain why WinToUsb would still work, my guess is that they are injecting an old appraider DLL that does not check for the 23H2v2 CPU requirements (which, even if I wanted to, would be tricky to do legally in Rufus since the DLLs are copyrighted by Microsoft).

I can only reiterate that if you are genuinely interested in improving Rufus, you **MUST** follow the checklist that is being asked of you when opening issue, because, if you **CHOOSE** not to provide a log, you are 100% preventing any improvement to happen as will be unable to determine the exact nature of the issue, which means I will **NEVER** be able to fix it. It's as simple as this.

**Comment by drigoskalwalker** [comment]
Hi there's nothing that would help you in the logs.
But I would send you the logs anyway, so I downloaded the Windows 11 image again, generate with rufus, and guess what? It worked.
So, problem solved. Maybe it was something wrong with the first image I downloaded.
I don't remeber if I use the same image with Hasleo.
And just to point out, as I said my CPU is E5-2696V3 probably it has more extensions that what you are using now.

**Comment by pbatard** [comment]
> there's nothing that would help you in the logs.

Are you the developer of the application?

If not, I'm afraid that is **not** an assertion you can make. Instead my long experience of troubleshooting user issues and of tailoring the log to precisely expose potential problems tells me that, especially if you tried creating a media twice with different results, there most likely was something, in the log, that would have helped us determine why your initial attempt did not work, and that, if you had followed the check list, we would have avoided a lot of this back and forth.

At any rate, I am glad that your issue was sorted, but, really, you should not assume that you know better than the developer what they need to try to help you with a problem, and if someone asks you for a log, you just provide that log, period.

**Comment by drigoskalwalker** [comment]
Sorry to be honest, nice job and have a nice day.
