### ISSUE TITLE
[Feature Request] Simple web-site download button

### ISSUE THREAD

**Issue by drweb86** [pbatard/rufus#2450]
Hi guys

I appreciate work you've done with this utility, I use it already second time and it works just great.

Recently I was making simple download page for one on my projects and basically i wanted to have big download button before links to download for various platforms. And link to this button to show the platform-specific setup file.

I managed to do this and thus I have feature request to do it for your website. It might save some time for people so they won't need to think about their platform or even visit separate download page.

Here's the code sample 
```

<!DOCTYPE html>
<html>
    <head>
        <!-- Disable cache -->
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
        <meta http-equiv="Pragma" content="no-cache">
        <meta http-equiv="Expires" content="0">
    </head>
<body>
    <div class="button">
        <a href="#" id="default-setup">Download Setup</a>
    </div>

<script>
    var urlParams = new URLSearchParams(window.location.search);
    var version = urlParams.get('release');
    var setupWindowsArm64 = 'BUtil_v' + version + '_win-arm64.exe';
    var setupWindowsX64 = 'BUtil_v' + version + '_win-x64.exe';
    var ubuntuUrl = 'https://github.com/drweb86/butil/blob/master/help/Ubuntu.md';

    navigator
        .userAgentData
        .getHighEntropyValues(["architecture"])
        .then(ua => {
            var defaultDownloadElement = document.getElementById("default-setup");
            if (navigator.userAgentData.platform.includes("Linux")) {
                defaultDownloadElement.href=ubuntuUrl;
                defaultDownloadElement.innerHTML = "Ubuntu build instructions"
            }
            else if (navigator.userAgentData.platform === "Windows") {
                if (ua.architecture === 'arm') {
                    defaultDownloadElement.href="./" + setupWindowsArm64;
                    defaultDownloadElement.innerHTML = "<p>Download Setup</p><span>(detected Windows, ARM64)</span>"
                } else {
                    defaultDownloadElement.href="./" + setupWindowsX64;
                    defaultDownloadElement.innerHTML = "<p>Download Setup</p><span>(detected Windows, X64)</span>"
                }
            } else {
                defaultDownloadElement.href="#";
                defaultDownloadElement.innerHTML = "Your platform is not detected/supported."
            }
        });
</script>

</body>
</html>


```

**Comment by pbatard** [comment]
Thanks but I would ask you to be weary of considering that all web sites have similar needs or that all applications are designed for the same groups of users.

For one thing, there's no such thing as anything we can provide for Linux users. Rufus cannot be compiled for Linux, period. It's Windows only. So there's no "Ubuntu build" instructions we can point to. And considering that this is a utility that is aimed at people installing OSes, and __therefore__ better be a little bit versed in architectures and software that does not aim at holding their hand, I have a very different take on trying to hide the elements you suggest from the user.

If anything, and this is a "trick" that is actually used elsewhere in the application, I very much want to _scare away_ users who are likely to have no clue what they are doing (such as not being able to tell the arch of the exe they need to download), because installing an OS is far from a trivial operation, and trying to make it look at such, by holding the user's hand until we have no choice but to let go and they end up completely lost because they were under the impression, starting from the download, that they would be guided all the way, is not going to do them any favour.

So the decision not to sugarcoat the downloads under a big _"Here you go, we picked up the right download for you"_ green button, when you can very much do a lot wrong if you create a bootable installation media without having done your homework, is as deliberate as using some advanced terminology and doing other stuff in the app, and I sure want to continue to scare people away if choosing the right download on the website is already seen as a hurdle.

Therefore, as much as I appreciate your desire to help, I have to reject this request.
