### ISSUE TITLE
Win10, disk mounted to folder (w/o letter) Rufus can't see directories and files inside (like an iso per se) It shows the whole disk as empty

### ISSUE THREAD

**Issue by somethingstarted** [pbatard/rufus#2455]
I understand not wanting to deal with non standard mounts, but i feel this could be helpful to some depending on how common mounting to a folder is with windows users. 

Known workaround: copy file you want to a disk mounted to a letter and be done with it 

Thanks.

**Comment by pbatard** [comment]
I believe that your issue is the same as the one described [in this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Why_can_Rufus_not_see_my_network_shares) in that, because, Rufus runs elevated, disk and folder mappes as your regular user will not be accessible.

Please bear in mind that Administrator and your regular user are different accounts with different permissions and, despite what many seem to believe, Administrator does not have all access to all mapped resources.

A good way to tell if it's a Rufus issue or a Windows issue is to run Notepad elevated and see if you can access the files on your mounted folder. If you get the same issue, then clearly, this has nothing to do with Rufus.

I'd try the workaround described in the FAQ entry and see how it goes. But otherwise, yeah. I don't think I'm going to lose much sleep on an issue that I'm pretty sure is a pure Windows one and that, even if it wasn't, the cost/benefit of addressing would still be way too high.
