### ISSUE TITLE
[SUGGESTION]: Catalan Translation

### ISSUE THREAD

**Issue by DidacDelPort** [pbatard/rufus#2460]
Dear Rufus Development Team,

I am writing to you with the purpose of expressing my interest in collaborating with your team to carry out the translation of your software into Catalan. As a Rufus user, I have appreciated the usefulness and effectiveness of your tool for creating bootable USB drives.

However, I would like to point out that the availability of the software in Catalan would be of great benefit to Catalan-speaking users, as it would make it easier to use and more accessible to a wider audience.

Catalan is a language with a rich cultural tradition, and its inclusion in the field of technology and software is important for its preservation and promotion. Offering Rufus in Catalan would not only be a gesture of respect towards linguistic diversity, but would also expand its reach to a community of users that currently does not have access to a version in their native language.

As a fluent speaker of Catalan and Spanish, I am willing to collaborate with you in the software translation process. My goal is to ensure an accurate, high-quality translation that maintains the functionality and effectiveness of Rufus in Catalan.

I remain at your disposal to discuss further details about this proposal and to answer any questions you may have regarding it. I sincerely hope that you consider this suggestion and that together we can contribute to making Rufus a more inclusive and accessible tool for all users.

Thank you for your attention and I look forward to the opportunity to collaborate with your team.

Sincerely,
Diego Benito

**Comment by pbatard** [comment]
I do not plan to include Catalan or [any of the languages that Microsoft does not support as prime Windows languages](https://www.microsoft.com/en-us/windows/windows-10-specifications#areaheading-uid60d4) as Rufus translations. I just don't have the scope to support that many languages, because catering for translation is a lot more demanding than people realise.

For more on this see [this FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#user-content-What_languages_are_natively_supported_by_Rufus) as well as [the next one](https://github.com/pbatard/rufus/wiki/FAQ#what-about-the-languages-that-arent-listed-above).

Sorry.
