### ISSUE TITLE
[Feature Request] Estimate time when flashing image.

### ISSUE THREAD

**Issue by TCFFan123** [pbatard/rufus#2467]
﻿

Checklist
---------
- [X] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [X] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [X] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I would like to see a estimated time until finished in Rufus 4.5. Could be useful.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
You can already get this when writing in DD mode if you press <kbd>Alt</kbd>.

On the other hand, this will **never** be implemented for ISO extraction, because there are operations (formatting, patching) that rely on Windows APIs where we simply cannot get any time estimation, and I will not go with a half-assed guess just to hear people then complain that the time estimate is wrong.

Please bear in mind that it's not because an application can provide a progress of its operations that it can produce a time estimate. You can get progress reports for "black box" Windows APIs, but, since these are black box, there is no possibility to get an estimate of how much time is left to completion, and the cost/benefit of trying to "guesstimate" a value is simply not worth it n an application that was never designed to be a benchmarking tool.
