### ISSUE TITLE
New option - disable encryption

### ISSUE THREAD

**Issue by ExaFlop1** [pbatard/rufus#2476]
According to the new M$ policy (Windows 11 24H2) for encrypting the device, please add to the Rufus an option to switch on/off the encryption:
https://www.youtube.com/watch?v=kTLkejC4PbI&t=630s

**Comment by pineapple63** [comment]
Rufus already has an option to disable encryption

**Comment by pbatard** [comment]
Yes, as far as I know, the _Disable BitLocker automatic device encryption_ that is already present is what you are after.

At any rate, [I **DON'T** look into Insider build features](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_Insider_builds_NOT_SUPPORTED), because Microsoft has a habit of completely reworking or dropping them by the time of the actual release.
