### ISSUE TITLE
Issue with Rufus burning iso from Aoemi Backupper

### ISSUE THREAD

**Issue by UNC1RLM** [pbatard/rufus#2497]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
i get this message when I use Rufus to burn a ampe. iso  (Aoemi Backupper). I contacted them and they said contact you about this.

![Rufus Error Message with Aoemi Backupper](https://github.com/pbatard/rufus/assets/107044696/e4c74d06-eefb-4906-85a3-0db0c980762a)

Thanks for any help

BobM.
Log
---
```
Rufus x64 v4.5.2180 (AppStore version)
Windows version: Windows 10 Pro x64 (Build 19045.4474)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.12
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found 517 officially revoked UEFI bootloaders from embedded list
Found 2351 additional revoked UEFI bootloaders from this system's SKUSiPolicy.p7b
Notice: Windows VDS is unavailable
Found USB 2.0 device 'SanDisk Cruzer Glide USB Device' (0781:5575)
Using 'autorun.inf' label for drive E: 'Aoemi WinPE for Booting Computer'
1 device found
Disk type: FIXED, Disk size: 8 GB, Sector size: 512 bytes
Cylinders: 973, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {5DACDF5C-516E-4AE9-9852-D6E81D92F005}
Max parts: 128, Start Offset: 17408, Usable = 8004270592 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: FAT32
  ID: {C69D8DAF-22C1-4E4B-9FB8-AE912FDFFA1B}
  Size: 7.5 GB (8003227648 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
```

**Comment by pbatard** [comment]
> I contacted them and they said contact you about this.

LOL.

You will need to contact them back and tell them that their ISOs (or at least the one you use, maybe they have updated them since) use a Windows bootloader that is affected by the _BlackLotus_ Secure Boot UEFI vulnerability, which is what Rufus is warning you about. Or maybe, in case it's not Aoemi Backupper that provides the ISO bootloaders, but they were picked up from the system you are trying to back-up, it's your system that is vulnerable to _BlackLotus_.

At any rate, one of these should be updated so that it doesn't use a vulnerable UEFI bootloader, and that is **not** something Rufus can fix for you.

Or, since this is a simple warning (this is not an error) you can just press OK to continue, knowing that, if you are trying to boot that media on a system that has been updated to prevent _BlackLotus_ vulnerable bootloaders from running where Secure Boot is enabled, you may get a boot error since these vulnerable bootloaders have been (rightfully) revoked as potentially unsafe.

Is the system you are trying to back up fully up to date with Windows Update? Because, if that is the case, then its bootloaders should have been updated by Microsoft to versions that are not vulnerable, and not produce this message. In which case, that would mean that the bootloaders that are producing the warning come from Aoemi Backupper, and you will need to ask them for a version of their software that use updated non-vulnerable bootloaders. Oh, and if that is indeed the case, you may also want to ask them to confirm that they have a deal to redistribute Microsoft copyrighted content, as these bootloaders are copyrighted by Microsoft, and one needs a license agreement to redistribute any Microsoft copyrighted content...

At any rate, there's really nothing more I can do for you here. Either you use an ISO that uses non-vulnerable bootloaders, or you ignore the warning. And if you want to know more about the reason why Rufus produces this warning, you can take a look at #2244, knowing that it meanders a lot around the whole subject matter.

**Comment by UNC1RLM** [comment]
Yes everything is updated. This is all greek to me so I will write Aoemi..doubtful they care lol.

Thank you. greets and Best Wuishes,
Bob M.
