### ISSUE TITLE
How to make rufus a trilion times better!!!

### ISSUE THREAD

**Issue by La1234567891230** [pbatard/rufus#2518]
Just add support of burning Windows XP in rufus!!!

**Comment by pbatard** [comment]
So you believe there are a trillion Windows XP users in 2024?

At any rate, Rufus **does** support writing Windows XP ISOs. I still haven't removed the feature, though overzealous XP users like you, who believe a completely dead OS that has become a major security liability, not just for yourself but for everybody (since, like viral infection, it's not just **you** you are putting at risk by being careless, but all the people around you) are seriously making me reconsider that choice...

Finally, please see [this](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Windows_XP_Windows_Vista_Windows_7_NO_LONGER_SUPPORTED) which means that, if you are doing anything that relates to Windows XP with Rufus, you are 100% on your own, and I will not answer any further questions.

**Comment by thecatontheceiling** [comment]
the title was clickbait, disliked
