### ISSUE TITLE
Installing Windows 10

### ISSUE THREAD

**Issue by AmirHoseinDashti** [pbatard/rufus#2521]
Hello, when burning Windows 10 on a flash drive with Rufus, I clicked the option to create a local account, and after I installed Windows, it tells me to enter the password and then a new password if I did not leave a password for Windows.

**Comment by pbatard** [comment]
Yes, that's expected. Rufus will force local account to set a password after Windows is installed. The existing password is empty/blank. If you want to use a local account without a password, please look elsewhere because Rufus is not designed for that kind of usage scenario (which is a security liability and therefore not something I will ever endorse).
