### ISSUE TITLE
Windows to go not installing

### ISSUE THREAD

**Issue by vince897** [pbatard/rufus#2528]
﻿

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<I have tried severl copies of Rufus and several downloads of Windows 11 ISO and it results in failure. In despiration I used my version of Rufus and Windows 11 and successfully omplered the standard install. This tells me my versions of Rufus and Windows 11 ISo are correct and my USB is functioning properly.

I want Windows 11 on a USB as the computer is wish to use it on has limited memory insufficient to update Windows.

At this point I'm confused what to do.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
I'm sorry but your error report (_"results in failure"_) is way too vague and you are missing a log.

At any rate, if you didn't see any error during the Rufus media creation process, and Windows still doesn't work as expected, it is an issue between your hardware manufacturer and Microsoft, who are responsible for the ability of Windows to run, and not Rufus (which does not alter the Windows content and is not responsible for the ability of a system to actually be able to run Windows).

I therefore have no choice but to close this issue, because you seem to be expecting that, from a super vague error report, someone will be able to pop up and say _"Hey, I had the same issue too, and you need to do X, Y, Z to fix it"_ or _"Oh yeah, I just tried to create a Windows To Go media, and it didn't work either for me"_, which is simply **not** going to happen here, as this is an issue tracker, not a discussion forum.
