### ISSUE TITLE
Wiki should include Expert Mode (Ctrl-Alt-E) shortcut and description

### ISSUE THREAD

**Issue by DoubleStrike** [pbatard/rufus#2536]
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Issue description
-----------------
The wiki page does not list the Expert Mode - accessed with Ctrl-Alt-E and also does not mention what it does and what additional functions it unlocks.

**Comment by pbatard** [comment]
I'm afraid that this is very much intentional.

I have no plan to ever officially document what expert mode does because I estimate that it will create **a lot** more problems than it will actually help users.

Case in point #2385 where I get berated from people using expert mode and not understanding that this not a feature that I can ever officially support.
