### ISSUE TITLE
Cannot boot from USB Stick after using Rufus

### ISSUE THREAD

**Issue by Apache060** [pbatard/rufus#2548]
Hello,

This is the first time I am logging the following issue with Rufus I am using version 3.19 as I cannot get the new version to work, Find after I have copied the ISO file to USB Stick and try to boot from USB Stick the PC will start up then the screen goes blue and stops loading up, tried other PC and got the same issue, tried other USB Stick but no good.
Any help would be great. 

Thanks

**Comment by pbatard** [comment]
>  after I have copied the ISO file to USB Stick

That's just **not** how you create a bootable media. You don't copy the ISO to the USB media.

Since your post is lacking details on how to best help you (and you are using a pre 4.x version of Rufus, which I can no longer support &mdash; especially my guess is that you are trying to run Rufus on Windows 7 in which case you are 100% on your own) I **strongly** suggest that you look for youtube videos on how to use Rufus to create bootable media for your specific usage scenario (you might have to type something like: `rufus` `<name of the ISO you are trying to use>` `youtube` in your search engine), which should give you a much better idea on how you are supposed to use Rufus.

Then, if you still encounter an issue, you can create an issue here. But if you do, please make sure that:
* You do use the latest version of Rufus (which is the only version I can support)
* You do follow the check list and provide the log of how you created your media, as explicitly requested.
