### ISSUE TITLE
Please another bar to Status

### ISSUE THREAD

**Issue by jfha73** [pbatard/rufus#2551]
﻿

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Please besides de Total percentage bar can you add a file percentage? when you are copying big files to a USB it takes a long time to copy and it would be helpful knowing where Rufus is doing this.

Kudos, Thanks.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
The current progress bar reflects the progress of the copy within a individual file.

This means that, if you have a 1 MB file, and an 8 GB file on an ISO, Rufus is not going to jump to 1% then nothing then 100% when the large file is done being copied, but instead, it will accurately reflect, about 10 times per second, how many bytes of the ISO have been written so far, compared to the total number of bytes from the ISO.

**Which means** that, if the total progress appears stuck, then the same progress will also be stuck if you were to display a separate one for individual files.

In other words, you're not going to get finer grained progress with an additional bar, because that bar will just rapidly oscillate between empty and filled for small files, and not be that much different from the total progress for large ones (yeah, you may get a few extra pixels, but it won't be that much).

Ultimately, all the _"I wonder what is happening &mdash; there must be some kind of copy going on, that is not being reflected by Rufus, and I'd like to get some information about that"_ boils down to Windows caching, and Windows *not* having any API that can report what is going on when it's flushing its cache.

So, because of caching, you get super fast progress when copying to the cache, and almost no progress when the cache is effectively being flushed, because that's just how Windows reports progress to applications that ask it how far the copy operation currently stands.

As a result, I will reject this request, because it would only bring confusion when lots of small files are being copied (again any progress percentage / progress bar will fluctuate wildly and give exactly no useful information to the user then) and it will not bring more insight when copying large files (because, again, the file progress bar will be as equally stuck as the total progress bar when Windows flushes its cache).

If you are unhappy that Windows cannot accurately reflect the actual progress of a large copy operation, and therefore Rufus, you will need to contact Microsoft first, so that change the way they report file copy progress to USB drives...
