### ISSUE TITLE
Rufus , issue with setting local account

### ISSUE THREAD

**Issue by mmpr1** [pbatard/rufus#2557]
giving "local" or "Local" as username for creating local account 

after installation , it wont accept empty or blank password 

any work around ?

**Comment by pbatard** [comment]
The use of blank or empty passwords is **not** something I can support.

Rufus does initially use a blank password so that:
1. You don't have to type one in the application and wonder if, *somehow*, we're not malicious exfiltrating them
2. On initial install, Windows will automatically log on to complete the install.

**HOWEVER**, Rufus make sure to ask you to change the password after that, because, in no way, I want to endorse the use of a blank password on a new Windows installation.

My understanding (because your report is very short on a detailed explanation) is that you are attempting to use a blank password.

Therefore, you are out of anything I can support.

I would also *STRONGLY* advise not to attempt to use account names that might be reserved by Windows. I do try to filter some out (like `Admin`) in Rufus. But I will not filter them all out. So if you are using what turns out to be a reserved Windows account name, and then encounter an issue, you are also on your own.

Please try to use something like a real name account with a proper password, and only if you still find that you have an issue, you can reopen an issue.
