### ISSUE TITLE
Large FAT32 file system is not offered in case ISO is larger than 8 GB and usb stick is formatted NTFS

### ISSUE THREAD

**Issue by lcsongor** [pbatard/rufus#2558]
Issue description
----------------- 
Rufus does not offer to format drive to Large Fat32 when trying to burn an ISO larger than 8GB to a USB stick. 

Steps to reproduce: 

1. Create a bootable ISO, larger than 8 GB (10GB for example) 
2. Plug in a USB stick, which has been formatted as NTFS, larger than the file (16GB for ex.)

Expected result: 
Rufus offers you to format the USB disk as exFAT or Large Fat32 to accommodate the large ISO. 

Actual result: 
Only NTFS is offered as formattable file system option. 

MItigation: 
Format, using Windows the USB stick as exFAT and this file system will be offered as an option to format the usb stick with. 

Happens with Rufus 4.4. 

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
The log that you have **chosen** not to attach, **despite being explicitly asked to do so** would have told you why.

If an ISO contains a file that is larger than 4 GB, then Rufus can **NOT** offer you the choice of using FAT32 (or Large FAT32, which is still FAT3), because FAT32 can simply not accommodate files that are larger than 4 GB. That's a limitation of the specs that you cannot work around.

So Rufus **has no choice** but to let you use a different file system, and since exFAT is far less supported than NTFS, and would lead to issues, whereas we do offer a solution that, yes, [does allow you to boot from NTFS even on modern UEFI systems with Secure Boot](https://github.com/pbatard/rufus/wiki/FAQ#user-content-Blah_UEFI_Blah_FAT32_therefore_Rufus_should_Blah) which means that, no, you don't need to use FAT32.

Of course, if you had described why you _believe_ you need FAT32, and why you _believe_ it might cause issues not to use it, I may have tried to elaborate further, but since you didn't, I will simply close this issue, as I am confident I have answered your question.
