### ISSUE TITLE
Feature Request: systemd-boot

### ISSUE THREAD

**Issue by ero35** [pbatard/rufus#2591]
﻿systemd-boot ; 
Multiple ISO selection
Similar to Ventoy

**Comment by pbatard** [comment]
From #2576:

> Add support for [systemd-boot](https://wiki.archlinux.org/title/systemd-boot) (if needed and whenever the hell we find an ISO that uses that)

Since you're not pointing to any ISO that uses systemd-boot, I assume that there still aren't any yet.

Also: https://github.com/pbatard/rufus/wiki/FAQ#user-content-Do_you_plan_to_add_multiboot_support

The check list, that asked you to look at the FAQ and perform [a search in the issue tracker](https://github.com/pbatard/rufus/issues?q=systemd-boot) (which would have pointed you to #2576) does apply to you, even if you ask for features.
