### ISSUE TITLE
Official MSDN ISO "has been revoked by Windows SVN" with Rufus 4.6

### ISSUE THREAD

**Issue by MELERIX** [pbatard/rufus#2594]
Using image: es-mx_windows_10_consumer_editions_version_22h2_updated_oct_2024_x64_dvd_d0cfb2e9.iso (6.4 GB)
Note: No Windows User Experience options selected
Warning: '/bootmgr.efi' has been revoked by Windows SVN
Warning: '/efi/boot/bootx64.efi' has been revoked by Windows SVN

anyway it still boots fine in UEFI mode, just that during USB creation it throws a warning.

**Comment by pbatard** [comment]
It only boots because your system is not up to date when it comes to Secure Boot revocations. The thing about revocations is that they don't exist by default, but get applied **eventually**. And it's not because the warning from Rufus doesn't apply to you because the system you tested doesn't have all of the Secure Boot revocations applied that it won't be useful for other users who do, or that it should be removed.
