### ISSUE TITLE
Rufus still showing Dev Drives/ VHDs by default

### ISSUE THREAD

**Issue by nebula-it** [pbatard/rufus#2608]
Well it happened to me as well 😬  https://github.com/pbatard/rufus/issues/2305
I'm usually careful but was in a rush and next thing you know. Somehow even the size order didnt save me this time, as VHD was definitely bigger (100GB) vs thumb drive(32GB). But I cant reproduce this now 🤷

That was on v4.1. Found that it was fixed in 4.4 https://github.com/pbatard/rufus/commit/ebe01cc7b691cf1014d21dbd719ed209ac5d647e

So I downloaded the latest v4.6, however it still shows my Dev Drive in there by default.

```
Found VHD device 'Microsoft Virtual Disk'
Found USB 3.0 device 'Kingston DataTraveler 3.0 USB Device'
```
Let me know if you need any more info. Thank you

**Comment by pbatard** [comment]
Well, I'm afraid I don't have enough data to act on and you truncated the log. I am missing A LOT of relevant data because of that.

My last testing with Dev Drives showed that they are properly eliminated by Rufus, and your issue appears to be that you were using an old version and chose not to update, which should teach you a valuable lesson about disabling update checks. The update check is not just there to annoy people, but to provide a very critical service to help users, especially when it comes to ensuring that the application handles new external features... such as newly Microsoft introduced Dev drives.

At this stage I have no idea if the VHD you mention in the paltry two lines of log you chose to paste is an actual dev drive or a completely different VHD.

So, at this stage, I'm going to wait for a report from people who actually ran into an issue with dev drives, when using the latest version of Rufus, and who also understand the importance of not withholding data that they are explicitly asked to provide.
