### ISSUE TITLE
New feature - 

### ISSUE THREAD

**Issue by MrRolid** [pbatard/rufus#2611]
Please consider adding a small indicator of the current upload speed. Perhaps place it on the bottom right where it will show when you click on the duration of the file upload. Thanks for your work

**Comment by pbatard** [comment]
You can get the speed for DD image writes by pressing <kbd>Alt</kbd>.

For ISO mode writes, you won't get that info, because it's would be much more complicated to compute and, due to Windows caching, there would still be long periods of time where you would see the speed drop to 0 (since, short of injecting our own driver, we **cannot** get any insight into the actual writes that are going to the USB media).

In sort, if you are hoping to get more insight into what's being written during the time when Rufus does not appear to report progress when copying a large file, you are **not** going to get what you want, no matter how many more "speed indicators" Rufus adds...
