### ISSUE TITLE
Question: `unattend.xml` - `Microsoft-Windows-SecureStartup-FilterDriver`

### ISSUE THREAD

**Issue by Obegg** [pbatard/rufus#2612]
When using Rufus and selecting to disable Bitlocker encryption, the following value is added to `unattend.xml`:
```xml
    <component name="Microsoft-Windows-SecureStartup-FilterDriver" processorArchitecture="amd64" language="neutral" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" publicKeyToken="31bf3856ad364e35" versionScope="nonSxS">
      <PreventDeviceEncryption>true</PreventDeviceEncryption>
    </component>
```
But when reading the Microsoft page regarding `Microsoft-Windows-SecureStartup-FilterDriver` which can be found here: https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-securestartup-filterdriver
It clearly says:
```
These settings are intended for OEM manufacturing only.
```
and also:
```
Do not use these settings for standard 32-bit or 64-bit hardware architectures.
```
But also:
```
These settings only apply to Windows 8.
```

So my question is how true is the information on the Microsoft page, and if this value is even necessary (Windows 10 64-bit)?

**Comment by pbatard** [comment]
I'll take direct testing that validated these settings over whatever some page on the internet claims, **even** if it comes to Microsoft.

So, unless you have data, that you have actually tested, that appears to invalidate what Rufus is doing, as opposed to some interpretation of what a page from Microsoft's website, that has not been updated since Windows 8, might actually mean, I'm going to continue to take empirical evidence over attempted interpretation.

**Comment by pbatard** [comment]
xmlns is mostly for XML parsers. It's good to have them but by now means a requirement. It is **much preferred** to leave them, as it can make parsing **and validating** an XML file a lot less troublesome...
