### ISSUE TITLE
[Feature request] arm32 builds using clang

### ISSUE THREAD

**Issue by erkinalp** [pbatard/rufus#2629]
# Checklist

- [x] I have been made aware that if my problem can be summarized as _"I've created or tried to create a media using Rufus, and ..."_, and I am not including a log, **this issue will be summarily closed**.
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.
(No log here, because I'm reporting a feature request, not a bug)

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

# Issue description

> Well, I have better things to do then try to maintain platforms in the process of being deprecated, so I'll let the people who care about Rufus on ARM32 propose a non-intrusive workaround that can work with current GitHub Actions.

I hereby propose using the latest Windows SDK snapshot with ARM32 support and clang.

**Comment by pbatard** [comment]
Okay, the way I see it is that, whatever we try here, we are only going to delay the **inevitable** which is that ARM32 is being deprecated and should be seen in the same way as Windows on ALPHA, Windows on MIPS, Windows on IA64 (which is different than Windows on x64) and so on (I think PowerPC was also there at one stage).

Microsoft are clearly not planning to support ARM32 any longer, and I don't personally see a good investment to try to support it either.

So, I am planning to completely drop ARM32 support for Rufus, and I will ask people who care about ARM32 to sort out support for that platform in their own fork.

And yes, I appreciate that it sucks for the limited number of people who are still using Windows on ARM32, but considering that Microsoft never released Windows 11 for ARM32, which officially meant that, ever since 2021 Microsoft no longer saw ARM32 as viable platform, and that you still got 3 years of Rufus on ARM32 past that date, I think it's actually fair to discontinue ARM32 support in Rufus now rather than try to hang on hacks and more and more custom tweaking of the toolchains.

**Comment by erkinalp** [comment]
ReactOS will, though.

26 Kasım 2024 22:57:51 GMT+03:00 tarihinde Pete Batard ***@***.***> yazdı:

**Comment by pbatard** [comment]
> ReactOS will, though.

Well, ReactOS is still trying to match compatibility with Windows 7 as their main goal. By nature, ReactOS is always 1 or 2 cycle behind the current release of Windows and moving very slowly (they were still in the process of making Rufus run on ReactOS, and finding they were missing Windows 7 APIs by the time I had dropped support for Windows 7).

At any rate, it means that some people on the ReactOS team have time for ARM32. Good for them. I'm afraid that, in light of all the other things I could use that time on, I simply don't have this luxury.
