### ISSUE TITLE
This option "Create extended label and icon files" does not work.

### ISSUE THREAD

**Issue by GabrielMGitHub** [pbatard/rufus#2632]
Checklist
---------
- [ ] I have been made aware that if my problem can be summarized as _"I've created or tried to create a media using Rufus, and ..."_, and I am not including a log, **this issue will be summarily closed**.
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
From what I understand, selecting this option will recreate another autorun.inf file, which will contain the name of the pendrive and the path to the icon, which will be the same as the Rufus application.

I left this option enabled and used both the Windows 10/11 ISO in GPT and MBR mode, both in NTFS. No other autorun.inf file or icon was created. The autorun copied to the pendrive was the same one found inside the Windows ISOs.

Log
Too big and not added

The question is:

1- If Rufus identifies that the autorun file already exists, isn't it created?

2- What does create an extended label mean? Does it refer to the name included in the autorun.inf file "LABEL"?

**Comment by pbatard** [comment]
That's by design. Extended labels are mostly for blank drives that you format yourself, as it is usually ill-advised to try to change the label you got from an image, since the boot process may rely on seeing that specific label to locate the drive.

At any rate, if Rufus sees an existing `autorun.inf` it does not try to alter it but copies it as is.

As to your other question, please see https://github.com/pbatard/rufus/wiki/FAQ#why-does-rufus-create-an-autoruninf-file-isnt-that-dangerous, that details the content of `autorun.inf`.

But really the point is, if you already have an `autorun.inf` from your image, you shouldn't expect Rufus to alter it, even if you selected the "Create extended label" option.
