### ISSUE TITLE
Rufus doesn't support JMicron card readers

### ISSUE THREAD

**Issue by kddlb** [pbatard/rufus#334]
My laptop has an integrated SD card reader --made by JMicron--, and it doesn't show up on Rufus. Not even when "show USB hard drives" is checked.

**Comment by Herst** [comment]
That's quite a bummer, applies to my "Realtek PCIE CardReader" as well.
I think it's worth noting that the GPL "Universal USB Installer" does support it and detects my SD even without "Show all Drives" being checked, so I guess they might have some smart detection (checking whether Windows considers a device "removable" perhaps?).

**Comment by pbatard** [comment]
By default (All Drives unchecked) Universal USB Installer calls NSIS's [`GetDrives` function](http://nsis.sourceforge.net/GetDrives), with parameter `FDD`,  which in parts calls Microsoft's [`GetDriveType`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364939.aspx), to eliminate drives where the NSIS parameter doesn't match. As NSIS' `FDD` maps to Microsoft's `DRIVE_REMOVABLE`, this in effect, and as you correctly supposed, means that by default, Universal USB Installer will list all drives that have the removable attribute.

Now, my problem with that is that, if someone plugs an important backup drive on an eSATA port (or something that supports PCI Express hotplug), I fully expect that drive to have the removable attribute too. And, to my current knowledge, there is no attribute that Windows provides to indicate, with 100% certainty, whether a drive that got enumerated through the Windows APIs, and that does have the removable attribute, is a card reader, or an SSD or even a SATA drive.

This means that, a long as I have no means to conclusively tell if a drive is really an SD card, or a removable SSD/HDD, with important data, that someone plugged, I will not take the risk of enumerating such a drive Rufus. That's because I'd much rather inconvenience a handful of people who'd like to format an SD card, but won't lose any data if I don't allow them, than inconvenience people who might lose very important data by formatting the wrong drive by mistake (even if it's really __their__ mistake).

At the moment, the only safe way I see to allow the listing of PCI card readers in Rufus would be to do something similar to what is already being done for VHDs, and enable only card-reader controllers that we __know__, [through their hardware IDs](https://github.com/pbatard/rufus/blob/master/src/usb.c#L124-L127). My problem however is that I don't have any non USB card readers to validate if this is a feasible solution, and even if that is feasible, I expect that there is probably a large number of hardware IDs that would need to be gathered (and __maintained__) to keep people happy with card reader support in Rufus...

As such, I don't think I'll be spending time adding non USB card reader support in Rufus.

**Comment by Herst** [comment]
Great answer thanks and I totally get what your point. Now you could hide support for it through a some power keys combination just like for USB HDDs but I guess you're right in that since this feature is so rarely needed that it's not worth being implemented. Most certainly the hardware whitelist would be an overkill.
Thank you again.

**Comment by pbatard** [comment]
Can I just ask you for one more thing, so that I have as much data as I can with regards to non-USB card readers?

With a card in your card reader, can you please run Rufus, press <kbd>Alt</kbd>-<kbd>.</kbd> (you should see `USB Debug Enabled` at the bottom) and then copy/paste the log here?

I'm especially interested in seeing the kind of `SCSI\DiskXXXXXXXXXXXXXX` ID your card reader will generate. Having this may help try to figure if there's a (relatively) safe way to add non-USB card readers support.

Oh, and for the record, I confirmed that SATA drives plugged as eSATA are reported as removable, at least when testing the disk device itself (using `SetupDiGetDeviceRegistryProperty()` with parameter `SPDRP_REMOVAL_POLICY`). When testing with a mounted partition (which is what `GetDriveType()` takes as parameter), you do get `DRIVE_FIXED` for eSATA, so I guess Universal USB Installer will still eliminate them, as it works with a mounted drive letter. But then the problem is you can't really use that method if your device is blank, or has a partition using a file system that Windows cannot mount (e.g. Linux ext#)...

**Comment by pbatard** [comment]
I've been experimenting with a few more things to try to allow the listing of card readers by default (while eliminating eSATA and other non USB removable drives), so if you feel like it, I have a [test version of Rufus](https://rufus.akeo.ie/testing/rufus-2.7_TEST8.exe) for you to try. I expect this will list your card reader.

Note however that, if that works, I am not planning to integrate this patch into Rufus 2.7, as it's too close to release at this stage. But I will be considering it for Rufus 2.8.

**Comment by Herst** [comment]
Tested with latest stable now: My Card Reader wasn't listed in that log at all, only my internal SSDs. I guess because my device path is `PCI\VEN_10EC&DEV_522A&SUBSYS_504817AA&REV_01` (it starts with "PCI", not "SCSI").

> But then the problem is you can't really use that method if your device is blank, or has a partition using a file system that Windows cannot mount (e.g. Linux ext#)...

Or no partition table at all (sometimes referred to as "loop"), although I am not sure how Windows handles it all.

**Comment by pbatard** [comment]
Can you please use the <kbd>Alt</kbd>-<kbd>.</kbd> shortcut and copy/paste your full log?

What I am interested in are lines that start with `Processing Device:` which you will only see when Debug mode is enabled (and yes, even a PCI device should start with `SCSI\Disk....` &mdash; there are many different paths referencing the same device). Again, you will only see this content __after__ you press <kbd>Alt</kbd>-<kbd>.</kbd> in Rufus.

**Comment by Herst** [comment]
OK, I am currently on a different device and here the detection works, will post the log of the PC with the Realtek reader later.

Device No. 2:
```
Processing Hub 1:
Processing Hub 2:
Processing Hub 3:
  Hub[1] = '\\?\usb#root_hub20#4&1cc8b60&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[189]: USB\VID_8087&PID_8009\5&DFA438D&0&1
Processing Hub 4:
  Hub[2] = '\\?\usb#root_hub30#4&291bc6d2&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[109]: USB\VID_0BDA&PID_0327\201312261010
  Found ID[027]: USB\VID_045E&PID_00DB\5&8498A73&0&4
  Found ID[178]: USB\VID_046D&PID_C069\5&8498A73&0&11
Processing Hub 5:
  Hub[3] = '\\?\usb#root_hub20#4&abbcf3e&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[213]: USB\VID_8087&PID_8001\5&6E0A24C&0&1
Processing Device: 'USBSTOR\GenDisk'
Found USB device 'SDHC Card' (????:????)
Processing Device: 'SCSI\Disk_WD_____WD10EZEX-60M2NA001.0'
  Non USB => Eliminated
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 3881, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive has an unknown Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 29.7 GB (31925993472 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
```

**Comment by Herst** [comment]
And now here from again another device, this time with an "Intel SD Host Controller":
```
Processing Hub 1:
  Hub[1] = '\\?\usb#root_hub30#4&48210f7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[023]: USB\VID_1286&PID_204C\0000000000000000
  Found ID[132]: USB\VID_045E&PID_07DE\5&26F3984C&0&3
0 devices found
```

**Comment by pbatard** [comment]
Much appreciated!

I think the Realtek USB in your first log is the `USBSTOR\GenDisk` that produces the line `Found USB device 'SDHC Card' (????:????)`. As per its VID, `USB\VID_0BDA&PID_0327\201312261010` is most certainly a Realtek device so that has to be it. But if the device doesn't have a card inserted, it will be eliminated (though I would have expected a message that says so further down, and I'm also trying to figure out why the VID:PID could not be resolved). Be also mindful that if Rufus identified that device as an HDD, which is more probable if it can't get get VID:PID of the device, you may have to also enable HDD listing, which you can either do through <kdb>Alt</kbd>-</kbd>F</kbd> or by clicking the white triangle in the UI and then checking the appropriate option in the advanced panel. But you should always get a message about a device being eliminated because it was detected as an HDD in the Rufus log.

Still I have some ideas of Can I please ask you to run new tests with [rufus-2.7_TEST9.exe](https://rufus.akeo.ie/testing/rufus-2.7_TEST9.exe) and copy/paste the logs you get again? Note that you shouldn't have to press <kdb>Alt</kbd>-</kbd>.</kbd> again, as once debug mode is enabled, it is persisted (until you manually disable it).

**Comment by Herst** [comment]
Device No.2 with TEST9 (note that last time I disconnected some devices which I did not before, that's why so will now suddenly see them):
```
Rufus version: 2.7.854 (Test9)
Windows version: Windows 10 64-bit (Build 10586)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
Processing Hub 1:
  Hub[1] = '\\?\usb#vid_2109&pid_8110#5&8498a73&0&17#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[067]: USB\VID_0B95&PID_1790\00000000000001
  Found ID[034]: USB\VID_0B95&PID_1790\6&5A74B14&0&2
Processing Hub 2:
Processing Hub 3:
Processing Hub 4:
Processing Hub 5:
  Hub[2] = '\\?\usb#root_hub20#4&1cc8b60&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[189]: USB\VID_8087&PID_8009\5&DFA438D&0&1
Processing Hub 6:
  Hub[3] = '\\?\usb#root_hub30#4&291bc6d2&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[109]: USB\VID_0BDA&PID_0327\201312261010
  Found ID[027]: USB\VID_045E&PID_00DB\5&8498A73&0&4
  Found ID[178]: USB\VID_046D&PID_C069\5&8498A73&0&11
  Found ID[068]: USB\VID_2109&PID_8110\5&8498A73&0&17
  Found ID[003]: USB\VID_2109&PID_2811\5&8498A73&0&6
  Found ID[048]: USB\VID_0D28&PID_0204\220102030E3CAC05F3C071FC
Processing Hub 7:
  Hub[4] = '\\?\usb#root_hub20#4&abbcf3e&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[213]: USB\VID_8087&PID_8001\5&6E0A24C&0&1
Processing IDs belonging to USBSTOR:
  USB\VID_0D28&PID_0204&MI_00\220102030E3CAC05F3C071FC
ENUM 'USBSTOR'
Processing Device: 'USBSTOR\DiskMBED____microcontroller_1.0_'
  Matched with ID[167]: USB\VID_0D28&PID_0204&MI_00\220102030E3CAC05F3C071FC
  Matched with (GP) ID[048]: USB\VID_0D28&PID_0204\220102030E3CAC05F3C071FC
  Matched with Hub[3]: '\\?\usb#root_hub30#4&291bc6d2&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
Found USB 1.1 device 'MBED microcontroller USB Device' (0D28:0204)
ENUM 'USBSTOR'
Processing Device: 'USBSTOR\GenDisk'
Found USB device 'SDHC Card' (????:????)
ENUM 'SCSI'
Processing Device: 'SCSI\Disk_WD_____WD10EZEX-60M2NA001.0'
  Non USB or non removable => Eliminated
2 devices found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 304, TracksPerCylinder: 1, SectorsPerTrack: 1
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive has an unknown Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 152 KB (155648 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Device was eliminated because it is smaller than 8 MB
No file system is selectable for this drive
```

**Comment by Herst** [comment]
TEST9 on Device No.3:
```
Rufus version: 2.7.854 (Test9)
Windows version: Windows 10 64-bit (Build 10586)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
Processing Hub 1:
  Hub[1] = '\\?\usb#root_hub30#4&48210f7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[132]: USB\VID_045E&PID_07DE\5&26F3984C&0&3
  Found ID[023]: USB\VID_1286&PID_204C\0000000000000000
ENUM 'SD'
ENUM 'SD'
0 devices found
```

**Comment by pbatard** [comment]
Many thanks again for bearing with these tests. I think I should be able to work out something for Device No.3 (or at least, I now have a very good idea why the SD devices are not being listed there, and what might be done to remedy that).
But that `USBSTOR\GenDisk` SD card reader on Device No.2 looks like a tricky little bugger.

One thing I don't get is that despite the fact that its ID explicitly mentions `USBSTOR` later on, when we do list the `USBSTOR` devices earlier, the only one we get listed is your mbed device:
```
Processing IDs belonging to USBSTOR:
  USB\VID_0D28&PID_0204&MI_00\220102030E3CAC05F3C071FC
```

If you device really identifies itself as USBSTOR, this list should also have `USB\VID_0BDA&PID_0327\201312261010` or something similar in there.

Before I craft a new TEST release, can I please ask you to do the following?
1. Open Device Manager and go to View &rarr; Device By Connections
2. Navigate the tree until you find your device. It may be listed as something like _SDHC Card_. See screenshot below (where my USB card reader device is listed as _Generic STORAGE DEVICE USB Device_).
3. Now navigate to the device above (which may or may not be listed as _USB Mass Storage Device_) and right click to access its _Properties_. Then go to the _Details_ tab and select the `Service` property. I really like to see what you might have in there, as I get the feeling it may be something different than `USBSTOR`). I guess I'd also be interested to see a screenshot like this one, to give me a better idea of how how USB SDHC device is really set up.

![image1](https://cloud.githubusercontent.com/assets/1206968/13008144/83fcd8a2-d18c-11e5-9cd1-27a7226f1b56.png)

Hopefully this will get me a better idea of what I can do to sort out the detection on Device No.2.

**Comment by Herst** [comment]
Odd, I could only find the volume, not the device through the device manager:
![odd](https://cloud.githubusercontent.com/assets/1042176/13009188/46acdbe6-d19b-11e5-9a46-b094f872f5dd.png)

But going from the explorer I came to:
![odd2](https://cloud.githubusercontent.com/assets/1042176/13009293/0599e008-d19c-11e5-9548-e30aa885863e.png)
(USBSTOR\Disk&Ven_REALSIL&Prod_RTSUERLUN0&Rev_1.00\0000)

**Comment by pbatard** [comment]
Can you look again? You may have to expand many nodes before you locate your device.
As you point out in your last screenshot, there does exist an _SD Card_ disk device (and you should find that device listed in Task Manager in standard/View devices by type mode under the _Disk drives_ category). Therefore, since the View by connection does list the same thing, only organised differently,  this _SD Card_ device does exist somewhere in your tree. For instance, be mindful that USB devices might be listed under the PCI or PCI-Express bus, or even something else.

If you do see the _SD Card_ device under _Disk drives_ in regular view, it's definitely there in 'by connection' view.

**Comment by Herst** [comment]
Ah yes, you were right:
![thereitis](https://cloud.githubusercontent.com/assets/1042176/13012132/42ad1a24-d1aa-11e5-9a5d-435cfa4385a7.png)

**Comment by Herst** [comment]
Some info from Nirsoft's DevManView:

| Device Name | Manufacturer | Service | Device Type Code | Device Type Name | Device Instance ID | Location | Capabilities | Config Flags | Disabled | Connected | Device Registry Time 1 | Device Registry Time 2 | Drive Letter | Container ID | Driver Description | Driver Version | .inf File | .inf Section | Driver Date | Driver Registry Time |
|-------------|------------------------|---------|------------------|------------------|--------------------------------------------------------|----------|--------------|--------------|----------|-----------|------------------------|------------------------|--------------|----------------------------------------|--------------------|----------------|-----------|-----------------|-------------|----------------------|
| SD Card | (Standard disk drives) | disk | DiskDrive |  | USBSTOR\Disk&Ven_REALSIL&Prod_RTSUERLUN0&Rev_1.00\0000 |  | 0x00000014 | 0x00000000 | No | Yes | 20.11.2015 18:02:56 | 20.11.2015 18:02:56 | E:\ | {62188ec5-d126-014c-cf8e-aedbd7b28115} | Disk drive | 10.0.10586.0 | disk.inf | disk_install.NT | 21.06.2006 | 20.11.2015 18:02:56 |

**Comment by pbatard** [comment]
Glad you found it. The Service property I am interested in however is the one for _Realtek USB 3.0 Card Reader_, rather than the one for _SD Card_. Can you provide this value?

**Comment by Herst** [comment]
RTUSER :open_mouth: 

| Device Name | Manufacturer | Service | Device Type Code | Device Type Name | Device Instance ID | Location | Capabilities | Config Flags | Disabled | Connected | Device Registry Time 1 | Device Registry Time 2 | Drive Letter | Container ID | Driver Description | Driver Version | .inf File | .inf Section | Driver Date | Driver Registry Time |
|-----------------------------|---------------------------|---------|------------------|------------------|------------------------------------|----------------------|--------------|--------------|----------|-----------|------------------------|------------------------|--------------|----------------------------------------|-----------------------------|------------------|-----------|---------------------|-------------|----------------------|
| Realtek USB 3.0 Card Reader | Realtek Semiconduct Corp. | RTSUER | USB |  | USB\VID_0BDA&PID_0327\201312261010 | Port_#0018.Hub_#0003 | 0x00000090 | 0x00000000 | No | Yes | 20.11.2015 17:59:17 | 20.11.2015 17:58:40 |  | {00000000-0000-0000-ffff-ffffffffffff} | Realtek USB 3.0 Card Reader | 10.0.10125.31214 | oem71.inf | RSUER.USTOR.NTamd64 | 09.06.2015 | 20.11.2015 18:02:54 |

**Comment by pbatard** [comment]
Aha, this is starting to make sense now. And I am going to assume that it is really `RTSUER` as per the table (and what google seems to indicate) rather than RT<b>US</b>ER...

One one hand this will make adding card reader support a bit more tricky, as I'll have to ask users whose readers are not properly detected or populated to go into Device Manager and look for the service name, so that I can add it in Rufus. But on the other hand, this should make card reader detection safer (which I like), as it'll help filter out system drives.

Time for a new TEST 10 version [here](https://rufus.akeo.ie/testing/rufus-2.7_TEST10.exe), which I'm hoping will be able to list your devices on No.3, as well as properly populate the settings of your card reader on No.2. If possible, can I ask you to disconnect the mbed device or make sure you click on the _Device_ dropdown to confirm that the card reader is really missing. According to your earlier logs for No.2 Rufus did actually detect 2 devices (even if it couldn't resolve the VID:PID for the SD Card), which should translate to 2 devices being listed in the dropdown. However it is possible that the <8MB check, which utlimately eliminates the mbed, might interfere with the listing...

**Comment by Herst** [comment]
Device No. 2:

```Rufus version: 2.7.854 (Test10)
Windows version: Windows 10 64-bit (Build 10586)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
Processing Hub 1:
  Hub[1] = '\\?\usb#vid_2109&pid_8110#5&8498a73&0&17#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[067]: USB\VID_0B95&PID_1790\00000000000001
  Found ID[034]: USB\VID_0B95&PID_1790\6&5A74B14&0&2
Processing Hub 2:
Processing Hub 3:
Processing Hub 4:
Processing Hub 5:
  Hub[2] = '\\?\usb#root_hub20#4&1cc8b60&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[189]: USB\VID_8087&PID_8009\5&DFA438D&0&1
Processing Hub 6:
  Hub[3] = '\\?\usb#root_hub30#4&291bc6d2&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[109]: USB\VID_0BDA&PID_0327\201312261010
  Found ID[027]: USB\VID_045E&PID_00DB\5&8498A73&0&4
  Found ID[178]: USB\VID_046D&PID_C069\5&8498A73&0&11
  Found ID[068]: USB\VID_2109&PID_8110\5&8498A73&0&17
  Found ID[003]: USB\VID_2109&PID_2811\5&8498A73&0&6
Processing Hub 7:
  Hub[4] = '\\?\usb#root_hub20#4&abbcf3e&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[213]: USB\VID_8087&PID_8001\5&6E0A24C&0&1
Enumerating 'USBSTOR'
Processing Device: 'USBSTOR\GenDisk'
Found USB device 'SD Card' (????:????)
Enumerating 'SCSI'
Processing Device: 'SCSI\Disk_WD_____WD10EZEX-60M2NA001.0'
  Non USB or non removable => Eliminated
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 125, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive has an unknown Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 982.5 MB (1030225920 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
```

It can be selected and used (flashed FreeDos successfully).

**Comment by Herst** [comment]
Device 3 now:
```
Rufus version: 2.7.854 (Test10)
Windows version: Windows 10 64-bit (Build 10586)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
Processing Hub 1:
  Hub[1] = '\\?\usb#root_hub30#4&48210f7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[023]: USB\VID_1286&PID_204C\0000000000000000
  Found ID[132]: USB\VID_045E&PID_07DE\5&26F3984C&0&3
Enumerating 'SD'
Processing Device: 'SD\GenDisk'
Found Card Reader device 'Samsung MDGAGC'
Removing C: from the list: This is the system disk!
Enumerating 'SD'
Processing Device: 'SD\GenDisk'
Found Card Reader device 'Generic SD01G SD Card'
Using autorun.inf label for drive D: '1GB'
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 125, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x05FED164
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: FAT16 LBA (0x0e)
  Size: 981.5 MB (1029177344 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
```

**Comment by pbatard** [comment]
Great - thank you so much for these reports! :smile: 

I realize I still screwed up a little bit for No.2 (`Found USB device 'SD Card' (????:????)`), because I forgot to modify a section of the code that should also have been modified.

Mind trying [TEST11](https://rufus.akeo.ie/testing/rufus-2.7_TEST11.exe) on No.2 and post a log? I think I'll stop bothering you after that, as I'll need to clean up the code, regardless of the outcome...

**Comment by Herst** [comment]
Here you go, Device 2 again:

```
Rufus version: 2.7.854 (Test11)
Windows version: Windows 10 64-bit (Build 10586)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
Processing Hub 1:
  Hub[1] = '\\?\usb#vid_2109&pid_8110#5&8498a73&0&17#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[067]: USB\VID_0B95&PID_1790\00000000000001
  Found ID[034]: USB\VID_0B95&PID_1790\6&5A74B14&0&2
Processing Hub 2:
Processing Hub 3:
Processing Hub 4:
Processing Hub 5:
  Hub[2] = '\\?\usb#root_hub20#4&1cc8b60&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[189]: USB\VID_8087&PID_8009\5&DFA438D&0&1
Processing Hub 6:
  Hub[3] = '\\?\usb#root_hub30#4&291bc6d2&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[109]: USB\VID_0BDA&PID_0327\201312261010
  Found ID[027]: USB\VID_045E&PID_00DB\5&8498A73&0&4
  Found ID[178]: USB\VID_046D&PID_C069\5&8498A73&0&11
  Found ID[068]: USB\VID_2109&PID_8110\5&8498A73&0&17
  Found ID[003]: USB\VID_2109&PID_2811\5&8498A73&0&6
Processing Hub 7:
  Hub[4] = '\\?\usb#root_hub20#4&abbcf3e&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[213]: USB\VID_8087&PID_8001\5&6E0A24C&0&1
Processing IDs belonging to RTSUER:
  USB\VID_0BDA&PID_0327\201312261010
Enumerating 'SCSI'
Processing Device: 'SCSI\Disk_WD_____WD10EZEX-60M2NA001.0'
Could not get children of 'USB\VID_0BDA&PID_0327\201312261010'
  Non USB or non removable => Eliminated
0 devices found
```

**Comment by Herst** [comment]
OK, here you go, Device 2 again (forgot to add the insert the SD card before):
```
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
Processing Hub 1:
  Hub[1] = '\\?\usb#vid_2109&pid_8110#5&8498a73&0&17#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[067]: USB\VID_0B95&PID_1790\00000000000001
  Found ID[034]: USB\VID_0B95&PID_1790\6&5A74B14&0&2
Processing Hub 2:
Processing Hub 3:
Processing Hub 4:
Processing Hub 5:
  Hub[2] = '\\?\usb#root_hub20#4&1cc8b60&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[189]: USB\VID_8087&PID_8009\5&DFA438D&0&1
Processing Hub 6:
  Hub[3] = '\\?\usb#root_hub30#4&291bc6d2&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[109]: USB\VID_0BDA&PID_0327\201312261010
  Found ID[027]: USB\VID_045E&PID_00DB\5&8498A73&0&4
  Found ID[178]: USB\VID_046D&PID_C069\5&8498A73&0&11
  Found ID[068]: USB\VID_2109&PID_8110\5&8498A73&0&17
  Found ID[003]: USB\VID_2109&PID_2811\5&8498A73&0&6
Processing Hub 7:
  Hub[4] = '\\?\usb#root_hub20#4&abbcf3e&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[213]: USB\VID_8087&PID_8001\5&6E0A24C&0&1
Processing IDs belonging to RTSUER:
  USB\VID_0BDA&PID_0327\201312261010
Enumerating 'USBSTOR'
Processing Device: 'USBSTOR\GenDisk'
  Matched with ID[109]: USB\VID_0BDA&PID_0327\201312261010
  Matched with Hub[3]: '\\?\usb#root_hub30#4&291bc6d2&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
Found USB 3.0 device 'SD Card' (0BDA:0327)
Using autorun.inf label for drive E: '1GB'
Enumerating 'SCSI'
Processing Device: 'SCSI\Disk_WD_____WD10EZEX-60M2NA001.0'
  Non USB or non removable => Eliminated
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 125, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x0966F313
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: FAT16 LBA (0x0e)
  Size: 981.5 MB (1029177344 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
```

**Comment by pbatard** [comment]
```
Found USB 3.0 device 'SD Card' (0BDA:0327)
```
I like the look of that! And the earlier log you removed (without a card inserted) that reported a `Could not get children of 'USB\VID_0BDA&PID_0327\201312261010'` is also very interesting, as it may help report a more user friendly error message when there is no card.

I guess that's enough for today... Now I'll need to clean everything up so that I can add card reader support in Rufus 2.8.

But I really can't thank you enough for spending time with all these tests! :+1: You've probably helped countless users, who should be able to get their card reader supported at last, in a future version of Rufus. :smile_cat: 

Oh and no need to post the cardless log again - I have it in my inbox.

**Comment by Herst** [comment]
Great! Glad I could be of help.

Now that I'm back home I can post the log for device 1 (the one with the Realtek PCIE Reader):
```
Rufus version: 2.7.854 (Test11)
Windows version: Windows 10 64-bit (Build 10586)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
Processing Hub 1:
  Hub[1] = '\\?\usb#vid_8564&pid_4000#5&11cbd2d0&0&1#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[246]: USB\VID_0403&PID_6001\FTYO5SYU
Processing Hub 2:
Processing Hub 3:
  Hub[2] = '\\?\usb#root_hub30#4&1a0eaf57&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}'
  Found ID[208]: USB\VID_8086&PID_0A66\019150104604
  Found ID[093]: USB\VID_8564&PID_4000\5&11CBD2D0&0&1
  Found ID[165]: USB\VID_046D&PID_C07F\0A8034533934
  Found ID[019]: USB\VID_8564&PID_4000\5&11CBD2D0&0&13
Enumerating 'PCISTOR'
Enumerating 'SCSI'
Processing Device: 'SCSI\Disk_Samsun_SSD_850_EVO_250GEMT0'
  Non USB or non removable => Eliminated
Enumerating 'SCSI'
Processing Device: 'SCSI\Disk_Samsun_SSD_850_EVO_250GEMT0'
  Non USB or non removable => Eliminated
0 devices found
```

![another_service_id](https://cloud.githubusercontent.com/assets/1042176/13016995/502cfdc8-d1c2-11e5-87c9-6f89fa0b39d8.png)

SD card not available to Rufus.

**Comment by pbatard** [comment]
Thanks for the new report. By the looks of it, I'll need to add `PCISTOR` to the list of non-USB disk storage devices that Rufus enumerates for card readers.
I don't think I'll need `RTSPER` as, this time, it's not a USB device &mdash; but it sure doesn't hurt to have the full picture...

> Please tell me if I should continue posting in the other thread.

It's up to you. Maybe it's better to use the new thread, as it'll be more explicit this way.

I may wait until Rufus 2.7 is out (hopefully this Sunday) before I release a new version for you to test, if you feel like it. I'll definitely post again when it's ready to let you know.
