### ISSUE TITLE
Check device takes weeks, and can't abort or shut down

### ISSUE THREAD

**Issue by HenryS137** [pbatard/rufus#372]
I had a new 32GB SDHC card which I planned on using a lot, and I decided to experiment with your format option of "check device for bad blocks". I had already done a quick check under Windows.

Progress was extremely slow, but when I tried to abort the check it said that it would make the card unusable.  So I continued the check for about four days, at which point it was about 40% of the way through the first pass, when I had to abort because Windows 8.1 was forcing a shutdown for a forced update.

When I tried the card after rebooting, it would not format or accept any operations.

To be forced to tie up a PC for weeks or ruin a card is NOT a good forced choice for your users without any warning.

Other than this, I have been a very happy user, and have preferred your utility to any of the other alternatives, many of which I have tried.  I am using 1.4.10.514 on a very fast PC.

**Comment by GlassedSilver** [comment]
I just ran into this myself... No matter the hardware involved, the potential that this might leave the computer busy for a VERY long time should certainly be noted beforehand and CERTAINLY that cancelling - for whatever reason - is by design "uninterruptible".

This ticket was opened over 3 years ago... whew!
