### ISSUE TITLE
Possibility to not format the drive

### ISSUE THREAD

**Issue by eddy-geek** [pbatard/rufus#495]
Most other [inferior ;-)] tools allow to keep existing data on the drive (provided it's already formatted FAT32 I guess).

Is there any reason why this is not possible with rufus ?

From what I understand, at least for writing a bootable iso on the drive, only the boot sector of the existing partition needs to be changed to point to syslinux or whatever, right ?

I did not find anything related to this in the FAQ, though it should become more and more relevant with the increasing pendrive size (takes longer to backup the content)

**Comment by pbatard** [comment]
This has been asked on regular basis.
While it would be possible for __very specific__ cases, trying to do so is actually a __MAJOR__ problem because:
1. Rufus uses NTFS for Windows installations (so that >4GB files are not a problem, and so that BIOS vs EFI boot can be controlled) whereas Linux uses FAT32. So anyone who switches between Linux or Windows will have to reformat their drives anyway.
2. Not all formatting tool will leave the 1MB gap before the first partition, which ensures greater boot compatibility on various systems. I'd rather not have to try to second guess that someone's USB didn't boot because their drive was not partitioned with the proper compatibility settings.
3. Even if you are going to use the same file system as the one your drive is currently formatted in, you may want to switch between GPT and MBR partition scheme. That's not gonna happen unless you destroy the existing partition
4. Depending on your options, Rufus may add an extra partition. Resizing partitions is no fun.
5. __MOST IMPORTANT REASON:__ When one of the numerous people who don't know much about booting, partition schemes, and why this whole process can be so fraught with failure, asks me for support, at the very least I have a very good idea of how their drive was partitioned, how the file system was created, and how various other settings are set, so I don't have to spend an extra half an hour, __which I don't have__, asking them about some of the settings that might be critical to the boot process. The more you can ensure everybody starts with the same initial conditions, the easier it is to support. As far as I'm concerned, letting people fiddle with different initial conditions is like having the Olympic 100m sprint allowing sprinters to start from wherever they like, instead of the same common line. Provided that you can account for wind (in case sprinters decide to run in opposite directions), bends and whatnot, it's doable, but it creates an awful mess. Better have everyone run from the same line, in the same direction.
