### ISSUE TITLE
Unsupported ISO file from vmware "CPU Identification Utility"

### ISSUE THREAD

**Issue by lizard6** [pbatard/rufus#497]
Rufus is not be able to create a bootable disk using the ISO downloadable here : 
https://my.vmware.com/group/vmware/details?dlg=cpu_identification_utility&baseCode=ZHcqYmR0dGhidGR3#

**Comment by pbatard** [comment]
I'll see what I can do.

**Comment by lizard6** [comment]
Thank you in advance





        Sent by Outlook for Android




On Mon, May 4, 2015 at 5:24 AM -0700, "Pete Batard" <notifications@github.com> wrote:
I'll see what I can do.

---

**Comment by pbatard** [comment]
Unfortunately, while this ISO seems `Grub4DOS` based, it is missing `grldr` (which is why it isn't properly detected). So it probably uses some hybrid version of Grub 0.x, which trying to detect and add automatic support for (using Grub4DOS) looks like much more work than I'm willing to commit for an image that is unlikely to be used that much.

Note that you should might still be able to get that ISO to boot from USB by first installing `Grub4DOS` to your USB (click on the white triangle to get to advanced mode, which allows the installation of a bare `Grub4DOS`), and then copying the content of the ISO to the USB. But as with any boot process that was custom designed for an ISO, there's no guarantee that it will work (which is why I don't really want to go out of my way to try to support those).

I will close this issue now.
