### ISSUE TITLE
False ISO extraction failure after applying Win2Go image

### ISSUE THREAD

**Issue by Magendanz** [pbatard/rufus#523]
Creating Windows To Go from Windows 10 Build 10130 ISO image running on Windows 10 Build 10130 fails during bcdboot fixup. but reports ISO extraction failure.  Looking at the log, the ISO was successfully mounted and install.wim applied and closed.

Actual error was [c000015c] on 'bcdboot.exe D:\Windows /f ALL /s D:' command.  I'd love to hear an hints to work around the bcdboot failure, but Rufus should at least report a more appropriate effort message.

**Comment by pbatard** [comment]
Thanks for the report. A few things:
0. A __FULL__ log __ALWAYS__ helps.
1. Windows 10 To Go is experimental at this stage. As a matter of fact, I have never managed to get Windows 10 To Go x64, __even when using the Microsoft tool from Windows 10 Enterprise__. Please see the [specific Windows To Go entry in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Windows_To_Go_issues).
2. Rufus is aimed at regular users. I don't believe that reporting something about `bcdboot.exe` will speak to much of anyone. The error did happen during the ISO extraction (using the `bcdboot.exe` from the ISO) and if you want to find out more, that's what the log is for. As you indicated, you got a the full error from the log.
3. Any message that gets reported to users needs to get translated in 35 languages. This is a __MAJOR__ undertaking (because then I need to follow up with 35 translators, which takes __A LOT__ of time away from actual development) so I tend to limit the amount of messages that need to get translated. If a message that's already translated is close enough, that's what I'll use.
4. I'll be working on improving Windows To Go support for Windows 10 in the next version of Rufus (#453). However, as long as Windows 10 has not been officially released, and even the official Microsoft To Go creation tool seems to have trouble, it's hard to work with something that doesn't seem to have been entirely finalized yet. As a matter of fact, getting that message from the exact same version of Windows you are trying to create a To Go drive for seems to indicate that Microsoft may have some more finalizing to do.
