### ISSUE TITLE
Создание программы по дополнительной функции

### ISSUE THREAD

**Issue by deniska19982011** [pbatard/rufus#557]
Нужно создать программу(дополнение, интегрированное в rufus) по форматированию флешки после того как образ windows xp\vista\7\8.1\10 установлен на компьютер............
Скорее всего устанавливать образы будут с Flash накопителя!!!!
Спасибо за внимание!!!!!!

**Comment by pbatard** [comment]
Yes, because there are many cases when it is necessary (e.g. switching between MBR and GPT, or adding the extra partition for UEFI:NTFS) and also, most importantly, starting from a __known__ set of conditions rather than hoping that users have formatted their drives in a manner that will work is how we ensure __reliability__. Don't forget that the 'R' in Rufus stands for _Reliable_. If we were to try to reuse the existing partitions without formatting the drive, we would lose much of that reliability...
