### ISSUE TITLE
asus motherboard problem

### ISSUE THREAD

**Issue by Imee** [pbatard/rufus#564]
I have a desktop with asus p5sd2-vm motherboard, a sata hdd with windows xp os. At first it was working fine it can boot at windows xp. Then i used it to check my other ide hdd so i connected it that desktop and boots up. After that i remove the ide hdd then start booting up that desktop with the old sata hdd. It can detect the hdd but it doesn't continue to boot up anymore with windows xp. Need help . . Is there a special  mode so that it will boot on the old sata hdd?

**Comment by pbatard** [comment]
I'm sorry but this is not a hardware help forum. This issue tracker should be used if you have an issue with Rufus or want to request an enhancement.

Also, I have specifically [stopped supporting Windows XP installation issues ever since Microsoft retired that Operating System last year](https://github.com/pbatard/rufus/wiki/FAQ#Windows_XP_installation_issues).

I'm afraid you will have to bring your question somewhere else.
