### ISSUE TITLE
Cannot format a large disk as FAT to boot MS-DOS

### ISSUE THREAD

**Issue by steve6375** [pbatard/rufus#57]
There is a dropdown list for size, but this cannot be changed by the user.
What is the purpose of the selection list if you cannot change the size?

I have a large USB HDD and I want to boot it to MS-DOS - how do I do this?

**Comment by Lord-Nightmare** [comment]
"not many people have >32GB USB sticks."
As I've encountered today, this is no longer true. I have a 32GB stick and need to make a DOS bootable usb stick to flash a computer's bios, yet due to the size limitation, rufus refuses to allow freedos to be installed on the USB stick. I cannot easily obtain USB sticks smaller than 32GB locally, so maybe make it pop a warning up if you select freedos and a >=32gb device, rather than outright forbidding it?

**Comment by pbatard** [comment]
Okay. I may try to look into this (#647). But don't expect anything fast...

**Comment by pbatard** [comment]
> yet due to the size limitation, rufus refuses to allow freedos to be installed on the USB stick.

Are you sure of this?!?

As per #647, I have looked into this but found no issue whatsoever using a 64GB or a 100GB USB drive with either FreeDOS or WinME DOS (which the MS-DOS version embedded in the Windows platforms Rufus supports).

Rufus definitely does NOT check for the target size before installing FreeDOS or MS-DOS, so if you couldn't install FreeDOS, it was probably due to something else (such as your USB being partitioned for GPT in the first place, in which case you have to switch to MBR, else of course DOS will not be proposed).

If you really do encounter an issue when booting a DOS bootable USB created by Rufus, I will kindly ask that you provide a __FULL__ log from Rufus, of how you created your USB, using the very latest Rufus version.

**Comment by Lord-Nightmare** [comment]
I'm looking into it again. I was able to make it work using the 'vhd trick' as noted above to flash the bios on the system I had to do so on, but will check again after wiping the stick.
