### ISSUE TITLE
Add support of burning ISO into a primary partition of HDD.

### ISSUE THREAD

**Issue by evorios** [pbatard/rufus#571]
It's very useful for create emergency disk.

**Comment by pbatard** [comment]
Declined:

1. Allowing users to write disk partitions is __too dangerous__ as it introduces the risk of erasing important data by mistake
2. Doing this would require handling partitions rather than handling a whole disk, and ensuring that the existing boot loader isn't broken. This becomes really complex really fast and then __supporting__ this when it breaks or doesn't work as expected will be a massive time sink
3. You can already achieve this if you write to a VHD (which Rufus supports) that has the same size as your partition (which I assume will be small) and then write the VHD onto the partition itself.
4. Not enough people are going to use this to warrant the large investment it would require to add and support it (also see [here](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want_I_mean_youre_a_developer__it_shouldnt_be_that_hard))
