### ISSUE TITLE
Browsing iso in windows 10 ends up in not responding

### ISSUE THREAD

**Issue by khansharique** [pbatard/rufus#578]
Adding an iso image in windows 10 by clicking the browse icon made rufus not responding and then I have to force close it. Please fix it.

**Comment by pbatard** [comment]
I am using Windows 10 (and many others too) and I have never experienced this behaviour.
Therefore there is not much for me too fix since it seems to be specific to your environment.

Just for reference, Rufus gets downloaded more than 1.5 million times each month, so unless I receive multiple reports about issues such as yours, I can only consider them to be environmental and something I have no choice but to dismiss (since not being able to experience that behaviour makes it impossible to fix).
