### ISSUE TITLE
Used Rufus , what can I do ?

### ISSUE THREAD

**Issue by Zarnocs** [pbatard/rufus#583]
Hello everyone , sorry for the bad english from the start . I have an issue with my USB Stick its a hama of 32 GB .

I used it to make a bootable USB with Rufus and now my TV wont read it anymore , i tryed everything , formating it , making it NTFS FAT32 ... everything ... what can i do please tell me , show me a tutorial

**Comment by pbatard** [comment]
If your computer can read it and not your TV, clearly this is an issue with your TV. You should ask your TV manufacturer or other users of the same brand and model of your TV on how you should format your USB so that it can be recognized there. Most likely, there's a mention of the type of file system to use in your TV manual - have you looked there?

I suspect your TV probably only reads FAT32 filesystems. Maybe you need to uncheck the "Make disk bootable..." chekbox while formatting your drive as well.

Please spend some more time trying to reformat your drive as FAT32.
