### ISSUE TITLE
Windows XP x64 error iso file is not bootable

### ISSUE THREAD

**Issue by Aksam420** [pbatard/rufus#587]
File Name: en_win_xp_pro_x64_with_sp2_vl_x13-41611.iso
SHA1: cd9479e1dbad7f26b8bdcf97e4aa71cbb8de932b

**Comment by pbatard** [comment]
Windows XP x64 is NOT supported.
Also, as a whole, ever since Microsoft retired Windows XP more than a year ago, I am no longer planning to do any work related to XP in Rufus. If you want to use Windows XP with Rufus.

Please see [the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Windows_XP_installation_issues).
