### ISSUE TITLE
Rufus 2.4.757 - Error could not open media. It may be in use by another process.

### ISSUE THREAD

**Issue by Ninja243** [pbatard/rufus#608]
I've looked through a few threads and posts on Git and other websites, but I haven't found a fix yet. Ive tried closing everything (even Windows Explorer) and running it with Admin rights, but nothing has helped. Is there anything that I could have missed, or done, to get this working? 

Ninja243

```

Found USB 2.0 device 'Verbatim STORE N GO USB Device' (18A5:0302)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1882, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0xF8ABFC68
Drive has an unknown Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.4 GB (15480594432 bytes)
  Start Sector: 3184, Boot: No, Recognized: Yes
Will reuse 'ldlinux.sys' and 'ldlinux.bss' from './rufus_files/rufus_files/syslinux-6.03/' for Syslinux installation

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Could not get exclusive access to device \\.\PHYSICALDRIVE1: [0x00000005] Access is denied.

Found USB 2.0 device 'Verbatim STORE N GO USB Device' (18A5:0302)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1882, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0xF8ABFC68
Drive has an unknown Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.4 GB (15480594432 bytes)
  Start Sector: 3184, Boot: No, Recognized: Yes


```

**Comment by pbatard** [comment]
> Is there anything that I could have missed, or done

For a start, you shouldn't have truncated the log because I have no idea what version of Windows you are using, and what ISO you were using.

Also, it's always worth checking if there isn't a similar issue already opened (#605) for the same problem, __especially__ if it [sits at the top of the current issue list](https://github.com/pbatard/rufus/issues).

I'm going to close this issue as duplicate. If you want to follow up on it, please use #605.
