### ISSUE TITLE
Rufus extra partition type 0xEA

### ISSUE THREAD

**Issue by jenderek** [pbatard/rufus#609]
I used the partitioning+formatting tool product rufus 2.2.

This software has an extra format option for old BIOSes.
With this fix the main partition is created with some
alignments and for the remaining unallocated space 
a small extra and empty partition with identification 0xEA is created.

Unfortunately this option is not mentioned in text form on the web page.
It can be guessed by looking at the picture list_fixed_drive.png of rufus 
on the FAQ section.

Furthermore some partitioning software gets confused about this partition.
They display "Unknown" partition or refuse to resize partitions, because
they do not know how to handle partition type 0xEA.

Even worser there is a freedesktop proposal to use type 0xEA as boot
partition, see http://www.freedesktop.org/wiki/Specifications/BootLoaderSpec/

Best regards,
Jörg

**Comment by pbatard** [comment]
Hi Jorg,

On 2015-10-01 15:00, Jörg Jenderek wrote:
> This software has an extra format option for old BIOSes.

Which is not enabled by default and which is up to the *user* to enable.

> With this fix the main partition is created with some
> alignments and for the remaining unallocated space
> a small extra and empty partition with identification 0xEA is created.

Yes. Some BIOSes appear to need that.

> Unfortunately this option is not mentioned in text form on the web page.

If I were to mention every feature of Rufus in the web page, and get 
them translated in the 35 languages that the web page is currently 
translated, I would not have much time to code...

> It can be guessed by looking at the picture list_fixed_drive.png of rufus
> on the FAQ section.

Or by playing with the interface.
Again, the option is NOT enabled by default, so the fact that it is not 
displayed when starting Rufus shouldn't matter much: if you don't see 
that option, it shouldn't affect you.

Again, I fail to see how this option, which is never enabled by default, 
is a major problem.

> Furthermore some partitioning software gets confused about this partition.
> They display "Unknown" partition or refuse to resize partitions, because
> they do not know how to handle partition type 0xEA.

Well, you can always report to them that 0xEA is used by Rufus.

> Even worser there is a freedesktop proposal to use type 0xEA as boot
> partition, see
> http://www.freedesktop.org/wiki/Specifications/BootLoaderSpec/

Unfortunately for them, I think I can demonstrate that I started using 
0xEA before they did.

More seriously, the problem is that there are so few MBR partitions IDs 
left that, whatever you pick, you're sure to step on somebody else's 
foot. I looked hard at trying to pick an ID that wasn't being used. But 
of course, if somebody comes afterwards and says "Hey, we're gonna use 
this too", there's not much I can do, can I?

But then again, since it is NOT enabled by default, and I expect VERY 
FEW people to be using an obscure boot technology from an organization 
that is expected to have very little to do with boot (I fail to see how 
a group working on interoperability and shared technology for X Window 
System desktops needs to concern themselves with MBR boot types), I 
really don't see how this is an issue. Basically, you need to me mixing 
an OLD technology (a machine with an OLD BIOS that has the issue which 
the extra partition addresses) and NEW technology (the freedesktop 
proposal) to ever have a chance to be affected by this. As time passes, 
I don't expect many people to have any need to *manually* enable the 
fixes for old BIOSes, and therefore this looks like a complete non issue.

Then again, the day I get evidence from my users that people are using 
the freedesktop boot thing along with the fixes for old BIOSes in Rufus, 
I may reconsider...

Regards,

/Pete
