### ISSUE TITLE
This is not an issue but a request.

### ISSUE THREAD

**Issue by 0nesAndZer0s** [pbatard/rufus#665]
Would it be possible to list rufus cheat codes somewhere within the application, it was nice to see that zeroing a device was added as a feature but only enabled when using a cheat code, so I then googled away and found there were several rufus cheat codes that I was not aware of. Perhaps if these codes were attached to the software more users would be aware of them and rufus' full potential.

**Comment by pbatard** [comment]
This would mean translating this [whole FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Power_keysCheat_modes) into more than 35 languages, which would greatly increase the application size. And somehow, the users would have to be alerted to Rufus containing a usage guide, whereas I am trying to keep the interface to the minimal number of basic functions one needs to create a bootable USB.

What I'm trying to say here is that, the FAQ will have to do, because that's exactly what it's for. Also, cheat modes are cheat modes because they are not meant to be publicized too widely, as they are simply additional features, that __may__ be useful in specific situations or for advanced usage, but that haven't been as thoroughly tested as the main features and therefor __unsupported__ (i.e. if it works, great - if it doesn't, you're on your own).

I'll have to dismiss this request then.
