### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Maffblaster** [pbatard/rufus#681]
Hi Pete,

Do you think you could provide build instructions for building Rufus? Perhaps a list of dependencies? This could be either on the GitHub wiki or as a `CONTRIBUTING.md` file inside the main repository?

Thank you,
Matthew

**Comment by pbatard** [comment]
Well, first of all, Rufus will __not run__ on a Linux machine. It is a Windows application exclusively, and its source code is very Windows specific. So if your expectation is that by recompiling the source on Linux, you will get a Linux version of rufus, you will be very disappointed.

This means then that the only thing you will be able to accomplish on Linux is cross-compile a Windows version. But do that, all you need is MinGW, and doing the usual stuff one needs to do when cross-compiling (which is __not__ specific to Rufus).

You should be able to find plenty of guides on the internet telling you how to cross-compile a Windows application using MinGW on Linux. From there, it's really a matter of calling `autogen.sh`, `configure` and `make`.

Note however that, since I have no interest spending time ensuring that Rufus will compile properly in a MinGW environment on Linux, I will __not__ support you if you decide to try it, even if it turns out there exists something in the config files that needs to be fixed for it to work (but I will accept a patch proposal for such a fix if you have one).

Since I believe I have answered your question about performing an operation (compiling Rufus on Linux) which I do not officially support, I will close this call now.
