### ISSUE TITLE
Problem with disk

### ISSUE THREAD

**Issue by maddevil666** [pbatard/rufus#707]
Hi!
I run rufus 2.7.855 and he don't see my hd.

Log:
```
Rufus version: 2.7.855
Windows version: Windows 7 SP1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0415
Found USB 2.0 device 'WDC WD50 00LPVT-22G33T0 USB Device' (1BCF:0C31)
Device eliminated because it was detected as an USB Hard Drive (score 23 > 0)
If this device is not an USB Hard Drive, please e-mail the author of this application
NOTE: You can enable the listing of USB Hard Drives in 'Advanced Options' (after clicking the white triangle)
0 devices found
```
Please help me.

**Comment by pbatard** [comment]
Well, the log pretty much says why. Rufus is __designed__ to eliminate USB hard drives by default, so that someone who doesn't format an important backup drive by mistake, when they wanted to format a flash drive. Note that this is a very deliberate choice, as I __regularly__ receive mail from people who indicate that they formatted the wrong drive by mistake, and I'd rather inconvenience a few people by not listing some drives by default, while ensuring that no data will be lost as a result, than inconvenience people who are likely to lose important data if HDDs are listed by default.

[This FAQ entry](https://github.com/pbatard/rufus/wiki/FAQ#Help_my_USB_drive_is_not_detected) explain how to enable the listing of USB HDDs (which is the same way as what the log describes).

If that doesn't answer your query feel free to reopen this issue.
