### ISSUE TITLE
why ask for ISO file, why not write folder/ files

### ISSUE THREAD

**Issue by vsrawat** [pbatard/rufus#719]
It asks us to name an ISO file which it will write to the flash drive.

Now that CD-DVD are getting out of use, we don't really need iso files. Even if we downloaded a setup iso file, we extaract that so that we have individual files and folders of that iso on our hard disk. Then, to save space on hdd, we delete iso file. It should write that folder to the flash drive.

I mean why does it ask for ISO file? Eventually it is going to read that iso file and then unzip and then write to flash drive, so why doesn't it directly write the folder specified by us to the flash drive, considering the folder to be an extract of an iso file?

Today, I had w10 setup files extracted on my hdd, but as it had asked me for iso file only, I had to spend 3 hours searching net for a software that would create an iso file from folder/ files, and then I found Folder2ISO using which I created iso file, and then rufus could write that to flash drive, doing the reverse.

Thanks.

**Comment by pbatard** [comment]
> I mean why does it ask for ISO file?

Because that is __still__ what manufacturers provide.
Want to install a retail version of Windows? Then you're __NOT__ going to get a zip archive with the Windows installation content but an ISO. Want to install or run a live distro of Linux? Same thing.

Please be mindful of extrapolating your specific usage with having a bunch of custom Windows installation files (which were likely extracted from an ISO in the first place) already available and wanting to use those to create a bootable USB, and what __the vast majority others__ will be doing. As you state:

> Even if we downloaded a setup iso file, we extaract that so that we have individual files and folders of that iso on our hard disk

Well, that is a __very custom__ usage. As you probably understand, most people, and especially the ones that aren't tech-savvy, are not going to extract the ISO content when they get it. They're just going to keep the ISO. Besides, having everything in a single large file can be more convenient than having a bunch of files.

This being said, I used to have an enhancement for folder support in Rufus (#76), which I dropped, because after keeping it opened for years, and seeing no requests for it, I determined that the cost to benefit ratio was simply too high. In other words, as long as most OSes out there are distributed in the form of ISOs, which people are very unlikely to extract (because ISOs are not the same as archive files), then it's simply not worth adding a feature that will be both tricky and time consuming to support and implement to Rufus (see also [here](https://github.com/pbatard/rufus/wiki/FAQ#Why_cant_you_just_add_the_feature_I_want_I_mean_youre_a_developer__it_shouldnt_be_that_hard)).

If you want folder support, I will kindly ask you that you use a different application, because I have no plans to add such a feature in Rufus right now.
