### ISSUE TITLE
UDF Deletion Bit

### ISSUE THREAD

**Issue by pcdeem** [pbatard/rufus#771]
I used Rufus to copy a Windows 7 ISO to USB.
I had previously used a small app called eicfg_remover on the iso.

The app's readme says:
This works by toggling the deletion bit in the UDF file table, which instructs the operating system to ignore the file and to treat it as if it does not exist.
By not physically removing the file, this eliminates the need to rebuild the ISO, and makes this sort of fast, unintrustive patching possible. This also makes it possible to reverse the patch and to restore the image to its original state, if so desired.

---------------
When I burn the ISO to a DVD this works fine and I get a menu asking me which version of Windows to install.
When I use Rufus to copy the ISO to a USB stick it fails and I install the version that is set in ei.cfg with the version menu.
So I think perhaps Rufus is ignoring that deletion bit.

**Comment by pbatard** [comment]
Well, clearly `eicfg_remover` acts on the UDF file system, which is what most Windows ISO images use. Apparently it uses a specific UDF flag to mark a specific file as deleted.

However, when Rufus converts that bootable ISO to bootable USB, it converts the UDF file system to FAT32 or NTFS file system, and those file systems don't have a "delete" flag, therefore it is ignored, and the "deleted" file is copied regardless.

While you could argue that Rufus should actively look for all the files on an UDF file system that have the "delete" attribute, and either not copy or delete these files, I don't think I want to do that on account that:
* Because the USB is read/write, as opposed to the ISO, which is read-only, instead of relying on running `eicfg_remover`, it should be very easy for you to locate the file that `eicfg_remover` flags as "deleted" and remove it. I believe you can find that file in `sources\ei.cfg`. If you use Rufus, there's really no need to run `eicfg_remover`. Just delete `sources\ei.cfg` and it should achieve the same.
* I am only supporting official unaltered Microsoft ISOs. `eicfg_remover` does modify the official image, and therefore is not something I feel the need to support.
* Since it only seems to apply to Windows 7 (and not Windows 8.x or 10 - there's no `ei.cfg` file on those ISOs) I don't believe there will be that much demand for Rufus to carry the change applied by `eicfg_remover`, whihc makes the the cost/benefit ratio of implementing (and __supporting__) the feature too high in the long run.

I'm going to have to dismiss this request. But of course, if there happens to be a lot of demand for it (so far you're the first person to request it), I may reconsider.
