### ISSUE TITLE
Misleading download

### ISSUE THREAD

**Issue by account45** [pbatard/rufus#789]
The website where the executable is hosted now is serving misleading advertising with ~~malware~~ software of very dubious origin. Could the executable hosting be changed? I understand that it might provide additional funding needed to support the project, but I worry that, being the officially recommended method from Canonical and from Ubuntu (an OS for "the masses"), it might be misleading many people.

Here is the offending advertising with the big **START DOWNLOAD** button:

<img width="960" alt="fail" src="https://cloud.githubusercontent.com/assets/20232820/16506566/a0adc0a6-3f23-11e6-9c93-9105fb504229.png">

**Comment by pbatard** [comment]
Well, the problem is 100% with google ads, because they set an arbitrary limit on the number of categories you can filter out.

I complained to them many times about this, because if it was up to me, I'd have only the "technological" category open for ads, which, I am hoping, would filter out these kind of deceptive ads. However, if you've ever advertised with google ads, you'll see that they prevent people from tailoring exactly the ads they want their users to see, by setting a hard limit regarding the categories of ads one can eliminate.

I have done my best to remove the categories that I consider most likely to generate deceptive ads. But there's only so much I can do when the advertising platform is uncooperative. And I can't remove ads from the site either, as I want the software to remain free.

Then again, I do estimate that internet users need to be aware that there exist deceptive ads, and, further than that, I __actually__ tell any user who visits the Rufus web page how they can block ads altogether (see _"unless your are blocking them"_ part [here](https://rufus.akeo.ie/#donate)).

So I'm really doing the best I can. But there's only so much google will let one do, when their whole business model is based on users clicking as many ads as possible.

Oh, and if you read the homepage, you'll see that I am advocating for an Open Source Software development model where developers would not have to rely on ads or donations (and I really don't want to go the donations route). Sadly, not many people, and especially none of the companies who benefit the most from active OSS development, seem to want to subscribe to such a model.

So, my only advice is: If you are smart, you'll disable ads, or at the very least, you'll know that there exits deceptive ads that one should avoid blindly clicking onto. And if one has to learn this lesson the hard way (as far as I know, while they aren't doing much for deceptive ads, google __does__ actively look for ads that link to malware and are very proactive about removing them, so I don't believe a user clicking such an ad will be especially at risk) so be it.
