### ISSUE TITLE
Windows 10, UEFI and Surface-* devices.

### ISSUE THREAD

**Issue by artemsky** [pbatard/rufus#796]
Checklist
---------
- [ *] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [* ] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [*] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [empty_log] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Issue description
-----------------
Actually i have Surface Book.
And i wanted to install fresh copy of Windows 10.
And it accepts only FAT32 Formated Usb Media.

Rufus 2.9 can't force FAT32 Format for Windows 10 iso.
So i just suggest to add this feature into the next version.
GL)

**Comment by pbatard** [comment]
There's nothing to add in the next version - what you want is already there, you're just not aware of the option you need to select.

Your surface is UEFI so you need to select "GPT partition scheme for UEFI" under "Partition scheme and target system type" __after__ selecting your Windows 10 ISO. Otherwise BIOS mode is used, which is not compatible with your platform.

If that doesn't answer your question, feel free to reopen this issue.
