### ISSUE TITLE
Rufus USB access denied

### ISSUE THREAD

**Issue by coconut515** [pbatard/rufus#811]
I'm working on a project for work that I need to install Linux onto two computers that have had Dban run on them. I need Rufus to do this and it's not working. Version 2.10 won't run because it's claiming I need higher admin rights but Version 2.9.934 will run. However it won't accept any of the USB drives I'm using. First it says access to the USB is denied and then it says it doesn't report itself as a disk. I do have the "List USB Hard Drives" button checked.

Here's the full log:
Rufus version: 2.9.934
Windows version: Windows 7 SP1 32 bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta3
System locale ID: 0x0409
Will use default UI locale 0x0409
Found USB 2.0 device 'Kingston DT 101 II USB Device' (0951:1625)
Could not open '\\?\usbstor#disk&ven_kingston&prod_dt_101_ii&rev_1.00#00142225a589f9a186350efc&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}': [0x00000005] Access is denied.
A device was eliminated because it didn't report itself as a disk
0 devices found
Found USB 2.0 device 'Kingston DT 101 II USB Device' (0951:1625)
Could not open '\\?\usbstor#disk&ven_kingston&prod_dt_101_ii&rev_1.00#00142225a589f9a186350efc&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}': [0x00000005] Access is denied.
A device was eliminated because it didn't report itself as a disk
0 devices found

**Comment by aaronfranke** [comment]
What does it show up as in Disk Management?

**Comment by pbatard** [comment]
> version 2.10 won't run because it's claiming I need higher admin rights

Yes, otherwise you will get "Access denied" errors.

> but Version 2.9.934 will run

But produce the "Access denied" which means you don't have enough privileges, which is exactly why  Rufus 2.10 will refuse to run, as it can't magically raise your privileges if your account lacks them.

I see nothing that needs fixing here. Just make sure you use Rufus with an account that has enough privileges.

**Comment by coconut515** [comment]
I was just hoping that since 2.9 worked that I didn't need the higher privileges and that there was something wrong with the USB or rufus. Thanks anyway.

**Comment by pbatard** [comment]
> since 2.9 worked

Your problem is that this statement of yours, which you keep repeating, is incorrect.

2.9 didn't work. The application might launch, yes, but it wasn't able to do anything due to missing access right. So that's really not something one can call "working". Therefore, since it was impossible to accomplish anything in 2.9, I saw it better to ensure that 2.10 would not launch at all under the same conditions, to make it a lot more explicit that you __must__ have enough privileges to run Rufus.
