### ISSUE TITLE
User send report on error found in b994 - ISO image can't write's

### ISSUE THREAD

**Issue by VictorVG** [pbatard/rufus#829]
User **vitsat** on http://forum.ru-board.com/topic.cgi?forum=5&topic=38800&start=320#18 to report an error in b994:

![rufus210vs211](https://cloud.githubusercontent.com/assets/906886/18435720/868e604a-78fd-11e6-916e-024fe6110d54.png)

I did not check it on something, so just have to inform about its detection, and asked him to provide details on this issues

**Comment by pbatard** [comment]
From the [Changelog](https://github.com/pbatard/rufus/blob/c4b9ec4a627cd27a957169f64603a92d79155619/ChangeLog.txt#L7):
> Fix an issue that enabled FAT32 file system selection on some Windows images

This is a result of the fix for #813. Your guy should be using NTFS, not FAT32. There is no reason for using FAT32 with such images when NTFS will work, and it was creating issues, therefore FAT32 selection was __deliberately__ removed.
