### ISSUE TITLE
Antivirus-locked AUTORUN.INF triggers 'ISO image extraction failure'

### ISSUE THREAD

**Issue by sean-gugler** [pbatard/rufus#83]
SEVERITY:  minor inconvenience, user confusion

Antivirus software (such as Avira) may prohibit access to the file "AUTORUN.INF" on the root of a UFD.  When this happens, Rufus aborts the file-copy stage with a non-specific error dialog, "ISO image extraction failure".  Diagnosis efforts led me down several false paths before finding the culprit.

The error message should at least be clearer about which file it was unable to write.  The current wording misrepresents the ISO source file as the cause of failure.  Even better if it specifically noticed AUTORUN and suggested disabling antivirus software.  Better still, if this error dialog offered choices similar to "Abort, Retry, Ignore" then I could proceed with the rest of the files while investigating.

This caveat should maybe be mentioned in the documents, though hopefully future web searchers will at least find this bug report.

**Comment by Laro88** [comment]
Any chance that Rufus could show the desired content of the autorun.inf file so it would be possible to create it manually on the disk?

**Comment by pbatard** [comment]
Sorry but no. That would be a very custom feature added to work around a very specific problem that very very few people are expected to have (since a __properly__ designed security solution would be able to parse the content of the `autorun.inf` being written by Rufus and see that it is harmless since it doesn't invoke the launching of any executable).

As much as I'd like to help everybody, because my development time is limited and this is not a feature that is as easy to implement as you might think it is, I have to draw the line somewhere and concentrate on adding features that will help a majority of people. This, I'm afraid, is not one of them.

I would __strongly__ encourage you to raise that issue with your Antivirus software developer and advise them that a blanket prohibition on `autorun.inf` is blocking very legitimate uses, as opposed to only blocking `autorun.inf`'s that are actively launching an application.

Also, please remember that you can already disable the creation of the `autorun.inf` by Rufus altogether, if you uncheck the _Create extended label and icon file_ under _advanced format options_.

**Comment by Laro88** [comment]
I understand and acknowledge you lack of time :-)

We have a company enforced Trend Micro antivirus and I can't disable it (tried to but failed)

I finally created a bootable usb (MBR option) with Win10pro and it did start to install, however it failed mid-installation for no apparent reason. I will burn an install media and test the hw using a good old dvd.
