### ISSUE TITLE
[QUESTION] ISO Image Mode vs DD Image Mode

### ISSUE THREAD

**Issue by github2016github** [pbatard/rufus#843]
<PLEASE READ THIS CAREFULLY: You *MUST* read and complete the checklist below, by placing an x into each [ ], BEFORE clicking on 'Submit new issue'. Failure to perform these steps, WHICH ARE ONLY THERE TO HELP *YOU*, will result in the issue being dismissed without warning.>

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [x] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive
  - [ ] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [ ] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
For an Arch Linux ISO, could you please explain the overall difference, when creating a USB Flash Drive, between Rufus' ISO Image mode and it's DD Image (disk image) mode? I am trying to understand what steps Rufus goes through, depending on which mode is selected, and how that affects the outcome.

thanks,

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment]
DD is an exact clone of the image onto the USB. Basically, this flat copies the image byte by byte onto the USB, so if you look at the image in hex and see it starts with something like `33 ED 90 90 ...` then what Rufus or any other DD application will do is copy `33 ED 90 90 ...` onto the USB, starting at the first byte of the first sector, and continue to copy bytes until the data from the image is exhausted. That's all DD does, and it usually ensures that you get an exact clone of the image or device the maintainer of the distro created. 

One advantage is that it doesn't require partitioning or formatting, and it can create USB drives with file system that Windows is unable to handle on its own (such as ext# or anything FreeBSD). But this can also be one of the drawbacks, as it means you will usually find that you cannot access the content of your USB any longer after it has been created. So if you want to modify some settings, or want to access the doc, or, say, copy the firmware for your Wifi card onto the USB, you may not be able to do so. Also, even if you are able to access the content, you will find that the available size you have is a lot less than the total size of your USB. For instance, if you DD copy a 4GB image onto a 16GB USB, then even if you can access your drive from Windows, you will only ever be able to access 4GB of your drive, and not 16.

Finally, the choice between DD and ISO only applies to ISOHybrid images, which is a somewhat brittle __hack__ that tries to make optical disc filesystems (ISO9660 or UDF) something that they were never designed to do (which essentially boils down to making it look like a completely different file system, along with constructs, such as a partition table, that are not meant to apply to optical media), so it takes A LOT of trial and error to get something that kind of works, but has some limits.


On the other hand what ISO mode does is partition and format the USB in a way that Windows can always understand (and using the __whole__ capacity of the drive), and then copy each individual file and directory from the ISO image onto the newly created file system.

One of the drawback this has is that the boot loading and later process of the media has to be able to handle a Windows file system (usually FAT32, but it could be NTFS or exFAT), which may come with some limitations, but this is usually not an issue for something like an installation media.
Also, if you have a lot of small files the copy process in ISO mode can be a lot slower than the DD mode copy process. But as I pointed above, ISO mode also ensures that you can always access the full content of your USB.

If you want a quick analogy, you can consider that DD mode is similar to cloning a whole bookshelf into your living room. For some cases this may be the best option, but in others, you may find that this bookshelf is locked with a key that you don't have, and it has to sit right in the middle of your living room, which prevents you from installing a couch, or something.

On the other hand, ISO mode is akin to providing you with a bookshelf, which is tailored to the space you have against a wall of your choosing in your living room, and cloning books one by one into it. It's a bit more tedious and slow, but if you have a large wall, if will live you with a similarly large bookshelf, that you can use to put other books, and it also isn't locked, so you can always access both the books that were copied over, as well as any new book you put in it.

Hope that explains it, and also the reason why Rufus usually recommends to try using ISO mode first, and only use DD mode if you have an issue with ISO mode.

As far as Arch is concerned, ISO mode should work very well (because the Arch maintainers tend to be very good at what they are doing), but in the end it's really up to you to pick the mode you want.
