### ISSUE TITLE
Rufus 2.11 Not Running in Windows XP

### ISSUE THREAD

**Issue by davesgonechina** [pbatard/rufus#885]
My user account is an Administrator, but nothing happens. No errors, no popups, no other files generated.

**Comment by pbatard** [comment]
I'm afraid I have stopped supporting XP issues ever since Microsoft retired Windows XP more than 2 years ago. If Rufus works on XP (and as far as I know, it still should for most people). If it doesn't, you're on your own.

If you want to receive support with Rufus, I would strongly encourage you to use a version of Windows that is still supported by Microsoft.

I will close this issue now.
