### ISSUE TITLE
Hebrew Translation update

### ISSUE THREAD

**Issue by NSbuilder** [pbatard/rufus#890]
I sent the updated translation to your e-mail.
Also, the translation status claim the Hebrew translation appear on Rufus homepage but it doesn't
( https://github.com/pbatard/rufus/wiki/Translations-Status ).
(https://github.com/pbatard/rufus/issues/816) - it is not marked in the task list

**Comment by pbatard** [comment]
> I sent the updated translation to your e-mail.

Got it. I was just about to ask you to add the two new messages, so thanks for being proactive!

> Also, the translation status claim the Hebrew translation appear on Rufus homepage

No, the translation status only claims that the homepage itself has been translated into Hebrew, [which it has](https://rufus.akeo.ie/?locale=he_IL).

On the other hand, the task in #816 is to remind me to officially add Hebrew to the list of supported langauges (as well as a screenshot of the Rufus application running in Hebrew), on the day of the official release. I don't want to do that too early, as right now, only the BETA is available in Hebrew, and since the BETA is not publicised on the homepage, people might download Rufus 2.11, thinking it supports Hebrew, whereas it is not the case.

So, please don't worry, I made sure to leave a task open so that I don't forget to publicize that Hebrew is available, on the day of the 2.12 release. At any rate, many thanks for your work!
