### ISSUE TITLE
adding memdisk / grldr

### ISSUE THREAD

**Issue by JAF84** [pbatard/rufus#906]
Hello,

i use "memdisk" for some test tools i start from usb stick.

at the moment i use www.rmprepusb.com/tutorials/grub4dos
("Part 1" of the guide) for creating a bootable disk.

For me Rufus looks much nicer,
So i would prefer to create this with rufus.

When using "rmprepusb" there is bassically one one file ("grldr") on the Fat-Filesystem,
the other files are specific, so the filesystem is clean on the usb key.
(then i copy menu.lst, memdisk and some other files on the key)

Do you think this is possible with rufus?

BR Johannes

**Comment by pbatard** [comment]
How I wish people who request features didn't completely ignore the checklist and read the FAQ...

Rufus already allows you to install a blank Grub4DOS bootloader (which is where `grldr` comes from) and this is [mentioned in the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Advanced_Mode).

Because this is an advanced feature (that I don't want regular users to be confused about), it is only proposed when you run Rufus in advanced mode, i.e. after clicking the while triangle besides _Format Options_. If you are in advanced mode and have selected "MBR partition scheme for BIOS or UEFI" then you'll see a `Grub4DOS 0.4.6a` entry in _Create a bootable disk using_, which is what you want.

Closing as __already implemented__.
