### ISSUE TITLE
Chinese file name  Become gibberish

### ISSUE THREAD

**Issue by bowknot** [pbatard/rufus#917]
![01](https://cloud.githubusercontent.com/assets/11291839/24319074/af442622-114c-11e7-9a97-c88cbedae01f.jpg)

![02](https://cloud.githubusercontent.com/assets/11291839/24319117/59366e06-114d-11e7-9da9-9a57804f84c5.jpg)

**Comment by pbatard** [comment]
If you don't follow the checklist, and choose __not__ to provide the full log as requested, I will simply close this issue without looking at it.

**Comment by bowknot** [comment]
log:
[rufus.zip](https://github.com/pbatard/rufus/files/870121/rufus.zip)

**Comment by pbatard** [comment]
The ISO you are trying to use was mastered by relying on the computer it is being used on having the same codepage as the one it was created on, __instead of relying on Unicode_ (through properly formatted Joliet extensions).

The issue of codepage conversion __HAS BEEN SOLVED ONCE AND FOR ALL YEARS AGO, WITH UNICODE__. If someone, in 2017, such as the creators of `Ylmf_Ghost_Win7_SP1_x64_2017_0113.iso` (which by the way is unlikely to be an __official__ Windows 7 ISO, and therefore not something I would support in the first place) chose not to use Unicode names when mastering their image, then that issue is entirely theirs. In other words, I have no plans to make Rufus handle anything but ISOs that use Unicode. Other ISOs, such as yours, are unsupported.

**Comment by pbatard** [comment]
Oh and by the way, every single site that appears to be serving the ISO you are using is being flagged as a malware site by Google, so I'd rather avoid having anything to do with that.
