### ISSUE TITLE
Please help us understand what the users encountered?

### ISSUE THREAD

**Issue by VictorVG** [pbatard/rufus#980]
Started with the question:

> **bashaero**
> 
> Hello. What's wrong with x86 startup?
>  
> ![1](https://user-images.githubusercontent.com/906886/28242342-c5bbeef4-69b1-11e7-871d-cd42ab5fa54a.png)

I have no such phenomena, advised to disable UAC and EDS check, but after it turned out that two people have similar phenomena:

> **NOSS68**
> 
> I do not have either UAC or parental control, it was the message of the program itself at start-up, I wanted to put the screen here, consult. It was in the morning, there was no one on the forum, so I downloaded 2.15.1117 from offsite. This version started and worked fine.

> **BetterLink**
> 
> to **Victor_VG**
> 
> Your assemblies worked fine for me, but from the very beginning the same error started.
> UAC / Parental Control is disabled.
> If it was only a warning - OK.
> But first: a warning

![warning](https://user-images.githubusercontent.com/906886/28242354-01e21a66-69b2-11e7-889b-3f1d5faa0305.png)

, and when you try to run - the result

![crash](https://user-images.githubusercontent.com/906886/28242355-0b2d0c70-69b2-11e7-9df5-f4f8e508cf08.png)

. We have to use the official version.
>  
> Suspicion falls on problems with VisualC++2015 Redistributable. Perhaps, when installing a hefty modern application, this package was automatically replaced by 2017. Accordingly ... I can not now check the assumption.

I do not understand what can cause this behavior of the Win 7 OS, but I think that this is the reaction of some "beyond important security updates" from Microsoft.

**Comment by pbatard** [comment]
Sorry, but as I hope you can understand, I cannot support unofficial versions of Rufus, and especially, I will not provide any advice on how to remove the warning about using an unofficial version, which is there for a very good reason.

Also, if you do decide to provide your own binaries (Why? Where? To whom?), I __STRONGLY__ advise that you digitally sign them (__PLEASE__ get a code signing certificate if you haven't already done so, and sign your binaries!). If you can demonstrate that you only publish Rufus binaries that are digitally signed with your own code signing certificate, then maybe I'll be willing to help you with this. But otherwise, you're 100% on your own, because telling Windows users that they can run unsigned versions of elevated apps is exceedingly bad security practice and precisely the reason why I want to distance myself from anyone doing so.
