### ISSUE TITLE
Some well-known ISOs for open source software give an error at the moment - any chance of a fix?

### ISSUE THREAD

**Issue by stilez** [pbatard/rufus#987]
I'm a long term Rufus user - thank you!

I tried Rufus on 3 ISO images, all from well-known open source projects - FreeBSD (FreeBSD-11.0-RELEASE-amd64-dvd1.iso), FreeNAS (FreeNAS-11.0-U2.iso) and pfSense (pfSense-CE-2.3.4-RELEASE-amd64.iso).

All three are current versions, one is FreeBSD and the other two are based on FreeBSD (of course that doesn't mean they use the same ISO tools). FreeNAS can be put to USB by Rufus but the other two report unbootable or unknown format.  If they were proprietary I'd accept that as a good diagnosis, but they aren't.  Whatever they're doing they should be using standard ISO formats.

Any chance of a look and a fix?  Whatever it is probably affects other ISOs as well. 

Thanks!

**Comment by pbatard** [comment]
BSD/NAS do their own thing in terms of boot and bootloaders, and, unlike Linux, have chosen not to support FAT32 or any of the native Windows file system by default in their installers. This makes it a __major endeavour__ to try to support them, as you'd need to install a *BSD compatible file system driver in Windows before you can do anything.

As such, I have no plans to ever support anything *BSD based, because it's way more work than people realize: you can't just write an ISO-9660 or UDF file system onto an USB and expect that to work, because the bootloaders used for optical-mode and disk-mode are incompatible, and Rufus actually does a lot of work behind the scenes to work around this (such as needing to embed and copy out own versions of Syslinux or GRUB, because we can't use the ones that exist on an ISO... but of course, *BSD decided they would use neither).

However, you should be able to use the `.img` or compressed images that these distros provide, in DD-Image mode in Rufus.
